import unittest

from scripts.recommend_pr_lifecycle import (
    KNOWN_LIFECYCLE_LABELS,
    PullRequestContext,
    classify_source,
    recommend,
)
from test_check_pr_review_template import VALID_RUNTIME_BODY


def ctx(**overrides):
    values = {
        "number": 1,
        "title": "Update runtime",
        "body": VALID_RUNTIME_BODY,
        "base_ref": "main",
        "head_ref": "feature/runtime",
        "html_url": "https://github.com/drsapaev/final/pull/1",
        "is_draft": False,
        "mergeable": "MERGEABLE",
        "author_login": "drsapaev",
        "files": ("backend/app/api/v1/example.py",),
    }
    values.update(overrides)
    return PullRequestContext(**values)


class RecommendPRLifecycleTests(unittest.TestCase):
    def test_detects_v0_ai_marker(self):
        rec = recommend(ctx(title="v0 generated runtime panel"))

        self.assertIn("source:ai", rec.labels)

    def test_detects_jules_ai_marker(self):
        rec = recommend(ctx(body=VALID_RUNTIME_BODY + "\n\nGenerated by Jules."))

        self.assertIn("source:ai", rec.labels)

    def test_detects_codex_ai_marker(self):
        rec = recommend(ctx(head_ref="codex/runtime-validation"))

        self.assertIn("source:ai", rec.labels)

    def test_detects_claude_ai_marker(self):
        rec = recommend(ctx(title="Claude runtime cleanup"))

        self.assertIn("source:ai", rec.labels)

    def test_detects_ai_generated_marker(self):
        rec = recommend(ctx(body=VALID_RUNTIME_BODY + "\n\nAI-generated change."))

        self.assertIn("source:ai", rec.labels)

    def test_dependabot_gets_source_and_deps_risk(self):
        rec = recommend(
            ctx(
                author_login="app/dependabot",
                head_ref="dependabot/npm_and_yarn/root-npm-minor-patch",
                title="deps(deps): bump package group",
                body="Dependabot generated body",
                files=("frontend/package-lock.json",),
            )
        )

        self.assertIn("source:dependabot", rec.labels)
        self.assertIn("risk:deps", rec.labels)

    def test_ai_runtime_without_validation_needs_review_and_tests(self):
        rec = recommend(
            ctx(
                title="Codex runtime endpoint",
                body="AI-generated runtime change without validation proof.",
                files=("backend/app/api/v1/runtime.py",),
            )
        )

        self.assertIn("decision:needs-review", rec.labels)
        self.assertIn("decision:needs-tests", rec.labels)

    def test_possible_duplicate_is_label_only_not_close(self):
        rec = recommend(ctx(title="possible duplicate of #290", body=VALID_RUNTIME_BODY))

        self.assertIn("decision:possible-duplicate", rec.labels)
        self.assertNotIn("decision:should-close-candidate", rec.labels)
        self.assertTrue(
            any("close manually" in action for action in rec.next_actions),
            rec.next_actions,
        )

    def test_unrelated_labels_are_not_known_lifecycle_labels(self):
        self.assertNotIn("team:clinic", KNOWN_LIFECYCLE_LABELS)
        self.assertIn("source:ai", KNOWN_LIFECYCLE_LABELS)
        self.assertIn("source:dependabot", KNOWN_LIFECYCLE_LABELS)

    def test_recommendation_has_no_merge_or_close_action(self):
        rec = recommend(ctx(title="possible duplicate of #290", body=VALID_RUNTIME_BODY))
        text = "\n".join((*rec.decisions, *rec.next_actions)).lower()

        self.assertNotIn("auto-merge", text)
        self.assertNotIn("auto-close", text)

    def test_classify_source_can_return_both_ai_and_dependabot(self):
        labels = classify_source(
            ctx(
                author_login="app/dependabot",
                head_ref="dependabot/npm_and_yarn/codex-package",
            )
        )

        self.assertIn("source:ai", labels)
        self.assertIn("source:dependabot", labels)


if __name__ == "__main__":
    unittest.main()
