"""RQ-16.c: public-address registry for queue directions (D-03).

Owner decision 2026-09-17 (E-055, DECISION_PROPOSALS.md §«Решение владельца
по открытой точке RQ-16.c», trace 1a0ae53e51ec7769): the permanent public
address of a direction is ``/q/<public_code>`` where ``public_code`` is an
OPAQUE RANDOM server-generated identifier — never the direction title and
never the internal ``QueueProfile.key``.

Registry contract pinned by this model (E-055 §5):

- ``public_code`` is globally UNIQUE forever across the whole database
  (the URL has no clinic/profile namespace): a used code can never be
  reassigned — not after retire, not after a hard delete;
- at most ONE active (``retired_at IS NULL``) address per QueueProfile —
  partial unique index declared for both PostgreSQL and SQLite (test
  world), so the invariant holds even under a concurrent race;
- ``queue_profile_id`` is nullable with ON DELETE SET NULL: a permitted
  hard delete of the profile leaves the row behind as a tombstone, so the
  burned code stays reserved forever and can never point to a new entity
  (a recreated similar profile always gets a NEW code);
- rename of the profile never touches the address (the code is opaque and
  unrelated to title/key); archive (``is_active=False``) neither removes
  nor retires the row — reactivating the SAME profile restores the SAME
  address;
- canonical form is enforced at the DB level: fixed 12-char length and
  lowercase storage (``public_code = lower(public_code)``);
- no PII and no secret data: the code is a PUBLIC IDENTIFIER generated in
  canonical lowercase from a Crockford/Base32-like alphabet without
  ambiguous glyphs (0/1/i/l/o/u); join security is provided by the
  eligibility + short-lived session + token contract (D-03 APPROVED),
  never by the code itself.

Deliberately OUT OF SCOPE for this slice (RQ-16.c is MODEL only, E-055
§13): no ``/q`` frontend route, no public resolve/start endpoint, no
session issuance, no QR printing UI, no ``permanent_address`` flip (that
is RQ-16.d per E-055 §8), no provisioning of addresses for existing
profiles, no backfill. ``generate_public_code`` is the only provision-time
primitive provided here; wiring it into a provision/enable operation with
its collision-retry insert loop is RQ-16.d runtime.
"""

from __future__ import annotations

import secrets
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.db.base_class import Base

# Crockford/Base32-like lowercase alphabet: digits 2-9 plus ASCII letters
# without i/l/o/u (no ambiguous glyphs), 30 characters total. The code is
# a PUBLIC identifier (not a secret), so crypto-random selection over this
# URL-safe alphabet is sufficient; E-055 §2 fixes only the shape (12 chars,
# lowercase, Crockford/Base32-like) and leaves the exact library a
# technical implementation detail.
PUBLIC_CODE_ALPHABET = "23456789abcdefghjkmnpqrstvwxyz"
PUBLIC_CODE_LENGTH = 12


def generate_public_code() -> str:
    """Crypto-random opaque public code in canonical lowercase form.

    E-055 §3: generated by the server, ONCE, at the first provision/enable
    of the permanent address — never derived from title or key, never
    admin-typed. E-055 §11: the code is generated already in canonical
    lowercase; on the (astronomically unlikely) collision the provisioner
    retries with a freshly generated code until the unique insert succeeds
    — the global UNIQUE constraint is the arbiter. The retry loop itself
    belongs to the RQ-16.d runtime, not to this model slice.
    """
    return "".join(
        secrets.choice(PUBLIC_CODE_ALPHABET) for _ in range(PUBLIC_CODE_LENGTH)
    )


def normalize_public_code(value: str) -> str:
    """E-055 §11: the input boundary may normalize ASCII-case before a
    lookup, but exactly ONE canonical lowercase variant is stored in the
    DB. No locale-dependent transliteration happens here or anywhere else
    in the registry."""
    return value.strip().lower()


class QueueDirectionPublicAddress(Base):
    """Public-address registry row for one queue direction (QueueProfile).

    QueueProfile remains the direction/presentation entity (D-01): owning
    the public address does NOT make it a queue owner — Doctor.id and
    QueueResource.id stay separate identity spaces, and the RQ-16.d runtime
    resolves a direction into a concrete eligible owner through the
    canonical server resolver.
    """

    __tablename__ = "queue_direction_public_addresses"
    __table_args__ = (
        # Canonical form guardrails (portable SQL for PG + SQLite parity).
        CheckConstraint(
            "length(public_code) = 12",
            name="ck_qdpa_code_length",
        ),
        CheckConstraint(
            "public_code = lower(public_code)",
            name="ck_qdpa_code_canonical",
        ),
        # Globally UNIQUE forever — no partial predicate here on purpose:
        # retired rows and tombstones keep burning their code forever.
        UniqueConstraint("public_code", name="uq_qdpa_public_code"),
        # At most ONE active (retired_at IS NULL) address per profile.
        # The tombstone rows (queue_profile_id IS NULL) are excluded so a
        # burned code never blocks a fresh profile linkage again.
        # Partial on both PostgreSQL and SQLite (test world) — precedent
        # uq_push_devices_active_credential.
        Index(
            "uq_qdpa_one_active_per_profile",
            "queue_profile_id",
            unique=True,
            postgresql_where=text(
                "retired_at IS NULL AND queue_profile_id IS NOT NULL"
            ),
            sqlite_where=text(
                "retired_at IS NULL AND queue_profile_id IS NOT NULL"
            ),
        ),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    # Nullable with ON DELETE SET NULL: after a permitted hard delete the
    # profile may disappear, but the row stays behind as a tombstone so
    # the burned public_code can never be reassigned (E-055 §5).
    queue_profile_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("queue_profiles.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Opaque public identifier: 12 lowercase Crockford/Base32-like chars.
    # PUBLIC IDENTIFIER, not a secret — never logged as a credential, but
    # there is nothing to redact if it appears in a printed QR or URL.
    public_code: Mapped[str] = mapped_column(String(12), nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Lifecycle marker: NULL = active address; a timestamp retires the row
    # (rotation/revoke is an explicitly separate future workstream, E-055
    # §6 — nothing in RQ-16.c/.d writes this column from product flows).
    retired_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Read-side convenience only (E-055 §13 «model relationship»); the
    # direction stays a presentation entity — no backref on QueueProfile,
    # no lifecycle coupling beyond the FK.
    queue_profile = relationship("QueueProfile", foreign_keys=[queue_profile_id])
