export const ROUTE_GROUPS = ['public', 'onboarding', 'clinical', 'admin', 'internal-demo'];
export const ROUTE_SURFACES = ['screen', 'modal-route', 'callback', 'utility'];
export const ROUTE_LIFECYCLES = ['stable', 'compatibility', 'experimental', 'internal'];
export const ROUTE_SHELLS = ['landing', 'app-shell', 'fullscreen', 'callback', 'setup'];
export const ROUTE_AUTH = ['public', 'authenticated', 'role-scoped'];
export const ROUTE_ENTRY = ['menu', 'contextual', 'direct', 'callback', 'internal'];

export const ROLE_ALIASES = {
  receptionist: 'registrar',
  nurse: 'doctor',
};

export const ROLE_HOME_PRIORITY = [
  'admin',
  'cardio',
  'derma',
  'dentist',
  'registrar',
  'lab',
  'cashier',
  'doctor',
  'patient',
];

const AI_SIDEBAR_DISCLAIMER = 'Черновик · не медицинское заключение';
const AI_SIDEBAR_ACCESSIBLE_LABEL = 'AI-помощник: черновик, не диагноз, не медицинское заключение';
const AI_SIDEBAR_DISCLAIMER_META = {
  badge: AI_SIDEBAR_DISCLAIMER,
  tooltip: AI_SIDEBAR_ACCESSIBLE_LABEL,
  ariaLabel: AI_SIDEBAR_ACCESSIBLE_LABEL,
};

export const SIDEBAR_PRESETS = {
  admin: {
    navigation: 'path',
    defaultItem: 'admin-dashboard',
  },
  default: {
    navigation: 'path',
    defaultItem: 'clinical-search',
  },
  // P-016 fix: removed the `registrar`, `patient`, and `cashier` presets —
  // all routes that referenced them set hideSidebar:true, so the items below
  // were never rendered. The actual navigation for these roles lives in:
  //   - registrar: HeaderNew.jsx (hardcoded buttons) + ModernTabs in page body
  //   - patient:   TelegramMiniAppPatientShell (separate surface, no sidebar)
  //   - cashier:   HeaderNew.jsx (single "Касса" button) + tabs in CashierPanel
  // Keeping dead preset configuration here was misleading: it looked
  // authoritative but never surfaced in the UI.
  doctor: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'dashboard',
    items: [
      { id: 'dashboard', label: 'Обзор', icon: 'chart.bar' },
      { id: 'patients', label: 'Пациенты', icon: 'person.2' },
      { id: 'appointments', label: 'Записи', icon: 'calendar' },
      { id: 'queue', label: 'Очередь', icon: 'person.2' },
      { id: 'ai', label: 'AI-помощник', icon: 'brain', ...AI_SIDEBAR_DISCLAIMER_META },
      { id: 'reports', label: 'Отчёты', icon: 'doc.text' },
    ],
  },
  lab: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    items: [
      { id: 'queue', label: 'Очередь', icon: 'testtube.2' },
      { id: 'templates', label: 'Шаблоны', icon: 'rectangle.stack.badge.plus' },
      { id: 'reports', label: 'Бланки', icon: 'doc.text' },
    ],
  },
  cardiology: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    // Phase 4+ fix: reduced from 8 tabs to 4 flat tabs.
    // Goal: cardiologist workflow is "queue → visit" — everything else
    // (ecg/blood/ai/services/history) was either a separate tab for a tool
    // that belongs inside the visit (ecg, blood), or admin/lookup that
    // doesn't belong in the clinical workflow (services, history).
    //
    // The 4 remaining tabs:
    //   queue    — вход: вызвать следующего пациента из очереди
    //   visit    — единый экран приёма: анамнез + ЭКГ + анализы + диагноз + AI inline
    //   patients — поиск/история пациентов (включая бывший 'history' tab)
    //   ai       — AI-помощник (draft support, не диагноз)
    //
    // Muscle memory: 4 flat items, well under Miller's 7±2.
    items: [
      { id: 'queue',    label: 'Очередь',   icon: 'person.2' },
      { id: 'visit',    label: 'Приём',     icon: 'heart' },
      { id: 'patients', label: 'Пациенты',  icon: 'person.2' },
      { id: 'ai',       label: 'AI-помощник', icon: 'brain', ...AI_SIDEBAR_DISCLAIMER_META },
    ],
  },
  dermatology: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    // Phase 4+ fix: reduced from 9 tabs to 4 flat tabs.
    // Goal: dermatologist workflow is "queue → visit" — everything else
    // (photos/skin/cosmetic/ai/services/history) was either a separate tab
    // for a tool that belongs inside the visit (photos, skin, cosmetic),
    // or admin/lookup that doesn't belong in the clinical workflow.
    //
    // The 4 remaining tabs:
    //   queue    — вход: вызвать следующего пациента из очереди
    //   visit    — единый экран приёма: анамнез + фото + осмотр кожи + диагноз + AI inline
    //   patients — поиск/история пациентов (включая бывший 'history' tab)
    //   ai       — AI-помощник (draft support, не диагноз)
    items: [
      { id: 'queue',    label: 'Очередь',     icon: 'person.2' },
      { id: 'visit',    label: 'Приём',       icon: 'stethoscope' },
      { id: 'patients', label: 'Пациенты',    icon: 'person.2' },
      { id: 'ai',       label: 'AI-помощник', icon: 'brain', ...AI_SIDEBAR_DISCLAIMER_META },
    ],
  },
  dentistry: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    // Phase 4 fix: reduced from 13 tabs in 4 sections to 5 flat tabs.
    // Goal: dentist workflow is "queue → visit → patient/photos" — everything
    // else (examinations/diagnoses/dental-chart/treatment-plans/prosthetics/
    // templates/reports) was either dead UI (treatment-plans/prosthetics had
    // 501 backend stubs) or duplicated the visit screen (dental-chart
    // duplicated the chart embedded in the visit; examinations/diagnoses
    // were merged into EMR v2 visit screen).
    //
    // The 5 remaining tabs:
    //   queue    — вход: вызвать следующего пациента из очереди
    //   visit    — единый экран приёма: анамнез + схема зубов + Дополнительно
    //   patients — поиск/история пациентов
    //   photos   — фотоархив (рентген + intraoral)
    //   ai-assistant — AI-помощник (draft support, не диагноз)
    //
    // Muscle memory: 5 flat items, well under Miller's 7±2.
    items: [
      { id: 'queue',         label: 'Очередь',      icon: 'list.number' },
      { id: 'visit',         label: 'Приём',        icon: 'stethoscope' },
      { id: 'patients',      label: 'Пациенты',     icon: 'person.2' },
      { id: 'photos',        label: 'Фотоархив',    icon: 'camera' },
      { id: 'ai-assistant',  label: 'AI-помощник',  icon: 'brain', ...AI_SIDEBAR_DISCLAIMER_META },
    ],
  },
};

const stable = 'stable';
const internal = 'internal';

function nav(meta) {
  return meta || false;
}

function layout(meta = {}) {
  return meta;
}

export const ROUTE_REGISTRY = [
  {
    id: 'landing',
    path: '/',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'landing',
    auth: 'public',
    roles: [],
    entry: 'menu',
    nav: false,
    title: 'Clinic Management System',
    owner: 'marketing.landing',
    component: 'Landing',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Clinic Management System' }),
  },
  {
    id: 'login',
    path: '/login',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'landing',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Login',
    owner: 'iam.auth',
    component: 'LoginFormStyled',
    legacyRedirectFrom: ['/old-login'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Login' }),
  },
  {
    id: 'change-password-required',
    path: '/change-password-required',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'authenticated',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Change Password Required',
    owner: 'iam.auth',
    component: 'ChangePasswordRequired',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Change Password Required' }),
  },
  {
    id: 'health',
    path: '/health',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'System Health',
    owner: 'platform.ops',
    component: 'Health',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'System Health' }),
  },
  {
    id: 'queue-join',
    path: '/queue/join',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Join Queue',
    owner: 'queue.public',
    component: 'QueueJoin',
    legacyRedirectFrom: ['/pwa/queue'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Join Queue' }),
  },
  {
    id: 'queue-join-token',
    path: '/queue/join/:token',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Join Queue',
    owner: 'queue.public',
    component: 'QueueJoin',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Join Queue' }),
  },
  {
    id: 'telegram-mini-app-patient',
    path: '/telegram/mini-app/patient',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Telegram Mini App Patient',
    owner: 'telegram.mini_app',
    component: 'TelegramMiniAppPatientShell',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, fullscreen: true, pageTitle: 'Telegram Mini App Patient' }),
  },
  {
    id: 'payment-success',
    path: '/payment/success',
    group: 'public',
    surface: 'callback',
    lifecycle: stable,
    shell: 'callback',
    auth: 'public',
    roles: [],
    entry: 'callback',
    nav: false,
    title: 'Payment Success',
    owner: 'billing.payments',
    component: 'PaymentSuccess',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Payment Success' }),
  },
  {
    id: 'payment-cancel',
    path: '/payment/cancel',
    group: 'public',
    surface: 'callback',
    lifecycle: stable,
    shell: 'callback',
    auth: 'public',
    roles: [],
    entry: 'callback',
    nav: false,
    title: 'Payment Cancelled',
    owner: 'billing.payments',
    component: 'PaymentCancel',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Payment Cancelled' }),
  },
  {
    id: 'display-board',
    path: '/display-board',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Display Board',
    owner: 'queue.display',
    component: 'DisplayBoardUnified',
    legacyRedirectFrom: ['/queue-board', '/display'],
    layout: layout({ hideHeader: true, hideSidebar: true, fullscreen: true, pageTitle: 'Display Board' }),
  },
  {
    id: 'display-board-role',
    path: '/display-board/:role',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Display Board',
    owner: 'queue.display',
    component: 'DisplayBoardUnified',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, fullscreen: true, pageTitle: 'Display Board' }),
  },
  {
    id: 'setup',
    path: '/setup',
    group: 'onboarding',
    surface: 'screen',
    lifecycle: stable,
    shell: 'setup',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Clinic Setup',
    owner: 'platform.setup',
    component: 'Setup',
    legacyRedirectFrom: ['/register'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Clinic Setup' }),
  },
  {
    id: 'admin-dashboard',
    path: '/admin',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    homeForRoles: ['admin'],
    entry: 'menu',
    nav: nav({ label: 'Обзор', icon: 'chart.bar', section: 'Обзор', order: 10, menu: true, sidebar: true }),
    title: 'Админ: обзор',
    owner: 'admin.operations',
    component: 'AdminDashboard',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-dashboard', pageTitle: 'Обзор' }),
  },
  {
    id: 'admin-analytics',
    path: '/admin/analytics',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Аналитика', icon: 'chart.bar', section: 'Обзор', order: 10, sidebar: true }),
    title: 'Админ: аналитика',
    owner: 'admin.analytics',
    component: 'AnalyticsPage',
    legacyRedirectFrom: ['/analytics'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-analytics', pageTitle: 'Аналитика' }),
  },
  {
    id: 'admin-webhooks',
    path: '/admin/webhooks',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false, // IA PR-2: demoted to direct-only (tab inside UnifiedIntegrations hub)
    title: 'Админ: вебхуки',
    owner: 'admin.integrations',
    component: 'WebhookManager',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-webhooks', pageTitle: 'Вебхуки' }),
  },
  {
    id: 'admin-reports',
    path: '/admin/reports',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Отчеты', icon: 'file-text', section: 'Обзор', order: 20, sidebar: true }),
    title: 'Admin Reports',
    owner: 'admin.reports',
    component: 'UnifiedReports',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-reports', pageTitle: 'Admin Reports' }),
  },
  {
    id: 'admin-system',
    path: '/admin/system',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Система', icon: 'gear', section: 'Система', order: 50, sidebar: true }),
    title: 'Admin System',
    owner: 'admin.system',
    component: 'SystemManagement',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-system', pageTitle: 'Admin System' }),
  },
  {
    id: 'admin-cloud-printing',
    path: '/admin/cloud-printing',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false, // IA PR-2: demoted to direct-only (tab inside UnifiedIntegrations hub)
    title: 'Admin Cloud Printing',
    owner: 'admin.operations',
    component: 'CloudPrintingManager',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-cloud-printing', pageTitle: 'Admin Cloud Printing' }),
  },
  {
    id: 'admin-medical-equipment',
    path: '/admin/medical-equipment',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false, // IA PR-2: demoted to direct-only (tab inside UnifiedIntegrations hub)
    title: 'Admin Medical Equipment',
    owner: 'admin.operations',
    component: 'MedicalEquipmentManager',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-medical-equipment', pageTitle: 'Admin Medical Equipment' }),
  },
  {
    id: 'admin-graphql-explorer',
    path: '/admin/graphql-explorer',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false, // IA PR-2: demoted to direct-only (tab inside UnifiedIntegrations hub)
    title: 'Admin GraphQL Explorer',
    owner: 'admin.integrations',
    component: 'GraphQLExplorer',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-graphql-explorer', pageTitle: 'Admin GraphQL Explorer' }),
  },
  {
    id: 'admin-users',
    path: '/admin/users',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Пользователи', icon: 'users', section: 'Система', order: 10, sidebar: true }),
    title: 'Admin Users',
    owner: 'admin.users',
    component: 'UnifiedUserManagement',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-users', pageTitle: 'Admin Users' }),
  },
  {
    id: 'admin-doctors',
    path: '/admin/doctors',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Врачи', icon: 'user-plus', section: 'Пациенты и запись', order: 20, sidebar: true }),
    title: 'Admin Doctors',
    owner: 'admin.users',
    component: 'AdminDoctors',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-doctors', pageTitle: 'Admin Doctors' }),
  },
  {
    id: 'admin-services',
    path: '/admin/services',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Услуги', icon: 'list', section: 'Клиника и очередь', order: 50, sidebar: true }),
    title: 'Admin Services',
    owner: 'admin.catalog',
    component: 'AdminServices',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-services', pageTitle: 'Admin Services' }),
  },
  {
    id: 'admin-queue-cabinet-management',
    path: '/admin/queue-cabinet-management',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Кабинеты очередей', icon: 'building', section: 'Клиника и очередь', order: 20, sidebar: true }),
    title: 'Admin Queue Cabinets',
    owner: 'admin.queue',
    component: 'QueueCabinetManagement',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-queue-cabinet-management', pageTitle: 'Admin Queue Cabinets' }),
  },
  {
    id: 'admin-patients',
    path: '/admin/patients',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Пациенты', icon: 'users', section: 'Пациенты и запись', order: 10, sidebar: true }),
    title: 'Admin Patients',
    owner: 'admin.patients',
    component: 'AdminPatients',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-patients', pageTitle: 'Admin Patients' }),
  },
  {
    id: 'admin-appointments',
    path: '/admin/appointments',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Записи', icon: 'calendar', section: 'Пациенты и запись', order: 30, sidebar: true }),
    title: 'Admin Appointments',
    owner: 'admin.scheduling',
    component: 'AdminAppointments',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-appointments', pageTitle: 'Admin Appointments' }),
  },
  {
    id: 'admin-all-free',
    path: '/admin/all-free',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Заявки All Free', icon: 'exclamationmark.triangle', section: 'Пациенты и запись', order: 40, sidebar: true }),
    title: 'Admin All Free',
    owner: 'admin.operations',
    component: 'AllFreeApproval',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-all-free', pageTitle: 'Admin All Free' }),
  },
  {
    id: 'admin-benefit-settings',
    path: '/admin/benefit-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ label: 'Льготы и скидки', icon: 'percent', section: 'Финансы', order: 30, sidebar: true }),
    title: 'Admin Benefit Settings',
    owner: 'admin.billing',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-benefit-settings', pageTitle: 'Admin Benefit Settings' }),
  },
  {
    id: 'admin-wizard-settings',
    path: '/admin/wizard-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ label: 'Мастер записи', icon: 'wand.and.stars', section: 'Пациенты и запись', order: 50, sidebar: true }),
    title: 'Admin Wizard Settings',
    owner: 'admin.settings',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-wizard-settings', pageTitle: 'Admin Wizard Settings' }),
  },
  {
    id: 'admin-payment-providers',
    path: '/admin/payment-providers',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ label: 'Платёжные системы', icon: 'creditcard', section: 'Финансы', order: 20, sidebar: true }),
    title: 'Admin Payment Providers',
    owner: 'admin.billing',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-payment-providers', pageTitle: 'Admin Payment Providers' }),
  },
  {
    id: 'admin-clinic-management',
    path: '/admin/clinic-management',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Управление клиникой', icon: 'building', section: 'Клиника и очередь', order: 10, sidebar: true }),
    title: 'Admin Clinic Management',
    owner: 'admin.operations',
    component: 'ClinicManagement',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-clinic-management', pageTitle: 'Admin Clinic Management' }),
  },
  {
    id: 'admin-clinic-settings',
    path: '/admin/clinic-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ label: 'Профиль клиники', icon: 'building', section: 'Клиника и очередь', order: 55, sidebar: true }),
    title: 'Admin Clinic Settings',
    owner: 'admin.settings',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-clinic-settings', pageTitle: 'Admin Clinic Settings' }),
  },
  {
    id: 'admin-queue-settings',
    path: '/admin/queue-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ label: 'Настройки очереди', icon: 'list.bullet', section: 'Клиника и очередь', order: 30, sidebar: true }),
    title: 'Admin Queue Settings',
    owner: 'admin.queue',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-queue-settings', pageTitle: 'Admin Queue Settings' }),
  },
  {
    id: 'admin-ai-settings',
    path: '/admin/ai-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'AI Инструменты', icon: 'brain', section: 'Система', order: 20, sidebar: true, ...AI_SIDEBAR_DISCLAIMER_META }),
    title: 'Admin AI Settings',
    owner: 'admin.ai',
    component: 'AISettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-ai-settings', pageTitle: 'Admin AI Settings' }),
  },
  {
    id: 'admin-telegram-settings',
    path: '/admin/telegram-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ label: 'Настройки Telegram', icon: 'paperplane', section: 'Коммуникации', order: 30, sidebar: true }),
    title: 'Admin Telegram Settings',
    owner: 'admin.telegram',
    component: 'TelegramSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-telegram-settings', pageTitle: 'Admin Telegram Settings' }),
  },
  {
    id: 'admin-display-settings',
    path: '/admin/display-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ label: 'Табло очереди', icon: 'tv', section: 'Клиника и очередь', order: 40, sidebar: true }),
    title: 'Admin Display Settings',
    owner: 'admin.queue',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-display-settings', pageTitle: 'Admin Display Settings' }),
  },
  {
    id: 'admin-telegram-integration',
    path: '/admin/integrations/telegram',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    // P1 architectural fix (Sprint 3): demoted to entry:'direct' + nav:false to
    // remove duplicate Telegram sidebar entry. The canonical Telegram surface is
    // admin-telegram-settings (Настройки section) — it covers bot token, webhook,
    // test messages, and stats. TelegramManager (this route) is a richer bot-
    // management surface (commands, onboarding requests) that remains reachable
    // via direct URL /admin/integrations/telegram and via legacy redirect from
    // /telegram-integration, but no longer clutters the sidebar.
    entry: 'direct',
    nav: false,
    title: 'Admin Telegram Integration',
    owner: 'admin.telegram',
    component: 'TelegramManager',
    legacyRedirectFrom: ['/telegram-integration'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-telegram-integration', pageTitle: 'Admin Telegram Integration' }),
  },
  {
    id: 'admin-notifications',
    path: '/admin/notifications',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Уведомления', icon: 'bell', section: 'Коммуникации', order: 10, sidebar: true }),
    title: 'Admin Notifications',
    owner: 'admin.notifications',
    component: 'EmailSMSManager',
    legacyRedirectFrom: ['/notifications'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-notifications', pageTitle: 'Admin Notifications' }),
  },
  {
    id: 'admin-push-notifications',
    path: '/admin/push-notifications',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Push-уведомления', icon: 'bell', section: 'Коммуникации', order: 20, sidebar: true }),
    title: 'Admin Push Notifications',
    owner: 'admin.notifications',
    component: 'UnifiedNotifications',
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-push-notifications', pageTitle: 'Admin Push Notifications' }),
  },
  {
    id: 'admin-phone-verification',
    path: '/admin/phone-verification',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Верификация телефонов', icon: 'phone', section: 'Коммуникации', order: 40, sidebar: true }),
    title: 'Admin Phone Verification',
    owner: 'admin.integrations',
    component: 'PhoneVerificationManager',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-phone-verification', pageTitle: 'Admin Phone Verification' }),
  },
  {
    id: 'admin-activation',
    path: '/admin/activation',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Активация', icon: 'key', section: 'Система', order: 40, sidebar: true }),
    title: 'Admin Activation',
    owner: 'admin.licensing',
    component: 'ActivationSystem',
    legacyRedirectFrom: ['/activation'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-activation', pageTitle: 'Admin Activation' }),
  },
  {
    id: 'admin-finance',
    path: '/admin/finance',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Финансы', icon: 'dollarsign.circle', section: 'Финансы', order: 10, sidebar: true }),
    title: 'Admin Finance',
    owner: 'admin.billing',
    component: 'UnifiedFinance',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-finance', pageTitle: 'Admin Finance' }),
  },
  {
    id: 'admin-settings',
    path: '/admin/settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Настройки', icon: 'gear', section: 'Система', order: 80, sidebar: true, menu: true }),
    title: 'Admin Settings',
    owner: 'admin.settings',
    component: 'Settings',
    legacyRedirectFrom: ['/settings'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-settings', pageTitle: 'Admin Settings' }),
  },
  {
    id: 'admin-security',
    path: '/admin/security',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Безопасность', icon: 'lock', section: 'Система', order: 20, sidebar: true }),
    title: 'Admin Security',
    owner: 'admin.security',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-security', pageTitle: 'Admin Security' }),
  },
  {
    id: 'admin-audit',
    path: '/admin/audit',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Аудит', icon: 'list', section: 'Система', order: 30, sidebar: true }),
    title: 'Admin Audit',
    owner: 'admin.audit',
    component: 'Audit',
    legacyRedirectFrom: ['/audit'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-audit', pageTitle: 'Admin Audit' }),
  },
  {
    id: 'admin-file-management',
    path: '/admin/file-management',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor'],
    entry: 'direct',
    nav: false, // IA PR-2: demoted to direct-only (tab inside UnifiedIntegrations hub)
    title: 'File Management',
    owner: 'admin.files',
    component: 'FileManager',
    legacyRedirectFrom: ['/file-management'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-file-management', pageTitle: 'File Management' }),
  },
  {
    id: 'admin-integrations',
    path: '/admin/integrations',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Интеграции', icon: 'puzzlepiece', section: 'Система', order: 55, sidebar: true }),
    title: 'Admin Integrations',
    owner: 'admin.integrations',
    component: 'UnifiedIntegrations',
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-integrations', pageTitle: 'Интеграции' }),
  },
  {
    id: 'admin-user-select',
    path: '/admin/user-select',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false,
    title: 'Admin User Switcher',
    owner: 'admin.users',
    component: 'UserSelect',
    legacyRedirectFrom: ['/user-select'],
    layout: layout({ sidebarPreset: 'admin', pageTitle: 'Admin User Switcher' }),
  },
  {
    id: 'registrar-home',
    path: '/registrar',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar'],
    homeForRoles: ['registrar', 'receptionist'],
    entry: 'direct',
    nav: nav({ label: 'Регистратура', icon: 'users', section: 'Clinical', order: 10, menu: true }),
    title: 'Registrar Panel',
    owner: 'clinical.registrar',
    component: 'RegistrarPanel',
    legacyRedirectFrom: ['/registrar-panel'],
    layout: layout({ hideSidebar: true, pageTitle: 'Registrar Panel' }),
  },
  // Strategic Direction 3: canonical nested routes for registrar views.
  // These replace the legacy ?view= query param pattern. Backward compat
  // is maintained: ?view=welcome still works (handled by currentView useMemo).
  // See frontend/src/pages/registrar/registrarNavigation.js for helpers.
  {
    id: 'registrar-welcome',
    path: '/registrar/welcome',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar'],
    entry: 'direct',
    nav: false,
    title: 'Registrar — Welcome Dashboard',
    owner: 'clinical.registrar',
    component: 'RegistrarPanel',
    layout: layout({ hideSidebar: true, pageTitle: 'Registrar — Welcome' }),
  },
  {
    id: 'registrar-queue',
    path: '/registrar/queue',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar'],
    entry: 'direct',
    nav: false,
    title: 'Registrar — Online Queue',
    owner: 'clinical.registrar',
    component: 'RegistrarPanel',
    layout: layout({ hideSidebar: true, pageTitle: 'Registrar — Queue' }),
  },
  {
    id: 'doctor-home',
    path: '/doctor',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor'],
    homeForRoles: ['doctor', 'nurse'],
    entry: 'menu',
    nav: nav({ label: 'Врач', icon: 'stethoscope', section: 'Clinical', order: 20, menu: true }),
    title: 'Doctor Panel',
    owner: 'clinical.doctor',
    component: 'DoctorPanel',
    legacyRedirectFrom: ['/doctor-panel'],
    layout: layout({ sidebarPreset: 'doctor', pageTitle: 'Doctor Panel' }),
  },
  {
    id: 'cashier-home',
    path: '/cashier',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Cashier'],
    homeForRoles: ['cashier'],
    entry: 'menu',
    nav: nav({ label: 'Касса', icon: 'creditcard', section: 'Clinical', order: 30, menu: true }),
    title: 'Cashier Panel',
    owner: 'clinical.cashier',
    component: 'CashierPanel',
    legacyRedirectFrom: ['/cashier-panel'],
    layout: layout({ hideSidebar: true, pageTitle: 'Cashier Panel' }),
  },
  {
    id: 'lab-home',
    path: '/lab',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Lab'],
    homeForRoles: ['lab'],
    entry: 'menu',
    nav: nav({ label: 'Лаборатория', icon: 'testtube.2', section: 'Clinical', order: 40, menu: true }),
    title: 'Lab Panel',
    owner: 'clinical.lab',
    component: 'LabPanel',
    legacyRedirectFrom: ['/lab-panel'],
    layout: layout({ sidebarPreset: 'lab', pageTitle: 'Lab Panel' }),
  },
  {
    id: 'patient-home',
    path: '/patient',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    // P-001 fix: previously roles omitted 'Patient', so a patient logging in via the
    // standard form was bounced to /forbidden by RouteAccessBoundary because
    // homeForRoles:['patient'] pointed them here while the role guard for the route
    // rejected them. Patient role is now included so the home-route resolves and
    // the guard accepts the patient. Admin/Registrar/Doctor retain access for
    // support / debug purposes.
    roles: ['Admin', 'Registrar', 'Doctor', 'Patient'],
    homeForRoles: ['patient'],
    entry: 'direct',
    nav: false,
    title: 'Patient Panel',
    owner: 'clinical.patient',
    component: 'PatientPanel',
    legacyRedirectFrom: ['/patient-panel'],
    layout: layout({ hideSidebar: true, pageTitle: 'Patient Panel' }),
  },
  {
    id: 'doctor-cardiology',
    path: '/doctor/cardiology',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'cardio'],
    homeForRoles: ['cardio'],
    homeForUsernames: ['cardio@example.com'],
    entry: 'menu',
    nav: nav({ label: 'Кардиология', icon: 'heart', section: 'Clinical', order: 50, menu: true }),
    title: 'Cardiology Panel',
    owner: 'clinical.cardiology',
    component: 'CardiologistPanelUnified',
    legacyRedirectFrom: ['/cardiologist'],
    layout: layout({ fullscreen: true, sidebarPreset: 'cardiology', pageTitle: 'Cardiology Panel' }),
  },
  {
    id: 'doctor-dermatology',
    path: '/doctor/dermatology',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'derma'],
    homeForRoles: ['derma'],
    homeForUsernames: ['derma@example.com'],
    entry: 'menu',
    nav: nav({ label: 'Дерматология', icon: 'face.smiling', section: 'Clinical', order: 60, menu: true }),
    title: 'Dermatology Panel',
    owner: 'clinical.dermatology',
    component: 'DermatologistPanelUnified',
    legacyRedirectFrom: ['/dermatologist'],
    layout: layout({ fullscreen: true, sidebarPreset: 'dermatology', pageTitle: 'Dermatology Panel' }),
  },
  {
    id: 'doctor-dentistry',
    path: '/doctor/dentistry',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'dentist'],
    homeForRoles: ['dentist'],
    homeForUsernames: ['dentist@example.com'],
    entry: 'menu',
    nav: nav({ label: 'Стоматология', icon: 'smile', section: 'Clinical', order: 70, menu: true }),
    title: 'Dentistry Panel',
    owner: 'clinical.dentistry',
    component: 'DentistPanelUnified',
    legacyRedirectFrom: ['/dentist'],
    layout: layout({ fullscreen: true, sidebarPreset: 'dentistry', pageTitle: 'Dentistry Panel' }),
  },
  {
    id: 'clinical-scheduler',
    path: '/clinical/scheduler',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'Registrar'],
    entry: 'menu',
    nav: nav({ label: 'Расписание', icon: 'calendar', section: 'Clinical', order: 80, menu: true }),
    title: 'Clinical Scheduler',
    owner: 'clinical.scheduling',
    component: 'Scheduler',
    legacyRedirectFrom: ['/scheduler'],
    layout: layout({ sidebarPreset: 'default', activeSidebarItem: 'clinical-scheduler', pageTitle: 'Clinical Scheduler' }),
  },
  {
    id: 'clinical-appointments',
    path: '/clinical/appointments',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    // P-014 fix: previously roles:[Admin, Registrar] excluded Doctor, Cashier, Lab.
    // Cashier needs to look up appointments to take payments; Lab needs to find
    // patients for sample collection; Doctor needs to see schedules of peers.
    // All clinical roles now have read access to the appointments list.
    roles: ['Admin', 'Doctor', 'Registrar', 'Cashier', 'Lab', 'cardio', 'derma', 'dentist'],
    entry: 'menu',
    nav: nav({ label: 'Записи', icon: 'calendar', section: 'Clinical', order: 90, menu: true }),
    title: 'Clinical Appointments',
    owner: 'clinical.scheduling',
    component: 'Appointments',
    legacyRedirectFrom: ['/appointments'],
    layout: layout({ sidebarPreset: 'default', activeSidebarItem: 'clinical-appointments', pageTitle: 'Clinical Appointments' }),
  },
  {
    id: 'clinical-search',
    path: '/clinical/search',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    // P-014 fix: previously excluded Cashier and Lab. Both roles need patient
    // lookup to do their jobs (find a patient for payment / sample collection).
    roles: ['Admin', 'Doctor', 'Registrar', 'Cashier', 'Lab', 'cardio', 'derma', 'dentist'],
    entry: 'menu',
    nav: nav({ label: 'Поиск', icon: 'magnifyingglass', section: 'Clinical', order: 100, menu: true }),
    title: 'Clinical Search',
    owner: 'clinical.search',
    component: 'Search',
    legacyRedirectFrom: ['/search'],
    layout: layout({ sidebarPreset: 'default', activeSidebarItem: 'clinical-search', pageTitle: 'Clinical Search' }),
  },
  {
    id: 'clinical-profile',
    path: '/clinical/profile',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'authenticated',
    roles: [],
    entry: 'contextual',
    nav: false,
    title: 'User Profile',
    owner: 'iam.profile',
    component: 'UserProfile',
    legacyRedirectFrom: ['/profile'],
    layout: layout({ hideSidebar: true, pageTitle: 'User Profile' }),
  },
  {
    id: 'clinical-visit-details',
    path: '/clinical/visits/:id',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'Registrar', 'cardio', 'derma', 'dentist'],
    entry: 'contextual',
    nav: false,
    title: 'Visit Details',
    owner: 'clinical.emr',
    component: 'VisitDetails',
    legacyRedirectFrom: ['/visits/:id'],
    layout: layout({ sidebarPreset: 'default', pageTitle: 'Visit Details' }),
  },
  {
    id: 'clinical-pickup',
    path: '/clinical/pickup/:patientId',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar', 'Cashier', 'Lab', 'Doctor', 'cardio', 'derma', 'dentist'],
    entry: 'contextual',
    nav: false,
    title: 'Patient Pickup',
    owner: 'clinical.patient',
    component: 'PatientPickupView',
    legacyRedirectFrom: ['/pickup/:patientId'],
    layout: layout({ sidebarPreset: 'default', pageTitle: 'Patient Pickup' }),
  },
  {
    id: 'internal-demo-medilab',
    path: '/internal-demo/medilab',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'MediLab Demo',
    owner: 'internal.demo',
    component: 'MediLabDemo',
    legacyRedirectFrom: [
      '/medilab-demo',
      '/medilab-demo/dashboard',
      '/medilab-demo/patients',
      '/medilab-demo/appointments',
      '/medilab-demo/staff-schedule',
    ],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'MediLab Demo' }),
  },
  {
    id: 'internal-demo-macos',
    path: '/internal-demo/macos',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'macOS Demo',
    owner: 'internal.demo',
    component: 'MacOSDemoPage',
    legacyRedirectFrom: ['/macos-demo'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'macOS Demo' }),
  },
  {
    id: 'internal-demo-integration',
    path: '/internal-demo/integration',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'Integration Demo',
    owner: 'internal.demo',
    component: 'IntegrationDemo',
    legacyRedirectFrom: ['/integration-demo'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Integration Demo' }),
  },
  {
    id: 'internal-demo-payment-test',
    path: '/internal-demo/payment-test',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'Payment Test',
    owner: 'internal.demo',
    component: 'PaymentTest',
    legacyRedirectFrom: ['/payment/test'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Payment Test' }),
  },
  {
    id: 'internal-demo-css-test',
    path: '/internal-demo/css-test',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'CSS Test',
    owner: 'internal.demo',
    component: 'CSSTestPage',
    legacyRedirectFrom: ['/css-test'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'CSS Test' }),
  },
  // SW-01 fix: removed internal-demo-buttons route (ButtonShowcase component deleted)
  {
    id: 'unauthorized',
    path: '/unauthorized',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Unauthorized',
    owner: 'platform.routing',
    component: 'UnauthorizedPage',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Unauthorized' }),
  },
  {
    id: 'forbidden',
    path: '/forbidden',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Forbidden',
    owner: 'platform.routing',
    component: 'ForbiddenPage',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Forbidden' }),
  },
  {
    id: 'not-found',
    path: '/not-found',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Not Found',
    owner: 'platform.routing',
    component: 'NotFoundPage',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Not Found' }),
  },
];

export function getCanonicalRoutes() {
  return ROUTE_REGISTRY;
}
