import {
  AlertTriangle, BarChart3, Bell, Brain, Building2, Calendar, Camera,
  CircleDollarSign, CreditCard, FileText, Heart, KeyRound, List, ListOrdered,
  Lock, Monitor, Percent, Phone, Puzzle, Search, Send, Settings, Smile,
  SquareStack, Stethoscope, TestTube2, UserPlus, Users, Wand2,
} from 'lucide-react';

export const ROUTE_GROUPS = ['public', 'onboarding', 'clinical', 'admin', 'internal-demo'];
export const ROUTE_SURFACES = ['screen', 'modal-route', 'callback', 'utility'];
export const ROUTE_LIFECYCLES = ['stable', 'compatibility', 'experimental', 'internal'];
export const ROUTE_SHELLS = ['landing', 'app-shell', 'fullscreen', 'callback', 'setup'];
export const ROUTE_AUTH = ['public', 'authenticated', 'role-scoped'];
export const ROUTE_ENTRY = ['menu', 'contextual', 'direct', 'callback', 'internal'];

// REC-3 (Receptionist deprecation): the receptionist alias was removed —
// Registrar is the canonical front-desk role; legacy 'Receptionist'
// profiles no longer reach registrar routes (route parity test pins the
// deny; stale cached profiles are purged by clearAuthCache). The
// nurse -> doctor alias is a separate policy decision, untouched here.
export const ROLE_ALIASES = {
  nurse: 'doctor',
};

export const ROLE_HOME_PRIORITY = [
  'admin',
  'cardio',
  'derma',
  'dentist',
  'registrar',
  'lab',
  'cashier',
  'doctor',
  'patient',
];

// PR-UI-19 (C-6, Codex round 1): the AI safety disclaimer is user-visible in
// doctor/specialist sidebars (badge + hover tooltip + screen-reader name) and
// must follow the active language — carried as i18n keys, resolved in Sidebar.
const AI_SIDEBAR_DISCLAIMER_META = {
  badgeKey: 'nav.ai_disclaimer_badge',
  tooltipKey: 'nav.ai_disclaimer_aria',
  ariaLabelKey: 'nav.ai_disclaimer_aria',
};

export const SIDEBAR_PRESETS = {
  admin: {
    navigation: 'path',
    defaultItem: 'admin-dashboard',
  },
  default: {
    navigation: 'path',
    defaultItem: 'clinical-search',
  },
  // PR-UI-04: restored registrar preset (P-016 fix partially reversed).
  // Cashier sidebar restored — AppShell migration complete for all clinical roles.
  // Patient remains on TelegramMiniAppPatientShell (separate surface).
  registrar: {
    navigation: 'path',
    defaultItem: 'registrar-home',
    items: [
      { id: 'registrar-home', labelKey: 'nav.overview', icon: BarChart3, to: '/registrar/welcome' },
      { id: 'registrar-queue', labelKey: 'nav.queue', icon: Users, to: '/registrar/queue' },
      { id: 'clinical-appointments', labelKey: 'nav.appointments', icon: Calendar, to: '/clinical/appointments' },
      { id: 'clinical-search', labelKey: 'nav.patients', icon: Users, to: '/clinical/search' },
    ],
  },
  // PR-UI-04b: restored cashier preset (completes AppShell migration).
  // P-014 TIGHTEN: the appointments nav item (clinical-appointments) was
  // removed from the Cashier sidebar — that route is canonical trio
  // (Admin/Doctor/Registrar) again, and non-admin presets are not
  // access-filtered, so a stale entry here would render a dead link that
  // lands Cashier on /forbidden. Payment workflows for Cashier live on
  // /cashier (pending-payments feed), not on the shared appointments screen.
  // admin-finance excluded — role-scoped to Admin only.
  cashier: {
    navigation: 'path',
    defaultItem: 'cashier-home',
    items: [
      { id: 'cashier-home', labelKey: 'nav.cashier', icon: CreditCard, to: '/cashier' },
    ],
  },
  doctor: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'dashboard',
    items: [
      { id: 'dashboard', labelKey: 'nav.overview', icon: BarChart3 },
      { id: 'patients', labelKey: 'nav.patients', icon: Users },
      { id: 'appointments', labelKey: 'nav.appointments', icon: Calendar },
      { id: 'queue', labelKey: 'nav.queue', icon: Users },
      { id: 'ai', labelKey: 'nav.ai_assistant', icon: Brain, ...AI_SIDEBAR_DISCLAIMER_META },
      { id: 'reports', labelKey: 'nav.reports', icon: FileText },
    ],
  },
  lab: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    items: [
      { id: 'queue', labelKey: 'nav.queue', icon: TestTube2 },
      { id: 'templates', labelKey: 'nav.templates', icon: SquareStack },
      { id: 'reports', labelKey: 'nav.blanks', icon: FileText },
    ],
  },
  cardiology: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    // Phase 4+ fix: reduced from 8 tabs to 4 flat tabs.
    // Goal: cardiologist workflow is "queue → visit" — everything else
    // (ecg/blood/ai/services/history) was either a separate tab for a tool
    // that belongs inside the visit (ecg, blood), or admin/lookup that
    // doesn't belong in the clinical workflow (services, history).
    //
    // The 4 remaining tabs:
    //   queue    — вход: вызвать следующего пациента из очереди
    //   visit    — единый экран приёма: анамнез + ЭКГ + анализы + диагноз + AI inline
    //   patients — поиск/история пациентов (включая бывший 'history' tab)
    //   ai       — AI-помощник (draft support, не диагноз)
    //
    // Muscle memory: 4 flat items, well under Miller's 7±2.
    items: [
      { id: 'queue',    labelKey: 'nav.queue',   icon: Users },
      { id: 'visit',    labelKey: 'nav.visit',     icon: Heart },
      { id: 'patients', labelKey: 'nav.patients',  icon: Users },
      { id: 'ai',       labelKey: 'nav.ai_assistant', icon: Brain, ...AI_SIDEBAR_DISCLAIMER_META },
    ],
  },
  dermatology: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    // Phase 4+ fix: reduced from 9 tabs to 4 flat tabs.
    // Goal: dermatologist workflow is "queue → visit" — everything else
    // (photos/skin/cosmetic/ai/services/history) was either a separate tab
    // for a tool that belongs inside the visit (photos, skin, cosmetic),
    // or admin/lookup that doesn't belong in the clinical workflow.
    //
    // The 4 remaining tabs:
    //   queue    — вход: вызвать следующего пациента из очереди
    //   visit    — единый экран приёма: анамнез + фото + осмотр кожи + диагноз + AI inline
    //   patients — поиск/история пациентов (включая бывший 'history' tab)
    //   ai       — AI-помощник (draft support, не диагноз)
    items: [
      { id: 'queue',    labelKey: 'nav.queue',     icon: Users },
      { id: 'visit',    labelKey: 'nav.visit',       icon: Stethoscope },
      { id: 'patients', labelKey: 'nav.patients',    icon: Users },
      { id: 'ai',       labelKey: 'nav.ai_assistant', icon: Brain, ...AI_SIDEBAR_DISCLAIMER_META },
    ],
  },
  dentistry: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    // Phase 4 fix: reduced from 13 tabs in 4 sections to 5 flat tabs.
    // Goal: dentist workflow is "queue → visit → patient/photos" — everything
    // else (examinations/diagnoses/dental-chart/treatment-plans/prosthetics/
    // templates/reports) was either dead UI (treatment-plans/prosthetics had
    // 501 backend stubs) or duplicated the visit screen (dental-chart
    // duplicated the chart embedded in the visit; examinations/diagnoses
    // were merged into EMR v2 visit screen).
    //
    // The 5 remaining tabs:
    //   queue    — вход: вызвать следующего пациента из очереди
    //   visit    — единый экран приёма: анамнез + схема зубов + Дополнительно
    //   patients — поиск/история пациентов
    //   photos   — фотоархив (рентген + intraoral)
    //   ai-assistant — AI-помощник (draft support, не диагноз)
    //
    // Muscle memory: 5 flat items, well under Miller's 7±2.
    items: [
      { id: 'queue',         labelKey: 'nav.queue',      icon: ListOrdered },
      { id: 'visit',         labelKey: 'nav.visit',        icon: Stethoscope },
      { id: 'patients',      labelKey: 'nav.patients',     icon: Users },
      { id: 'photos',        labelKey: 'nav.photo_archive',    icon: Camera },
      { id: 'ai-assistant',  labelKey: 'nav.ai_assistant',  icon: Brain, ...AI_SIDEBAR_DISCLAIMER_META },
    ],
  },
};

const stable = 'stable';
const internal = 'internal';

function nav(meta: Record<string, unknown> | undefined): Record<string, unknown> | false {
  return meta || false;
}

function layout(meta: Record<string, unknown> = {}): Record<string, unknown> {
  return meta;
}

export const ROUTE_REGISTRY = [
  {
    id: 'landing',
    path: '/',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'landing',
    auth: 'public',
    roles: [],
    entry: 'menu',
    nav: false,
    title: 'Clinic OS',
    owner: 'marketing.landing',
    component: 'Landing',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Clinic OS' }),
  },
  {
    id: 'reset-password',
    path: '/reset-password',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'landing',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Reset Password',
    owner: 'iam.auth',
    component: 'ResetPasswordPage',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Reset Password' }),
  },
  {
    id: 'login',
    path: '/login',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'landing',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Login',
    owner: 'iam.auth',
    component: 'LoginFormStyled',
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Login' }),
  },
  {
    id: 'change-password-required',
    path: '/change-password-required',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'authenticated',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Change Password Required',
    owner: 'iam.auth',
    component: 'ChangePasswordRequired',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Change Password Required' }),
  },
  {
    id: 'health',
    path: '/health',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'System Health',
    owner: 'platform.ops',
    component: 'Health',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'System Health' }),
  },
  {
    id: 'queue-join',
    path: '/queue/join',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Join Queue',
    owner: 'queue.public',
    component: 'QueueJoin',
    legacyRedirectFrom: ['/pwa/queue'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Join Queue' }),
  },
  {
    id: 'queue-join-token',
    path: '/queue/join/:token',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Join Queue',
    owner: 'queue.public',
    component: 'QueueJoin',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Join Queue' }),
  },
  {
    id: 'telegram-mini-app-patient',
    path: '/telegram/mini-app/patient',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Telegram Mini App Patient',
    owner: 'telegram.mini_app',
    component: 'TelegramMiniAppPatientShell',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, fullscreen: true, pageTitle: 'Telegram Mini App Patient' }),
  },
  {
    id: 'payment-success',
    path: '/payment/success',
    group: 'public',
    surface: 'callback',
    lifecycle: stable,
    shell: 'callback',
    auth: 'public',
    roles: [],
    entry: 'callback',
    nav: false,
    title: 'Payment Success',
    owner: 'billing.payments',
    component: 'PaymentSuccess',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Payment Success' }),
  },
  {
    id: 'payment-cancel',
    path: '/payment/cancel',
    group: 'public',
    surface: 'callback',
    lifecycle: stable,
    shell: 'callback',
    auth: 'public',
    roles: [],
    entry: 'callback',
    nav: false,
    title: 'Payment Cancelled',
    owner: 'billing.payments',
    component: 'PaymentCancel',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Payment Cancelled' }),
  },
  {
    id: 'display-board',
    path: '/display-board',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Display Board',
    owner: 'queue.display',
    component: 'DisplayBoardUnified',
    legacyRedirectFrom: ['/queue-board', '/display'],
    layout: layout({ hideHeader: true, hideSidebar: true, fullscreen: true, pageTitle: 'Display Board' }),
  },
  {
    id: 'display-board-role',
    path: '/display-board/:role',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Display Board',
    owner: 'queue.display',
    component: 'DisplayBoardUnified',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, fullscreen: true, pageTitle: 'Display Board' }),
  },
  {
    id: 'setup',
    path: '/setup',
    group: 'onboarding',
    surface: 'screen',
    lifecycle: stable,
    shell: 'setup',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Clinic Setup',
    owner: 'platform.setup',
    component: 'Setup',
    legacyRedirectFrom: ['/register'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Clinic Setup' }),
  },
  {
    id: 'admin-dashboard',
    path: '/admin',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    homeForRoles: ['admin'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.overview', icon: BarChart3, sectionKey: 'nav.overview', order: 10, menu: true, sidebar: true }),
    title: 'Админ: обзор',
    owner: 'admin.operations',
    component: 'AdminDashboard',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-dashboard', pageTitle: 'Обзор' }),
  },
  {
    id: 'admin-analytics',
    path: '/admin/analytics',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.analytics', icon: BarChart3, sectionKey: 'nav.overview', order: 20, sidebar: true }),
    title: 'Админ: аналитика',
    owner: 'admin.analytics',
    component: 'AnalyticsPage',
    legacyRedirectFrom: ['/analytics'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-analytics', pageTitle: 'Аналитика' }),
  },
  {
    id: 'admin-webhooks',
    path: '/admin/webhooks',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false, // IA PR-2: demoted to direct-only (tab inside UnifiedIntegrations hub)
    title: 'Админ: вебхуки',
    owner: 'admin.integrations',
    component: 'WebhookManager',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-webhooks', pageTitle: 'Вебхуки' }),
  },
  {
    id: 'admin-reports',
    path: '/admin/reports',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.reports_alt', icon: FileText, sectionKey: 'nav.overview', order: 20, sidebar: true }),
    title: 'Admin Reports',
    owner: 'admin.reports',
    component: 'UnifiedReports',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-reports', pageTitle: 'Admin Reports' }),
  },
  {
    id: 'admin-system',
    path: '/admin/system',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.system', icon: Settings, sectionKey: 'nav.system', order: 50, sidebar: true }),
    title: 'Admin System',
    owner: 'admin.system',
    component: 'SystemManagement',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-system', pageTitle: 'Admin System' }),
  },
  {
    id: 'admin-cloud-printing',
    path: '/admin/cloud-printing',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false, // IA PR-2: demoted to direct-only (tab inside UnifiedIntegrations hub)
    title: 'Admin Cloud Printing',
    owner: 'admin.operations',
    component: 'CloudPrintingManager',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-cloud-printing', pageTitle: 'Admin Cloud Printing' }),
  },
  {
    id: 'admin-medical-equipment',
    path: '/admin/medical-equipment',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false, // IA PR-2: demoted to direct-only (tab inside UnifiedIntegrations hub)
    title: 'Admin Medical Equipment',
    owner: 'admin.operations',
    component: 'MedicalEquipmentManager',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-medical-equipment', pageTitle: 'Admin Medical Equipment' }),
  },
  {
    id: 'admin-graphql-explorer',
    path: '/admin/graphql-explorer',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false, // IA PR-2: demoted to direct-only (tab inside UnifiedIntegrations hub)
    title: 'Admin GraphQL Explorer',
    owner: 'admin.integrations',
    component: 'GraphQLExplorer',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-graphql-explorer', pageTitle: 'Admin GraphQL Explorer' }),
  },
  {
    id: 'admin-users',
    path: '/admin/users',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.users', icon: Users, sectionKey: 'nav.system', order: 10, sidebar: true }),
    title: 'Admin Users',
    owner: 'admin.users',
    component: 'UnifiedUserManagement',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-users', pageTitle: 'Admin Users' }),
  },
  {
    id: 'admin-doctors',
    path: '/admin/doctors',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.doctors', icon: UserPlus, sectionKey: 'nav.section_patients_booking', order: 20, sidebar: true }),
    title: 'Admin Doctors',
    owner: 'admin.users',
    component: 'AdminDoctors',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-doctors', pageTitle: 'Admin Doctors' }),
  },
  {
    id: 'admin-services',
    path: '/admin/services',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.services', icon: List, sectionKey: 'nav.section_clinic_queue', order: 50, sidebar: true }),
    title: 'Admin Services',
    owner: 'admin.catalog',
    component: 'AdminServices',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-services', pageTitle: 'Admin Services' }),
  },
  {
    id: 'admin-queue-cabinet-management',
    path: '/admin/queue-cabinet-management',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.queue_rooms', icon: Building2, sectionKey: 'nav.section_clinic_queue', order: 20, sidebar: true }),
    title: 'Admin Queue Cabinets',
    owner: 'admin.queue',
    component: 'QueueCabinetManagement',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-queue-cabinet-management', pageTitle: 'Admin Queue Cabinets' }),
  },
  {
    id: 'admin-patients',
    path: '/admin/patients',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.patients', icon: Users, sectionKey: 'nav.section_patients_booking', order: 10, sidebar: true }),
    title: 'Admin Patients',
    owner: 'admin.patients',
    component: 'AdminPatients',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-patients', pageTitle: 'Admin Patients' }),
  },
  {
    id: 'admin-appointments',
    path: '/admin/appointments',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.appointments', icon: Calendar, sectionKey: 'nav.section_patients_booking', order: 30, sidebar: true }),
    title: 'Admin Appointments',
    owner: 'admin.scheduling',
    component: 'AdminAppointments',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-appointments', pageTitle: 'Admin Appointments' }),
  },
  {
    id: 'admin-all-free',
    path: '/admin/all-free',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.allfree_requests', icon: AlertTriangle, sectionKey: 'nav.section_patients_booking', order: 40, sidebar: true }),
    title: 'Admin All Free',
    owner: 'admin.operations',
    component: 'AllFreeApproval',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-all-free', pageTitle: 'Admin All Free' }),
  },
  {
    id: 'admin-benefit-settings',
    path: '/admin/benefit-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ labelKey: 'nav.discounts', icon: Percent, sectionKey: 'nav.finance', order: 30, sidebar: true }),
    title: 'Admin Benefit Settings',
    owner: 'admin.billing',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-benefit-settings', pageTitle: 'Admin Benefit Settings' }),
  },
  {
    id: 'admin-wizard-settings',
    path: '/admin/wizard-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ labelKey: 'nav.booking_wizard', icon: Wand2, sectionKey: 'nav.section_patients_booking', order: 50, sidebar: true }),
    title: 'Admin Wizard Settings',
    owner: 'admin.settings',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-wizard-settings', pageTitle: 'Admin Wizard Settings' }),
  },
  {
    id: 'admin-payment-providers',
    path: '/admin/payment-providers',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ labelKey: 'nav.payment_systems', icon: CreditCard, sectionKey: 'nav.finance', order: 20, sidebar: true }),
    title: 'Admin Payment Providers',
    owner: 'admin.billing',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-payment-providers', pageTitle: 'Admin Payment Providers' }),
  },
  {
    id: 'admin-clinic-management',
    path: '/admin/clinic-management',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.clinic_management', icon: Building2, sectionKey: 'nav.section_clinic_queue', order: 10, sidebar: true }),
    title: 'Admin Clinic Management',
    owner: 'admin.operations',
    component: 'ClinicManagement',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-clinic-management', pageTitle: 'Admin Clinic Management' }),
  },
  {
    id: 'admin-clinic-settings',
    path: '/admin/clinic-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ labelKey: 'nav.clinic_profile', icon: Building2, sectionKey: 'nav.section_clinic_queue', order: 55, sidebar: true }),
    title: 'Admin Clinic Settings',
    owner: 'admin.settings',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-clinic-settings', pageTitle: 'Admin Clinic Settings' }),
  },
  {
    id: 'admin-queue-settings',
    path: '/admin/queue-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ labelKey: 'nav.queue_settings', icon: List, sectionKey: 'nav.section_clinic_queue', order: 30, sidebar: true }),
    title: 'Admin Queue Settings',
    owner: 'admin.queue',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-queue-settings', pageTitle: 'Admin Queue Settings' }),
  },
  {
    id: 'admin-ai-settings',
    path: '/admin/ai-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.ai_tools', icon: Brain, sectionKey: 'nav.system', order: 20, sidebar: true, ...AI_SIDEBAR_DISCLAIMER_META }),
    title: 'Admin AI Settings',
    owner: 'admin.ai',
    component: 'AISettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-ai-settings', pageTitle: 'Admin AI Settings' }),
  },
  {
    id: 'admin-telegram-settings',
    path: '/admin/telegram-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ labelKey: 'nav.telegram_settings', icon: Send, sectionKey: 'nav.section_communications', order: 30, sidebar: true }),
    title: 'Admin Telegram Settings',
    owner: 'admin.telegram',
    component: 'TelegramSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-telegram-settings', pageTitle: 'Admin Telegram Settings' }),
  },
  {
    id: 'admin-display-settings',
    path: '/admin/display-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    // P-003 fix: surfaced in sidebar (previously nav:false — orphan route).
    nav: nav({ labelKey: 'nav.queue_board', icon: Monitor, sectionKey: 'nav.section_clinic_queue', order: 40, sidebar: true }),
    title: 'Admin Display Settings',
    owner: 'admin.queue',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-display-settings', pageTitle: 'Admin Display Settings' }),
  },
  {
    id: 'admin-telegram-integration',
    path: '/admin/integrations/telegram',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    // P1 architectural fix (Sprint 3): demoted to entry:'direct' + nav:false to
    // remove duplicate Telegram sidebar entry. The canonical Telegram surface is
    // admin-telegram-settings (Настройки section) — it covers bot token, webhook,
    // test messages, and stats. TelegramManager (this route) is a richer bot-
    // management surface (commands, onboarding requests) that remains reachable
    // via direct URL /admin/integrations/telegram and via legacy redirect from
    // /telegram-integration, but no longer clutters the sidebar.
    entry: 'direct',
    nav: false,
    title: 'Admin Telegram Integration',
    owner: 'admin.telegram',
    component: 'TelegramManager',
    legacyRedirectFrom: ['/telegram-integration'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-telegram-integration', pageTitle: 'Admin Telegram Integration' }),
  },
  {
    id: 'admin-notifications',
    path: '/admin/notifications',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.notifications', icon: Bell, sectionKey: 'nav.section_communications', order: 10, sidebar: true }),
    title: 'Admin Notifications',
    owner: 'admin.notifications',
    component: 'EmailSMSManager',
    legacyRedirectFrom: ['/notifications'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-notifications', pageTitle: 'Admin Notifications' }),
  },
  {
    id: 'admin-push-notifications',
    path: '/admin/push-notifications',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.push_notifications', icon: Bell, sectionKey: 'nav.section_communications', order: 20, sidebar: true }),
    title: 'Admin Push Notifications',
    owner: 'admin.notifications',
    component: 'UnifiedNotifications',
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-push-notifications', pageTitle: 'Admin Push Notifications' }),
  },
  {
    id: 'admin-phone-verification',
    path: '/admin/phone-verification',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.phone_verification', icon: Phone, sectionKey: 'nav.section_communications', order: 40, sidebar: true }),
    title: 'Admin Phone Verification',
    owner: 'admin.integrations',
    component: 'PhoneVerificationManager',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-phone-verification', pageTitle: 'Admin Phone Verification' }),
  },
  {
    id: 'admin-activation',
    path: '/admin/activation',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.activation', icon: KeyRound, sectionKey: 'nav.system', order: 40, sidebar: true }),
    title: 'Admin Activation',
    owner: 'admin.licensing',
    component: 'ActivationSystem',
    legacyRedirectFrom: ['/activation'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-activation', pageTitle: 'Admin Activation' }),
  },
  {
    id: 'admin-finance',
    path: '/admin/finance',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.finance', icon: CircleDollarSign, sectionKey: 'nav.finance', order: 10, sidebar: true }),
    title: 'Admin Finance',
    owner: 'admin.billing',
    component: 'UnifiedFinance',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-finance', pageTitle: 'Admin Finance' }),
  },
  {
    id: 'admin-settings',
    path: '/admin/settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.settings', icon: Settings, sectionKey: 'nav.system', order: 80, sidebar: true, menu: true }),
    title: 'Admin Settings',
    owner: 'admin.settings',
    component: 'Settings',
    legacyRedirectFrom: ['/settings'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-settings', pageTitle: 'Admin Settings' }),
  },
  {
    id: 'admin-security',
    path: '/admin/security',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.security', icon: Lock, sectionKey: 'nav.system', order: 30, sidebar: true }),
    title: 'Admin Security',
    owner: 'admin.security',
    component: 'UnifiedSettings',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-security', pageTitle: 'Admin Security' }),
  },
  {
    id: 'admin-audit',
    path: '/admin/audit',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.audit', icon: List, sectionKey: 'nav.system', order: 30, sidebar: true }),
    title: 'Admin Audit',
    owner: 'admin.audit',
    component: 'Audit',
    legacyRedirectFrom: ['/audit'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-audit', pageTitle: 'Admin Audit' }),
  },
  {
    id: 'admin-file-management',
    path: '/admin/file-management',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor'],
    entry: 'direct',
    nav: false, // IA PR-2: demoted to direct-only (tab inside UnifiedIntegrations hub)
    title: 'File Management',
    owner: 'admin.files',
    component: 'FileManager',
    legacyRedirectFrom: ['/file-management'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-file-management', pageTitle: 'File Management' }),
  },
  {
    id: 'admin-integrations',
    path: '/admin/integrations',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.integrations', icon: Puzzle, sectionKey: 'nav.system', order: 55, sidebar: true }),
    title: 'Admin Integrations',
    owner: 'admin.integrations',
    component: 'UnifiedIntegrations',
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-integrations', pageTitle: 'Интеграции' }),
  },
  {
    id: 'admin-user-select',
    path: '/admin/user-select',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false,
    title: 'Admin User Switcher',
    owner: 'admin.users',
    component: 'UserSelect',
    legacyRedirectFrom: ['/user-select'],
    layout: layout({ sidebarPreset: 'admin', pageTitle: 'Admin User Switcher' }),
  },
  {
    id: 'registrar-home',
    path: '/registrar',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar'],
    homeForRoles: ['registrar', 'receptionist'],
    entry: 'direct',
    nav: nav({ labelKey: 'nav.registrar', icon: Users, sectionKey: 'nav.section_clinical', order: 10, menu: true }),
    title: 'Registrar Panel',
    owner: 'clinical.registrar',
    component: 'RegistrarPanel',
    legacyRedirectFrom: ['/registrar-panel'],
    layout: layout({ sidebarPreset: 'registrar', activeSidebarItem: 'registrar-home', pageTitle: 'Registrar Panel' }),
  },
  // Strategic Direction 3: canonical nested routes for registrar views.
  // These replace the legacy ?view= query param pattern. Backward compat
  // is maintained: ?view=welcome still works (handled by currentView useMemo).
  // See frontend/src/pages/registrar/registrarNavigation.js for helpers.
  {
    id: 'registrar-welcome',
    path: '/registrar/welcome',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar'],
    entry: 'direct',
    nav: false,
    title: 'Registrar — Welcome Dashboard',
    owner: 'clinical.registrar',
    component: 'RegistrarPanel',
    layout: layout({ sidebarPreset: 'registrar', activeSidebarItem: 'registrar-home', pageTitle: 'Registrar — Welcome' }),
  },
  {
    id: 'registrar-queue',
    path: '/registrar/queue',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar'],
    entry: 'direct',
    nav: false,
    title: 'Registrar — Online Queue',
    owner: 'clinical.registrar',
    component: 'RegistrarPanel',
    layout: layout({ sidebarPreset: 'registrar', activeSidebarItem: 'registrar-queue', pageTitle: 'Registrar — Queue' }),
  },
  {
    id: 'doctor-home',
    path: '/doctor',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor'],
    homeForRoles: ['doctor', 'nurse'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.doctor', icon: Stethoscope, sectionKey: 'nav.section_clinical', order: 20, menu: true }),
    title: 'Doctor Panel',
    owner: 'clinical.doctor',
    component: 'DoctorPanel',
    legacyRedirectFrom: ['/doctor-panel'],
    layout: layout({ sidebarPreset: 'doctor', pageTitle: 'Doctor Panel' }),
  },
  {
    id: 'cashier-home',
    path: '/cashier',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Cashier'],
    homeForRoles: ['cashier'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.cashier', icon: CreditCard, sectionKey: 'nav.section_clinical', order: 30, menu: true }),
    title: 'Cashier Panel',
    owner: 'clinical.cashier',
    component: 'CashierPanel',
    legacyRedirectFrom: ['/cashier-panel'],
    layout: layout({ sidebarPreset: 'cashier', activeSidebarItem: 'cashier-home', pageTitle: 'Cashier Panel' }),
  },
  {
    id: 'lab-home',
    path: '/lab',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Lab'],
    homeForRoles: ['lab'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.lab', icon: TestTube2, sectionKey: 'nav.section_clinical', order: 40, menu: true }),
    title: 'Lab Panel',
    owner: 'clinical.lab',
    component: 'LabPanel',
    legacyRedirectFrom: ['/lab-panel'],
    layout: layout({ sidebarPreset: 'lab', pageTitle: 'Lab Panel' }),
  },
  {
    id: 'patient-home',
    path: '/patient',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    // P-001 fix: previously roles omitted 'Patient', so a patient logging in via the
    // standard form was bounced to /forbidden by RouteAccessBoundary because
    // homeForRoles:['patient'] pointed them here while the role guard for the route
    // rejected them. Patient role is now included so the home-route resolves and
    // the guard accepts the patient. Admin/Registrar/Doctor retain access for
    // support / debug purposes.
    roles: ['Admin', 'Registrar', 'Doctor', 'Patient'],
    homeForRoles: ['patient'],
    entry: 'direct',
    nav: false,
    title: 'Patient Panel',
    owner: 'clinical.patient',
    component: 'PatientPanel',
    legacyRedirectFrom: ['/patient-panel'],
    layout: layout({ hideSidebar: true, pageTitle: 'Patient Panel' }),
  },
  {
    id: 'doctor-cardiology',
    path: '/doctor/cardiology',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'cardio'],
    homeForRoles: ['cardio'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.cardiology', icon: Heart, sectionKey: 'nav.section_clinical', order: 50, menu: true }),
    title: 'Cardiology Panel',
    owner: 'clinical.cardiology',
    component: 'CardiologistPanelUnified',
    legacyRedirectFrom: ['/cardiologist'],
    layout: layout({ fullscreen: true, sidebarPreset: 'cardiology', pageTitle: 'Cardiology Panel' }),
  },
  {
    id: 'doctor-dermatology',
    path: '/doctor/dermatology',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'derma'],
    homeForRoles: ['derma'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.dermatology', icon: Smile, sectionKey: 'nav.section_clinical', order: 60, menu: true }),
    title: 'Dermatology Panel',
    owner: 'clinical.dermatology',
    component: 'DermatologistPanelUnified',
    legacyRedirectFrom: ['/dermatologist'],
    layout: layout({ fullscreen: true, sidebarPreset: 'dermatology', pageTitle: 'Dermatology Panel' }),
  },
  {
    id: 'doctor-dentistry',
    path: '/doctor/dentistry',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'dentist'],
    homeForRoles: ['dentist'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.dentistry', icon: Smile, sectionKey: 'nav.section_clinical', order: 70, menu: true }),
    title: 'Dentistry Panel',
    owner: 'clinical.dentistry',
    component: 'DentistPanelUnified',
    legacyRedirectFrom: ['/dentist'],
    layout: layout({ fullscreen: true, sidebarPreset: 'dentistry', pageTitle: 'Dentistry Panel' }),
  },
  {
    id: 'clinical-scheduler',
    path: '/clinical/scheduler',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'Registrar'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.schedule', icon: Calendar, sectionKey: 'nav.section_clinical', order: 80, menu: true }),
    title: 'Clinical Scheduler',
    owner: 'clinical.scheduling',
    component: 'Scheduler',
    legacyRedirectFrom: ['/scheduler'],
    layout: layout({ sidebarPreset: 'default', activeSidebarItem: 'clinical-scheduler', pageTitle: 'Clinical Scheduler' }),
  },
  {
    id: 'clinical-appointments',
    path: '/clinical/appointments',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    // P-014 TIGHTEN: canonical access for Appointments/Scheduler is the
    // Admin/Doctor/Registrar trio (matches clinical-scheduler above, the page
    // RoleGate on Appointments.tsx, and backend require_roles). The historical
    // widening to Cashier/Lab/cardio/derma/dentist was route-level only and
    // decorative: those roles were 403-rejected by the backend list endpoint
    // (doctor-family scoping; page never sends doctor_id), so the extra entry
    // points exposed dead UI reachability and /forbidden landings, not access.
    // The Cashier payment-facing surface (/appointments/pending-payments and
    // /cashier) is preserved separately — see APPOINTMENT_PENDING_PAYMENT_ROLES.
    roles: ['Admin', 'Doctor', 'Registrar'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.appointments', icon: Calendar, sectionKey: 'nav.section_clinical', order: 90, menu: true }),
    title: 'Clinical Appointments',
    owner: 'clinical.scheduling',
    component: 'Appointments',
    legacyRedirectFrom: ['/appointments'],
    layout: layout({ sidebarPreset: 'default', activeSidebarItem: 'clinical-appointments', pageTitle: 'Clinical Appointments' }),
  },
  {
    id: 'clinical-search',
    path: '/clinical/search',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    // P-014 fix: previously excluded Cashier and Lab. Both roles need patient
    // lookup to do their jobs (find a patient for payment / sample collection).
    roles: ['Admin', 'Doctor', 'Registrar', 'Cashier', 'Lab', 'cardio', 'derma', 'dentist'],
    entry: 'menu',
    nav: nav({ labelKey: 'nav.search', icon: Search, sectionKey: 'nav.section_clinical', order: 100, menu: true }),
    title: 'Clinical Search',
    owner: 'clinical.search',
    component: 'Search',
    legacyRedirectFrom: ['/search'],
    layout: layout({ sidebarPreset: 'default', activeSidebarItem: 'clinical-search', pageTitle: 'Clinical Search' }),
  },
  {
    id: 'clinical-profile',
    path: '/clinical/profile',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'authenticated',
    roles: [],
    entry: 'contextual',
    nav: false,
    title: 'User Profile',
    owner: 'iam.profile',
    component: 'UserProfile',
    legacyRedirectFrom: ['/profile'],
    layout: layout({ hideSidebar: true, pageTitle: 'User Profile' }),
  },
  {
    id: 'clinical-pickup',
    path: '/clinical/pickup/:patientId',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar', 'Cashier', 'Lab', 'Doctor', 'cardio', 'derma', 'dentist'],
    entry: 'contextual',
    nav: false,
    title: 'Patient Pickup',
    owner: 'clinical.patient',
    component: 'PatientPickupView',
    legacyRedirectFrom: ['/pickup/:patientId'],
    layout: layout({ sidebarPreset: 'default', pageTitle: 'Patient Pickup' }),
  },
  {
    id: 'internal-demo-macos',
    path: '/internal-demo/macos',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'macOS Demo',
    owner: 'internal.demo',
    component: 'MacOSDemoPage',
    legacyRedirectFrom: ['/macos-demo'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'macOS Demo' }),
  },
  {
    id: 'internal-demo-integration',
    path: '/internal-demo/integration',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'Integration Demo',
    owner: 'internal.demo',
    component: 'IntegrationDemo',
    legacyRedirectFrom: ['/integration-demo'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Integration Demo' }),
  },
  {
    id: 'internal-demo-payment-test',
    path: '/internal-demo/payment-test',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'Payment Test',
    owner: 'internal.demo',
    component: 'PaymentTest',
    legacyRedirectFrom: ['/payment/test'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Payment Test' }),
  },
  {
    id: 'internal-demo-css-test',
    path: '/internal-demo/css-test',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'CSS Test',
    owner: 'internal.demo',
    component: 'CSSTestPage',
    legacyRedirectFrom: ['/css-test'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'CSS Test' }),
  },
  // SW-01 fix: removed internal-demo-buttons route (ButtonShowcase component deleted)
  {
    id: 'unauthorized',
    path: '/unauthorized',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Unauthorized',
    owner: 'platform.routing',
    component: 'UnauthorizedPage',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Unauthorized' }),
  },
  {
    id: 'forbidden',
    path: '/forbidden',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Forbidden',
    owner: 'platform.routing',
    component: 'ForbiddenPage',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Forbidden' }),
  },
  {
    id: 'not-found',
    path: '/not-found',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Not Found',
    owner: 'platform.routing',
    component: 'NotFoundPage',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Not Found' }),
  },
];

export function getCanonicalRoutes() {
  return ROUTE_REGISTRY;
}
