export const ROUTE_GROUPS = ['public', 'onboarding', 'clinical', 'admin', 'internal-demo'];
export const ROUTE_SURFACES = ['screen', 'modal-route', 'callback', 'utility'];
export const ROUTE_LIFECYCLES = ['stable', 'compatibility', 'experimental', 'internal'];
export const ROUTE_SHELLS = ['landing', 'app-shell', 'fullscreen', 'callback', 'setup'];
export const ROUTE_AUTH = ['public', 'authenticated', 'role-scoped'];
export const ROUTE_ENTRY = ['menu', 'contextual', 'direct', 'callback', 'internal'];

export const ROLE_ALIASES = {
  receptionist: 'registrar',
  nurse: 'doctor',
};

export const ROLE_HOME_PRIORITY = [
  'admin',
  'cardio',
  'derma',
  'dentist',
  'registrar',
  'lab',
  'cashier',
  'doctor',
  'patient',
];

export const SIDEBAR_PRESETS = {
  admin: {
    navigation: 'path',
    defaultItem: 'admin-dashboard',
  },
  default: {
    navigation: 'path',
    defaultItem: 'clinical-search',
  },
  registrar: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'welcome',
    items: [
      { id: 'welcome', label: 'Welcome', icon: 'house' },
      { id: 'appointments', label: 'All Appointments', icon: 'calendar' },
      { id: 'cardio', label: 'Cardiology', icon: 'heart' },
      { id: 'echokg', label: 'ECG', icon: 'waveform.path.ecg' },
      { id: 'derma', label: 'Dermatology', icon: 'face.smiling' },
      { id: 'dental', label: 'Dentistry', icon: 'smile' },
      { id: 'lab', label: 'Laboratory', icon: 'testtube.2' },
      { id: 'procedures', label: 'Procedures', icon: 'list' },
      { id: 'queue', label: 'Online Queue', icon: 'list' },
    ],
  },
  doctor: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'dashboard',
    items: [
      { id: 'dashboard', label: 'Dashboard', icon: 'chart.bar' },
      { id: 'patients', label: 'Patients', icon: 'person.2' },
      { id: 'appointments', label: 'Appointments', icon: 'calendar' },
      { id: 'ai', label: 'AI Assistant', icon: 'brain' },
      { id: 'reports', label: 'Reports', icon: 'doc.text' },
    ],
  },
  patient: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'appointments',
    items: [
      { id: 'appointments', label: 'Appointments', icon: 'calendar' },
      { id: 'results', label: 'Test Results', icon: 'doc.text' },
      { id: 'profile', label: 'Profile', icon: 'person' },
    ],
  },
  cashier: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'dashboard',
    items: [
      { id: 'dashboard', label: 'Dashboard', icon: 'chart.bar' },
      { id: 'payments', label: 'Payments', icon: 'creditcard' },
      { id: 'appointments', label: 'Appointments', icon: 'calendar' },
      { id: 'reports', label: 'Reports', icon: 'doc.text' },
      { id: 'settings', label: 'Settings', icon: 'gear' },
    ],
  },
  lab: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    items: [
      { id: 'queue', label: 'Очередь', icon: 'testtube.2' },
      { id: 'templates', label: 'Шаблоны', icon: 'rectangle.stack.badge.plus' },
      { id: 'reports', label: 'Бланки', icon: 'doc.text' },
    ],
  },
  cardiology: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    items: [
      { id: 'queue', label: 'Queue', icon: 'person.2' },
      { id: 'appointments', label: 'Appointments', icon: 'calendar' },
      { id: 'visit', label: 'Visit', icon: 'heart' },
      { id: 'ecg', label: 'ECG', icon: 'waveform.path.ecg' },
      { id: 'blood', label: 'Blood Tests', icon: 'testtube.2' },
      { id: 'ai', label: 'AI Assistant', icon: 'brain' },
      { id: 'services', label: 'Services', icon: 'stethoscope' },
      { id: 'history', label: 'History', icon: 'doc.text' },
    ],
  },
  dermatology: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'queue',
    items: [
      { id: 'queue', label: 'Queue', icon: 'person.2' },
      { id: 'appointments', label: 'Appointments', icon: 'calendar' },
      { id: 'visit', label: 'Visit', icon: 'stethoscope' },
      { id: 'patients', label: 'Patients', icon: 'person' },
      { id: 'photos', label: 'Photos', icon: 'camera' },
      { id: 'skin', label: 'Skin Examination', icon: 'eye' },
      { id: 'cosmetic', label: 'Cosmetic', icon: 'sparkles' },
      { id: 'ai', label: 'AI Assistant', icon: 'brain' },
      { id: 'services', label: 'Services', icon: 'scissors' },
      { id: 'history', label: 'History', icon: 'doc.text' },
    ],
  },
  dentistry: {
    navigation: 'query',
    queryParam: 'tab',
    defaultItem: 'dashboard',
    items: [
      { id: 'dashboard', label: 'Dashboard', icon: 'chart.bar' },
      { id: 'patients', label: 'Patients', icon: 'person.2' },
      { id: 'appointments', label: 'Appointments', icon: 'calendar' },
      { id: 'examinations', label: 'Examinations', icon: 'eye' },
      { id: 'diagnoses', label: 'Diagnoses', icon: 'stethoscope' },
      { id: 'visits', label: 'Visit Protocols', icon: 'doc.text' },
      { id: 'photos', label: 'Photo Archive', icon: 'camera' },
      { id: 'templates', label: 'Templates', icon: 'doc' },
      { id: 'reports', label: 'Reports', icon: 'chart.bar' },
      { id: 'dental-chart', label: 'Dental Chart', icon: 'smile' },
      { id: 'treatment-plans', label: 'Treatment Plans', icon: 'list' },
      { id: 'prosthetics', label: 'Prosthetics', icon: 'smile' },
      { id: 'ai-assistant', label: 'AI Assistant', icon: 'brain' },
    ],
  },
};

const stable = 'stable';
const internal = 'internal';

function nav(meta) {
  return meta || false;
}

function layout(meta = {}) {
  return meta;
}

export const ROUTE_REGISTRY = [
  {
    id: 'landing',
    path: '/',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'landing',
    auth: 'public',
    roles: [],
    entry: 'menu',
    nav: false,
    title: 'Clinic Management System',
    owner: 'marketing.landing',
    component: 'Landing',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Clinic Management System' }),
  },
  {
    id: 'login',
    path: '/login',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'landing',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Login',
    owner: 'iam.auth',
    component: 'LoginFormStyled',
    legacyRedirectFrom: ['/old-login'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Login' }),
  },
  {
    id: 'change-password-required',
    path: '/change-password-required',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'authenticated',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Change Password Required',
    owner: 'iam.auth',
    component: 'ChangePasswordRequired',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Change Password Required' }),
  },
  {
    id: 'health',
    path: '/health',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'System Health',
    owner: 'platform.ops',
    component: 'Health',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'System Health' }),
  },
  {
    id: 'queue-join',
    path: '/queue/join',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Join Queue',
    owner: 'queue.public',
    component: 'QueueJoin',
    legacyRedirectFrom: ['/pwa/queue'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Join Queue' }),
  },
  {
    id: 'queue-join-token',
    path: '/queue/join/:token',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Join Queue',
    owner: 'queue.public',
    component: 'QueueJoin',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Join Queue' }),
  },
  {
    id: 'payment-success',
    path: '/payment/success',
    group: 'public',
    surface: 'callback',
    lifecycle: stable,
    shell: 'callback',
    auth: 'public',
    roles: [],
    entry: 'callback',
    nav: false,
    title: 'Payment Success',
    owner: 'billing.payments',
    component: 'PaymentSuccess',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Payment Success' }),
  },
  {
    id: 'payment-cancel',
    path: '/payment/cancel',
    group: 'public',
    surface: 'callback',
    lifecycle: stable,
    shell: 'callback',
    auth: 'public',
    roles: [],
    entry: 'callback',
    nav: false,
    title: 'Payment Cancelled',
    owner: 'billing.payments',
    component: 'PaymentCancel',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Payment Cancelled' }),
  },
  {
    id: 'queue-board',
    path: '/queue-board',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Queue Board',
    owner: 'queue.display',
    component: 'DisplayBoardUnified',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, fullscreen: true, pageTitle: 'Queue Board' }),
  },
  {
    id: 'display-board',
    path: '/display-board',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Display Board',
    owner: 'queue.display',
    component: 'DisplayBoardUnified',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, fullscreen: true, pageTitle: 'Display Board' }),
  },
  {
    id: 'display-board-role',
    path: '/display-board/:role',
    group: 'public',
    surface: 'screen',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Display Board',
    owner: 'queue.display',
    component: 'DisplayBoardUnified',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, fullscreen: true, pageTitle: 'Display Board' }),
  },
  {
    id: 'setup',
    path: '/setup',
    group: 'onboarding',
    surface: 'screen',
    lifecycle: stable,
    shell: 'setup',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Clinic Setup',
    owner: 'platform.setup',
    component: 'Setup',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Clinic Setup' }),
  },
  {
    id: 'admin-dashboard',
    path: '/admin',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    homeForRoles: ['admin'],
    entry: 'menu',
    nav: nav({ label: 'Dashboard', icon: 'chart.bar', section: 'Обзор', order: 10, menu: true, sidebar: true }),
    title: 'Admin Dashboard',
    owner: 'admin.operations',
    component: 'AnalyticsPage',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-dashboard', pageTitle: 'Admin Dashboard' }),
  },
  {
    id: 'admin-analytics',
    path: '/admin/analytics',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Аналитика', icon: 'chart.bar', section: 'Обзор', order: 20, sidebar: true }),
    title: 'Admin Analytics',
    owner: 'admin.analytics',
    component: 'AdminPanel',
    legacyRedirectFrom: ['/analytics'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-analytics', pageTitle: 'Admin Analytics' }),
  },
  {
    id: 'admin-webhooks',
    path: '/admin/webhooks',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Webhook\'и', icon: 'globe', section: 'Обзор', order: 30, sidebar: true }),
    title: 'Admin Webhooks',
    owner: 'admin.integrations',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-webhooks', pageTitle: 'Admin Webhooks' }),
  },
  {
    id: 'admin-reports',
    path: '/admin/reports',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Отчеты', icon: 'file-text', section: 'Обзор', order: 40, sidebar: true }),
    title: 'Admin Reports',
    owner: 'admin.reports',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-reports', pageTitle: 'Admin Reports' }),
  },
  {
    id: 'admin-system',
    path: '/admin/system',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Система', icon: 'gear', section: 'Обзор', order: 50, sidebar: true }),
    title: 'Admin System',
    owner: 'admin.system',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-system', pageTitle: 'Admin System' }),
  },
  {
    id: 'admin-cloud-printing',
    path: '/admin/cloud-printing',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Облачная печать', icon: 'printer', section: 'Обзор', order: 60, sidebar: true }),
    title: 'Admin Cloud Printing',
    owner: 'admin.operations',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-cloud-printing', pageTitle: 'Admin Cloud Printing' }),
  },
  {
    id: 'admin-medical-equipment',
    path: '/admin/medical-equipment',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Медицинское оборудование', icon: 'stethoscope', section: 'Обзор', order: 70, sidebar: true }),
    title: 'Admin Medical Equipment',
    owner: 'admin.operations',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-medical-equipment', pageTitle: 'Admin Medical Equipment' }),
  },
  {
    id: 'admin-graphql-explorer',
    path: '/admin/graphql-explorer',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'GraphQL API', icon: 'database', section: 'Обзор', order: 80, sidebar: true }),
    title: 'Admin GraphQL Explorer',
    owner: 'admin.integrations',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-graphql-explorer', pageTitle: 'Admin GraphQL Explorer' }),
  },
  {
    id: 'admin-users',
    path: '/admin/users',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Пользователи', icon: 'users', section: 'Управление', order: 10, sidebar: true }),
    title: 'Admin Users',
    owner: 'admin.users',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-users', pageTitle: 'Admin Users' }),
  },
  {
    id: 'admin-doctors',
    path: '/admin/doctors',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Врачи', icon: 'user-plus', section: 'Управление', order: 20, sidebar: true }),
    title: 'Admin Doctors',
    owner: 'admin.users',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-doctors', pageTitle: 'Admin Doctors' }),
  },
  {
    id: 'admin-services',
    path: '/admin/services',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Услуги', icon: 'list', section: 'Управление', order: 30, sidebar: true }),
    title: 'Admin Services',
    owner: 'admin.catalog',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-services', pageTitle: 'Admin Services' }),
  },
  {
    id: 'admin-queue-cabinet-management',
    path: '/admin/queue-cabinet-management',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Кабинеты очередей', icon: 'building', section: 'Управление', order: 40, sidebar: true }),
    title: 'Admin Queue Cabinets',
    owner: 'admin.queue',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-queue-cabinet-management', pageTitle: 'Admin Queue Cabinets' }),
  },
  {
    id: 'admin-patients',
    path: '/admin/patients',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Пациенты', icon: 'users', section: 'Управление', order: 50, sidebar: true }),
    title: 'Admin Patients',
    owner: 'admin.patients',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-patients', pageTitle: 'Admin Patients' }),
  },
  {
    id: 'admin-appointments',
    path: '/admin/appointments',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Записи', icon: 'calendar', section: 'Управление', order: 60, sidebar: true }),
    title: 'Admin Appointments',
    owner: 'admin.scheduling',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-appointments', pageTitle: 'Admin Appointments' }),
  },
  {
    id: 'admin-all-free',
    path: '/admin/all-free',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Заявки All Free', icon: 'exclamationmark.triangle', section: 'Управление', order: 70, sidebar: true }),
    title: 'Admin All Free',
    owner: 'admin.operations',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-all-free', pageTitle: 'Admin All Free' }),
  },
  {
    id: 'admin-benefit-settings',
    path: '/admin/benefit-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false,
    title: 'Admin Benefit Settings',
    owner: 'admin.billing',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', pageTitle: 'Admin Benefit Settings' }),
  },
  {
    id: 'admin-wizard-settings',
    path: '/admin/wizard-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false,
    title: 'Admin Wizard Settings',
    owner: 'admin.settings',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', pageTitle: 'Admin Wizard Settings' }),
  },
  {
    id: 'admin-payment-providers',
    path: '/admin/payment-providers',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false,
    title: 'Admin Payment Providers',
    owner: 'admin.billing',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', pageTitle: 'Admin Payment Providers' }),
  },
  {
    id: 'admin-clinic-management',
    path: '/admin/clinic-management',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Управление клиникой', icon: 'building', section: 'Система', order: 10, sidebar: true }),
    title: 'Admin Clinic Management',
    owner: 'admin.operations',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-clinic-management', pageTitle: 'Admin Clinic Management' }),
  },
  {
    id: 'admin-clinic-settings',
    path: '/admin/clinic-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false,
    title: 'Admin Clinic Settings',
    owner: 'admin.settings',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', pageTitle: 'Admin Clinic Settings' }),
  },
  {
    id: 'admin-queue-settings',
    path: '/admin/queue-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false,
    title: 'Admin Queue Settings',
    owner: 'admin.queue',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', pageTitle: 'Admin Queue Settings' }),
  },
  {
    id: 'admin-ai-settings',
    path: '/admin/ai-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'AI Инструменты', icon: 'brain', section: 'Система', order: 20, sidebar: true }),
    title: 'Admin AI Settings',
    owner: 'admin.ai',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-ai-settings', pageTitle: 'Admin AI Settings' }),
  },
  {
    id: 'admin-telegram-settings',
    path: '/admin/telegram-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false,
    title: 'Admin Telegram Settings',
    owner: 'admin.integrations',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', pageTitle: 'Admin Telegram Settings' }),
  },
  {
    id: 'admin-display-settings',
    path: '/admin/display-settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false,
    title: 'Admin Display Settings',
    owner: 'admin.queue',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', pageTitle: 'Admin Display Settings' }),
  },
  {
    id: 'admin-telegram-integration',
    path: '/admin/integrations/telegram',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Telegram', icon: 'paperplane', section: 'Система', order: 30, sidebar: true }),
    title: 'Admin Telegram Integration',
    owner: 'admin.integrations',
    component: 'TelegramManager',
    legacyRedirectFrom: ['/telegram-integration'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-telegram-integration', pageTitle: 'Admin Telegram Integration' }),
  },
  {
    id: 'admin-notifications',
    path: '/admin/notifications',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Уведомления', icon: 'bell', section: 'Система', order: 40, sidebar: true }),
    title: 'Admin Notifications',
    owner: 'admin.notifications',
    component: 'EmailSMSManager',
    legacyRedirectFrom: ['/notifications'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-notifications', pageTitle: 'Admin Notifications' }),
  },
  {
    id: 'admin-phone-verification',
    path: '/admin/phone-verification',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Верификация телефонов', icon: 'phone', section: 'Система', order: 50, sidebar: true }),
    title: 'Admin Phone Verification',
    owner: 'admin.integrations',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-phone-verification', pageTitle: 'Admin Phone Verification' }),
  },
  {
    id: 'admin-activation',
    path: '/admin/activation',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Активация', icon: 'key', section: 'Система', order: 60, sidebar: true }),
    title: 'Admin Activation',
    owner: 'admin.licensing',
    component: 'AdminPanel',
    legacyRedirectFrom: ['/activation'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-activation', pageTitle: 'Admin Activation' }),
  },
  {
    id: 'admin-finance',
    path: '/admin/finance',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Финансы', icon: 'dollarsign.circle', section: 'Система', order: 70, sidebar: true }),
    title: 'Admin Finance',
    owner: 'admin.billing',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-finance', pageTitle: 'Admin Finance' }),
  },
  {
    id: 'admin-settings',
    path: '/admin/settings',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Настройки', icon: 'gear', section: 'Система', order: 80, sidebar: true, menu: true }),
    title: 'Admin Settings',
    owner: 'admin.settings',
    component: 'Settings',
    legacyRedirectFrom: ['/settings'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-settings', pageTitle: 'Admin Settings' }),
  },
  {
    id: 'admin-security',
    path: '/admin/security',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Безопасность', icon: 'lock', section: 'Система', order: 90, sidebar: true }),
    title: 'Admin Security',
    owner: 'admin.security',
    component: 'AdminPanel',
    legacyRedirectFrom: [],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-security', pageTitle: 'Admin Security' }),
  },
  {
    id: 'admin-audit',
    path: '/admin/audit',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'menu',
    nav: nav({ label: 'Аудит', icon: 'list', section: 'Система', order: 100, sidebar: true }),
    title: 'Admin Audit',
    owner: 'admin.audit',
    component: 'Audit',
    legacyRedirectFrom: ['/audit'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-audit', pageTitle: 'Admin Audit' }),
  },
  {
    id: 'admin-advanced-users',
    path: '/admin/advanced-users',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: nav({ label: 'Расширенные пользователи', icon: 'users', section: 'Система', order: 110, sidebar: true }),
    title: 'Admin Advanced Users',
    owner: 'admin.users',
    component: 'UserManagement',
    legacyRedirectFrom: ['/advanced-users'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-advanced-users', pageTitle: 'Admin Advanced Users' }),
  },
  {
    id: 'admin-file-management',
    path: '/admin/file-management',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor'],
    entry: 'direct',
    nav: nav({ label: 'Файлы', icon: 'doc.text', section: 'Система', order: 120, sidebar: true }),
    title: 'File Management',
    owner: 'admin.files',
    component: 'FileManager',
    legacyRedirectFrom: ['/file-management'],
    layout: layout({ sidebarPreset: 'admin', activeSidebarItem: 'admin-file-management', pageTitle: 'File Management' }),
  },
  {
    id: 'admin-user-select',
    path: '/admin/user-select',
    group: 'admin',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'direct',
    nav: false,
    title: 'Admin User Switcher',
    owner: 'admin.users',
    component: 'UserSelect',
    legacyRedirectFrom: ['/user-select'],
    layout: layout({ sidebarPreset: 'admin', pageTitle: 'Admin User Switcher' }),
  },
  {
    id: 'registrar-home',
    path: '/registrar',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar'],
    homeForRoles: ['registrar', 'receptionist'],
    entry: 'menu',
    nav: nav({ label: 'Регистратура', icon: 'users', section: 'Clinical', order: 10, menu: true }),
    title: 'Registrar Panel',
    owner: 'clinical.registrar',
    component: 'RegistrarPanel',
    legacyRedirectFrom: ['/registrar-panel'],
    layout: layout({ hideSidebar: true, sidebarPreset: 'registrar', pageTitle: 'Registrar Panel' }),
  },
  {
    id: 'doctor-home',
    path: '/doctor',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor'],
    homeForRoles: ['doctor', 'nurse'],
    entry: 'menu',
    nav: nav({ label: 'Врач', icon: 'stethoscope', section: 'Clinical', order: 20, menu: true }),
    title: 'Doctor Panel',
    owner: 'clinical.doctor',
    component: 'DoctorPanel',
    legacyRedirectFrom: ['/doctor-panel'],
    layout: layout({ hideSidebar: true, sidebarPreset: 'doctor', pageTitle: 'Doctor Panel' }),
  },
  {
    id: 'cashier-home',
    path: '/cashier',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Cashier'],
    homeForRoles: ['cashier'],
    entry: 'menu',
    nav: nav({ label: 'Касса', icon: 'creditcard', section: 'Clinical', order: 30, menu: true }),
    title: 'Cashier Panel',
    owner: 'clinical.cashier',
    component: 'CashierPanel',
    legacyRedirectFrom: ['/cashier-panel'],
    layout: layout({ hideSidebar: true, sidebarPreset: 'cashier', pageTitle: 'Cashier Panel' }),
  },
  {
    id: 'lab-home',
    path: '/lab',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Lab'],
    homeForRoles: ['lab'],
    entry: 'menu',
    nav: nav({ label: 'Лаборатория', icon: 'testtube.2', section: 'Clinical', order: 40, menu: true }),
    title: 'Lab Panel',
    owner: 'clinical.lab',
    component: 'LabPanel',
    legacyRedirectFrom: ['/lab-panel'],
    layout: layout({ sidebarPreset: 'lab', pageTitle: 'Lab Panel' }),
  },
  {
    id: 'patient-home',
    path: '/patient',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar', 'Doctor'],
    homeForRoles: ['patient'],
    entry: 'direct',
    nav: false,
    title: 'Patient Panel',
    owner: 'clinical.patient',
    component: 'PatientPanel',
    legacyRedirectFrom: ['/patient-panel'],
    layout: layout({ hideSidebar: true, sidebarPreset: 'patient', pageTitle: 'Patient Panel' }),
  },
  {
    id: 'doctor-cardiology',
    path: '/doctor/cardiology',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'cardio'],
    homeForRoles: ['cardio'],
    homeForUsernames: ['cardio@example.com'],
    entry: 'menu',
    nav: nav({ label: 'Кардиология', icon: 'heart', section: 'Clinical', order: 50, menu: true }),
    title: 'Cardiology Panel',
    owner: 'clinical.cardiology',
    component: 'CardiologistPanelUnified',
    legacyRedirectFrom: ['/cardiologist'],
    layout: layout({ hideSidebar: true, fullscreen: true, sidebarPreset: 'cardiology', pageTitle: 'Cardiology Panel' }),
  },
  {
    id: 'doctor-dermatology',
    path: '/doctor/dermatology',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'derma'],
    homeForRoles: ['derma'],
    homeForUsernames: ['derma@example.com'],
    entry: 'menu',
    nav: nav({ label: 'Дерматология', icon: 'face.smiling', section: 'Clinical', order: 60, menu: true }),
    title: 'Dermatology Panel',
    owner: 'clinical.dermatology',
    component: 'DermatologistPanelUnified',
    legacyRedirectFrom: ['/dermatologist'],
    layout: layout({ hideSidebar: true, fullscreen: true, sidebarPreset: 'dermatology', pageTitle: 'Dermatology Panel' }),
  },
  {
    id: 'doctor-dentistry',
    path: '/doctor/dentistry',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'dentist'],
    homeForRoles: ['dentist'],
    homeForUsernames: ['dentist@example.com'],
    entry: 'menu',
    nav: nav({ label: 'Стоматология', icon: 'smile', section: 'Clinical', order: 70, menu: true }),
    title: 'Dentistry Panel',
    owner: 'clinical.dentistry',
    component: 'DentistPanelUnified',
    legacyRedirectFrom: ['/dentist'],
    layout: layout({ hideSidebar: true, fullscreen: true, sidebarPreset: 'dentistry', pageTitle: 'Dentistry Panel' }),
  },
  {
    id: 'clinical-scheduler',
    path: '/clinical/scheduler',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'Registrar'],
    entry: 'menu',
    nav: nav({ label: 'Расписание', icon: 'calendar', section: 'Clinical', order: 80, menu: true }),
    title: 'Clinical Scheduler',
    owner: 'clinical.scheduling',
    component: 'Scheduler',
    legacyRedirectFrom: ['/scheduler'],
    layout: layout({ sidebarPreset: 'default', activeSidebarItem: 'clinical-scheduler', pageTitle: 'Clinical Scheduler' }),
  },
  {
    id: 'clinical-appointments',
    path: '/clinical/appointments',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar'],
    entry: 'menu',
    nav: nav({ label: 'Записи', icon: 'calendar', section: 'Clinical', order: 90, menu: true }),
    title: 'Clinical Appointments',
    owner: 'clinical.scheduling',
    component: 'Appointments',
    legacyRedirectFrom: ['/appointments'],
    layout: layout({ sidebarPreset: 'default', activeSidebarItem: 'clinical-appointments', pageTitle: 'Clinical Appointments' }),
  },
  {
    id: 'clinical-search',
    path: '/clinical/search',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'Registrar', 'cardio', 'derma', 'dentist'],
    entry: 'menu',
    nav: nav({ label: 'Поиск', icon: 'magnifyingglass', section: 'Clinical', order: 100, menu: true }),
    title: 'Clinical Search',
    owner: 'clinical.search',
    component: 'Search',
    legacyRedirectFrom: ['/search'],
    layout: layout({ sidebarPreset: 'default', activeSidebarItem: 'clinical-search', pageTitle: 'Clinical Search' }),
  },
  {
    id: 'clinical-profile',
    path: '/clinical/profile',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'authenticated',
    roles: [],
    entry: 'contextual',
    nav: false,
    title: 'User Profile',
    owner: 'iam.profile',
    component: 'UserProfile',
    legacyRedirectFrom: ['/profile'],
    layout: layout({ hideSidebar: true, pageTitle: 'User Profile' }),
  },
  {
    id: 'clinical-security',
    path: '/clinical/security',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'authenticated',
    roles: [],
    entry: 'contextual',
    nav: false,
    title: 'Security Settings',
    owner: 'iam.security',
    component: 'SecurityPage',
    legacyRedirectFrom: ['/security'],
    layout: layout({ sidebarPreset: 'default', pageTitle: 'Security Settings' }),
  },
  {
    id: 'clinical-two-factor',
    path: '/clinical/security/two-factor',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor'],
    entry: 'direct',
    nav: false,
    title: 'Two-Factor Settings',
    owner: 'iam.security',
    component: 'TwoFactorManager',
    legacyRedirectFrom: ['/security-settings'],
    layout: layout({ sidebarPreset: 'default', pageTitle: 'Two-Factor Settings' }),
  },
  {
    id: 'clinical-visit-details',
    path: '/clinical/visits/:id',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Doctor', 'Registrar', 'cardio', 'derma', 'dentist'],
    entry: 'contextual',
    nav: false,
    title: 'Visit Details',
    owner: 'clinical.emr',
    component: 'VisitDetails',
    legacyRedirectFrom: ['/visits/:id'],
    layout: layout({ sidebarPreset: 'default', pageTitle: 'Visit Details' }),
  },
  {
    id: 'clinical-pickup',
    path: '/clinical/pickup/:patientId',
    group: 'clinical',
    surface: 'screen',
    lifecycle: stable,
    shell: 'app-shell',
    auth: 'role-scoped',
    roles: ['Admin', 'Registrar', 'Cashier', 'Lab', 'Doctor', 'cardio', 'derma', 'dentist'],
    entry: 'contextual',
    nav: false,
    title: 'Patient Pickup',
    owner: 'clinical.patient',
    component: 'PatientPickupView',
    legacyRedirectFrom: ['/pickup/:patientId'],
    layout: layout({ sidebarPreset: 'default', pageTitle: 'Patient Pickup' }),
  },
  {
    id: 'internal-demo-medilab',
    path: '/internal-demo/medilab',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'MediLab Demo',
    owner: 'internal.demo',
    component: 'MediLabDemo',
    legacyRedirectFrom: [
      '/medilab-demo',
      '/medilab-demo/dashboard',
      '/medilab-demo/patients',
      '/medilab-demo/appointments',
      '/medilab-demo/staff-schedule',
    ],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'MediLab Demo' }),
  },
  {
    id: 'internal-demo-macos',
    path: '/internal-demo/macos',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'macOS Demo',
    owner: 'internal.demo',
    component: 'MacOSDemoPage',
    legacyRedirectFrom: ['/macos-demo'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'macOS Demo' }),
  },
  {
    id: 'internal-demo-integration',
    path: '/internal-demo/integration',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'Integration Demo',
    owner: 'internal.demo',
    component: 'IntegrationDemo',
    legacyRedirectFrom: ['/integration-demo'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Integration Demo' }),
  },
  {
    id: 'internal-demo-payment-test',
    path: '/internal-demo/payment-test',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'Payment Test',
    owner: 'internal.demo',
    component: 'PaymentTest',
    legacyRedirectFrom: ['/payment/test'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Payment Test' }),
  },
  {
    id: 'internal-demo-css-test',
    path: '/internal-demo/css-test',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'CSS Test',
    owner: 'internal.demo',
    component: 'CSSTestPage',
    legacyRedirectFrom: ['/css-test'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'CSS Test' }),
  },
  {
    id: 'internal-demo-buttons',
    path: '/internal-demo/buttons',
    group: 'internal-demo',
    surface: 'utility',
    lifecycle: internal,
    shell: 'fullscreen',
    auth: 'role-scoped',
    roles: ['Admin'],
    entry: 'internal',
    nav: false,
    title: 'Buttons Showcase',
    owner: 'internal.demo',
    component: 'ButtonShowcase',
    legacyRedirectFrom: ['/buttons'],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Buttons Showcase' }),
  },
  {
    id: 'unauthorized',
    path: '/unauthorized',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Unauthorized',
    owner: 'platform.routing',
    component: 'UnauthorizedPage',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Unauthorized' }),
  },
  {
    id: 'forbidden',
    path: '/forbidden',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Forbidden',
    owner: 'platform.routing',
    component: 'ForbiddenPage',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Forbidden' }),
  },
  {
    id: 'not-found',
    path: '/not-found',
    group: 'public',
    surface: 'utility',
    lifecycle: stable,
    shell: 'fullscreen',
    auth: 'public',
    roles: [],
    entry: 'direct',
    nav: false,
    title: 'Not Found',
    owner: 'platform.routing',
    component: 'NotFoundPage',
    legacyRedirectFrom: [],
    layout: layout({ hideHeader: true, hideSidebar: true, pageTitle: 'Not Found' }),
  },
];

export function getCanonicalRoutes() {
  return ROUTE_REGISTRY;
}
