"""add payment fields to appointments

Revision ID: 20250129_0001
Revises: 20250829_0002
Create Date: 2025-01-29 12:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20250129_0001"
down_revision = "add_emr_prescription"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Добавляем поля для интеграции с платежами в таблицу appointments
    op.add_column(
        "appointments", sa.Column("payment_amount", sa.Float(), nullable=True)
    )
    op.add_column(
        "appointments",
        sa.Column(
            "payment_currency", sa.String(length=3), nullable=True, default="UZS"
        ),
    )
    op.add_column(
        "appointments",
        sa.Column("payment_provider", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "appointments",
        sa.Column("payment_transaction_id", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "appointments", sa.Column("payment_webhook_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "appointments",
        sa.Column("payment_processed_at", sa.DateTime(timezone=True), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Удаляем поля для интеграции с платежами
    op.drop_column("appointments", "payment_processed_at")
    op.drop_column("appointments", "payment_webhook_id")
    op.drop_column("appointments", "payment_transaction_id")
    op.drop_column("appointments", "payment_provider")
    op.drop_column("appointments", "payment_currency")
    op.drop_column("appointments", "payment_amount")

    # ### end Alembic commands ###
