"""add notification tables

Revision ID: 20250129_0003
Revises: 20250129_0002
Create Date: 2025-01-29 21:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20250129_0003'
down_revision = '20250129_0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Создаем таблицу шаблонов уведомлений
    op.create_table(
        'notification_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('channel', sa.String(length=20), nullable=False),
        sa.Column('subject', sa.String(length=200), nullable=True),
        sa.Column('template', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_index(
        op.f('ix_notification_templates_id'),
        'notification_templates',
        ['id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_notification_templates_name'),
        'notification_templates',
        ['name'],
        unique=True,
    )

    # Создаем таблицу истории уведомлений
    op.create_table(
        'notification_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recipient_type', sa.String(length=20), nullable=False),
        sa.Column('recipient_id', sa.Integer(), nullable=True),
        sa.Column('recipient_contact', sa.String(length=255), nullable=False),
        sa.Column('notification_type', sa.String(length=50), nullable=False),
        sa.Column('channel', sa.String(length=20), nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=True),
        sa.Column('subject', sa.String(length=200), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, default='pending'),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('related_entity_type', sa.String(length=50), nullable=True),
        sa.Column('related_entity_id', sa.Integer(), nullable=True),
        sa.Column('notification_metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('delivered_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_notification_history_id'), 'notification_history', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_notification_history_recipient_id'),
        'notification_history',
        ['recipient_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_notification_history_notification_type'),
        'notification_history',
        ['notification_type'],
        unique=False,
    )

    # Создаем таблицу настроек уведомлений
    op.create_table(
        'notification_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('user_type', sa.String(length=20), nullable=False),
        sa.Column('email_enabled', sa.Boolean(), nullable=False, default=True),
        sa.Column('sms_enabled', sa.Boolean(), nullable=False, default=True),
        sa.Column('telegram_enabled', sa.Boolean(), nullable=False, default=False),
        sa.Column('appointment_reminders', sa.Boolean(), nullable=False, default=True),
        sa.Column('payment_notifications', sa.Boolean(), nullable=False, default=True),
        sa.Column('queue_updates', sa.Boolean(), nullable=False, default=True),
        sa.Column('system_alerts', sa.Boolean(), nullable=False, default=False),
        sa.Column('reminder_hours_before', sa.Integer(), nullable=False, default=24),
        sa.Column('notification_email', sa.String(length=255), nullable=True),
        sa.Column('notification_phone', sa.String(length=20), nullable=True),
        sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_notification_settings_id'),
        'notification_settings',
        ['id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_notification_settings_user_id'),
        'notification_settings',
        ['user_id'],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_notification_settings_user_id'), table_name='notification_settings'
    )
    op.drop_index(
        op.f('ix_notification_settings_id'), table_name='notification_settings'
    )
    op.drop_table('notification_settings')

    op.drop_index(
        op.f('ix_notification_history_notification_type'),
        table_name='notification_history',
    )
    op.drop_index(
        op.f('ix_notification_history_recipient_id'), table_name='notification_history'
    )
    op.drop_index(op.f('ix_notification_history_id'), table_name='notification_history')
    op.drop_table('notification_history')

    op.drop_index(
        op.f('ix_notification_templates_name'), table_name='notification_templates'
    )
    op.drop_index(
        op.f('ix_notification_templates_id'), table_name='notification_templates'
    )
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
