"""Add file system models

Revision ID: abc9d4aacc0c
Revises: 20250129_0003
Create Date: 2025-09-11 08:54:10.563451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'abc9d4aacc0c'
down_revision = '20250129_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_file_size', sa.Integer(), nullable=True),
    sa.Column('allowed_types', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_file_storage_id'), 'file_storage', ['id'], unique=False)
    op.create_table('file_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['file_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_folders_id'), 'file_folders', ['id'], unique=False)
    op.create_index(op.f('ix_file_folders_owner_id'), 'file_folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_file_folders_parent_id'), 'file_folders', ['parent_id'], unique=False)
    op.create_table('file_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_storage_bytes', sa.Integer(), nullable=False),
    sa.Column('used_storage_bytes', sa.Integer(), nullable=False),
    sa.Column('max_files', sa.Integer(), nullable=True),
    sa.Column('used_files', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_quotas_id'), 'file_quotas', ['id'], unique=False)
    op.create_index(op.f('ix_file_quotas_user_id'), 'file_quotas', ['user_id'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('DOCUMENT', 'IMAGE', 'VIDEO', 'AUDIO', 'ARCHIVE', 'MEDICAL_RECORD', 'LAB_RESULT', 'XRAY', 'PRESCRIPTION', 'REPORT', 'BACKUP', 'OTHER', name='filetype'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'READY', 'ERROR', 'DELETED', 'ARCHIVED', name='filestatus'), nullable=False),
    sa.Column('permission', sa.Enum('PUBLIC', 'PRIVATE', 'RESTRICTED', 'CONFIDENTIAL', name='filepermission'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('file_metadata', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('emr_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['emr_id'], ['emr.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_appointment_id'), 'files', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_files_emr_id'), 'files', ['emr_id'], unique=False)
    op.create_index(op.f('ix_files_file_hash'), 'files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_files_file_type'), 'files', ['file_type'], unique=False)
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_owner_id'), 'files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_files_patient_id'), 'files', ['patient_id'], unique=False)
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_table('file_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_access_logs_file_id'), 'file_access_logs', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_access_logs_id'), 'file_access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_file_access_logs_user_id'), 'file_access_logs', ['user_id'], unique=False)
    op.create_table('file_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=True),
    sa.Column('shared_with_email', sa.String(length=255), nullable=True),
    sa.Column('permission', sa.Enum('PUBLIC', 'PRIVATE', 'RESTRICTED', 'CONFIDENTIAL', name='filepermission'), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_shares_access_token'), 'file_shares', ['access_token'], unique=True)
    op.create_index(op.f('ix_file_shares_file_id'), 'file_shares', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_shares_id'), 'file_shares', ['id'], unique=False)
    op.create_index(op.f('ix_file_shares_shared_with_email'), 'file_shares', ['shared_with_email'], unique=False)
    op.create_index(op.f('ix_file_shares_shared_with_user_id'), 'file_shares', ['shared_with_user_id'], unique=False)
    op.create_table('file_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_versions_id'), 'file_versions', ['id'], unique=False)
    op.drop_index('ix_visit_billings_status', table_name='visit_billings')
    op.drop_index('ux_visit_billings_visit', table_name='visit_billings')
    op.drop_table('visit_billings')
    op.drop_index('ix_printer_configs_id', table_name='printer_configs')
    op.drop_table('printer_configs')
    op.drop_index('ix_display_announcements_id', table_name='display_announcements')
    op.drop_table('display_announcements')
    op.drop_table('doctors_new')
    op.drop_index('ix_audit_action', table_name='audit')
    op.drop_index('ix_audit_created_at', table_name='audit')
    op.drop_index('ix_audit_entity', table_name='audit')
    op.drop_index('ix_audit_entity_id', table_name='audit')
    op.drop_index('ix_audit_user_id', table_name='audit')
    op.drop_table('audit')
    op.drop_index('ix_display_videos_id', table_name='display_videos')
    op.drop_table('display_videos')
    op.drop_index('ix_ai_prompt_templates_id', table_name='ai_prompt_templates')
    op.drop_index('ix_ai_prompt_templates_specialty', table_name='ai_prompt_templates')
    op.drop_index('ix_ai_prompt_templates_task_type', table_name='ai_prompt_templates')
    op.drop_table('ai_prompt_templates')
    op.drop_index('ix_telegram_users_chat_id', table_name='telegram_users')
    op.drop_index('ix_telegram_users_id', table_name='telegram_users')
    op.drop_table('telegram_users')
    op.drop_index('ix_ai_providers_id', table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_index('ix_display_boards_id', table_name='display_boards')
    op.drop_table('display_boards')
    op.drop_index('ix_telegram_configs_id', table_name='telegram_configs')
    op.drop_table('telegram_configs')
    op.drop_index('ix_print_jobs_created_at', table_name='print_jobs')
    op.drop_index('ix_print_jobs_id', table_name='print_jobs')
    op.drop_table('print_jobs')
    op.drop_index('ix_ai_usage_logs_created_at', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_id', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_request_hash', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_task_type', table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index('ix_telegram_messages_chat_id', table_name='telegram_messages')
    op.drop_index('ix_telegram_messages_created_at', table_name='telegram_messages')
    op.drop_index('ix_telegram_messages_id', table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_index('ix_print_templates_id', table_name='print_templates')
    op.drop_table('print_templates')
    op.drop_index('ix_display_themes_id', table_name='display_themes')
    op.drop_table('display_themes')
    op.drop_index('ix_display_banners_id', table_name='display_banners')
    op.drop_table('display_banners')
    op.drop_index('ix_telegram_templates_id', table_name='telegram_templates')
    op.drop_index('ix_telegram_templates_template_key', table_name='telegram_templates')
    op.drop_table('telegram_templates')
    op.alter_column('activations', 'status',
               existing_type=sa.VARCHAR(length=7),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_activations_key', table_name='activations')
    op.drop_index('idx_activations_machine_hash', table_name='activations')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('audit_logs', 'payload',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_foreign_key(None, 'doctors', 'branches', ['branch_id'], ['id'])
    op.alter_column('emr', 'vital_signs',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'lab_results',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'imaging_results',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'medications',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'allergies',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'family_history',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'social_history',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'ai_suggestions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'ai_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('lab_orders', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lab_orders', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_lab_orders_patient', table_name='lab_orders')
    op.drop_index('ix_lab_orders_status', table_name='lab_orders')
    op.drop_index('ix_lab_orders_visit', table_name='lab_orders')
    op.create_index(op.f('ix_lab_orders_patient_id'), 'lab_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_visit_id'), 'lab_orders', ['visit_id'], unique=False)
    op.alter_column('lab_results', 'abnormal',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lab_results', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_lab_results_code', table_name='lab_results')
    op.drop_index('ix_lab_results_order', table_name='lab_results')
    op.create_index(op.f('ix_lab_results_order_id'), 'lab_results', ['order_id'], unique=False)
    op.create_index(op.f('ix_lab_results_test_code'), 'lab_results', ['test_code'], unique=False)
    op.add_column('notification_history', sa.Column('notification_metadata', sa.JSON(), nullable=True))
    op.drop_column('notification_history', 'metadata')
    op.drop_index('ix_online_days_date', table_name='online_days')
    op.drop_index('ix_online_days_dep', table_name='online_days')
    op.drop_index('uq_online_day_dep_date__uniq_idx', table_name='online_days')
    op.create_index(op.f('ix_online_days_date_str'), 'online_days', ['date_str'], unique=False)
    op.create_index(op.f('ix_online_days_department'), 'online_days', ['department'], unique=False)
    op.create_index(op.f('ix_online_days_id'), 'online_days', ['id'], unique=False)
    op.create_unique_constraint('uq_online_day_dep_date', 'online_days', ['department', 'date_str'])
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('patients', 'first_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('patients', 'middle_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('patients', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_patients_doc', table_name='patients')
    op.drop_index('ix_patients_phone', table_name='patients')
    op.create_index(op.f('ix_patients_first_name'), 'patients', ['first_name'], unique=False)
    op.create_index(op.f('ix_patients_last_name'), 'patients', ['last_name'], unique=False)
    op.alter_column('payment_providers', 'commission_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_providers', 'min_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_providers', 'max_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'payment_providers', ['name'])
    op.alter_column('payment_transactions', 'commission',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'visit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'note',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_payments_visit_id', table_name='payments')
    op.drop_index('ix_payments_cashier', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_visit', table_name='payments')
    op.drop_index('ux_payments_receipt', table_name='payments')
    op.create_index(op.f('ix_payments_visit_id'), 'payments', ['visit_id'], unique=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'cashier_id')
    op.alter_column('queue_tickets', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_queue_date', table_name='queue_tickets')
    op.drop_index('ix_queue_dep', table_name='queue_tickets')
    op.drop_index('ix_queue_status', table_name='queue_tickets')
    op.drop_index('ix_queue_ticket', table_name='queue_tickets')
    op.drop_index('uq_queue_dep_date_ticket__uniq_idx', table_name='queue_tickets')
    op.create_index(op.f('ix_queue_tickets_date_str'), 'queue_tickets', ['date_str'], unique=False)
    op.create_index(op.f('ix_queue_tickets_department'), 'queue_tickets', ['department'], unique=False)
    op.create_index(op.f('ix_queue_tickets_id'), 'queue_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_queue_tickets_status'), 'queue_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_queue_tickets_ticket_number'), 'queue_tickets', ['ticket_number'], unique=False)
    op.alter_column('schedule_templates', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_sched_dep', table_name='schedule_templates')
    op.drop_index('ix_sched_doc', table_name='schedule_templates')
    op.drop_index('ix_sched_wd', table_name='schedule_templates')
    op.create_index(op.f('ix_schedule_templates_department'), 'schedule_templates', ['department'], unique=False)
    op.create_index(op.f('ix_schedule_templates_doctor_id'), 'schedule_templates', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_schedule_templates_id'), 'schedule_templates', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_templates_weekday'), 'schedule_templates', ['weekday'], unique=False)
    op.add_column('service_catalog', sa.Column('currency', sa.String(length=8), nullable=True))
    op.alter_column('service_catalog', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('service_catalog', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               nullable=True)
    op.alter_column('service_catalog', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('service_catalog', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_service_catalog_dept', table_name='service_catalog')
    op.drop_index('ux_service_catalog_code', table_name='service_catalog')
    op.create_index(op.f('ix_service_catalog_code'), 'service_catalog', ['code'], unique=False)
    op.create_index(op.f('ix_service_catalog_name'), 'service_catalog', ['name'], unique=False)
    op.drop_column('service_catalog', 'unit')
    op.drop_column('service_catalog', 'updated_at')
    op.drop_column('service_catalog', 'department')
    op.add_column('services', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'service_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'services', 'doctors', ['doctor_id'], ['id'])
    op.alter_column('settings', 'category',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('settings', 'key',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('settings', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('settings', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('settings', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_settings_category', table_name='settings')
    op.drop_index('ux_settings_cat_key', table_name='settings')
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_unique_constraint('uq_settings_category_key', 'settings', ['category', 'key'])
    op.alter_column('user_sessions', 'refresh_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('user_sessions', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_index('ix_user_sessions_user', table_name='user_sessions')
    op.drop_index('ux_user_sessions_token', table_name='user_sessions')
    op.create_index('idx_user_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_user_sessions_user_active', 'user_sessions', ['user_id', 'revoked'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
    op.drop_index('ux_users_email', table_name='users')
    op.drop_index('ux_users_username', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'password_changed_at')
    op.add_column('visit_services', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('visit_services', sa.Column('currency', sa.String(length=8), nullable=True))
    op.alter_column('visit_services', 'qty',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('visit_services', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               nullable=True)
    op.alter_column('visit_services', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_visit_services_visit_id', table_name='visit_services')
    op.drop_index('ix_visit_services_code', table_name='visit_services')
    op.drop_index('ix_visit_services_visit', table_name='visit_services')
    op.create_index(op.f('ix_visit_services_service_id'), 'visit_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_visit_services_visit_id'), 'visit_services', ['visit_id'], unique=False)
    op.drop_column('visit_services', 'code')
    op.drop_column('visit_services', 'name')
    op.alter_column('visits', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visits', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('visits', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('visits', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_visits_doctor_id', table_name='visits')
    op.drop_index('idx_visits_patient_id', table_name='visits')
    op.drop_index('ix_visits_doctor', table_name='visits')
    op.drop_index('ix_visits_patient', table_name='visits')
    op.drop_index('ix_visits_payment_provider', table_name='visits')
    op.drop_index('ix_visits_payment_status', table_name='visits')
    op.drop_index('ix_visits_payment_transaction', table_name='visits')
    op.drop_index('ix_visits_status', table_name='visits')
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_column('visits', 'planned_date')
    op.drop_column('visits', 'payment_currency')
    op.drop_column('visits', 'doctor_id')
    op.drop_column('visits', 'finished_at')
    op.drop_column('visits', 'started_at')
    op.drop_column('visits', 'payment_status')
    op.drop_column('visits', 'payment_provider')
    op.drop_column('visits', 'payment_processed_at')
    op.drop_column('visits', 'payment_webhook_id')
    op.drop_column('visits', 'payment_amount')
    op.drop_column('visits', 'payment_transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('payment_transaction_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('visits', sa.Column('payment_amount', sa.NUMERIC(precision=12, scale=2), nullable=True))
    op.add_column('visits', sa.Column('payment_webhook_id', sa.INTEGER(), nullable=True))
    op.add_column('visits', sa.Column('payment_processed_at', sa.DATETIME(), nullable=True))
    op.add_column('visits', sa.Column('payment_provider', sa.VARCHAR(length=32), nullable=True))
    op.add_column('visits', sa.Column('payment_status', sa.VARCHAR(length=32), server_default=sa.text("'unpaid'"), nullable=True))
    op.add_column('visits', sa.Column('started_at', sa.DATETIME(), nullable=True))
    op.add_column('visits', sa.Column('finished_at', sa.DATETIME(), nullable=True))
    op.add_column('visits', sa.Column('doctor_id', sa.INTEGER(), nullable=True))
    op.add_column('visits', sa.Column('payment_currency', sa.VARCHAR(length=3), server_default=sa.text("'UZS'"), nullable=True))
    op.add_column('visits', sa.Column('planned_date', sa.DATE(), nullable=True))
    op.create_foreign_key(None, 'visits', 'users', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'visits', 'patients', ['patient_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.create_index('ix_visits_status', 'visits', ['status'], unique=False)
    op.create_index('ix_visits_payment_transaction', 'visits', ['payment_transaction_id'], unique=False)
    op.create_index('ix_visits_payment_status', 'visits', ['payment_status'], unique=False)
    op.create_index('ix_visits_payment_provider', 'visits', ['payment_provider'], unique=False)
    op.create_index('ix_visits_patient', 'visits', ['patient_id'], unique=False)
    op.create_index('ix_visits_doctor', 'visits', ['doctor_id'], unique=False)
    op.create_index('idx_visits_patient_id', 'visits', ['patient_id'], unique=False)
    op.create_index('idx_visits_doctor_id', 'visits', ['doctor_id'], unique=False)
    op.alter_column('visits', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('visits', 'notes',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('visits', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'open'"),
               existing_nullable=False)
    op.alter_column('visits', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('visit_services', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('visit_services', sa.Column('code', sa.VARCHAR(length=32), nullable=True))
    op.drop_index(op.f('ix_visit_services_visit_id'), table_name='visit_services')
    op.drop_index(op.f('ix_visit_services_service_id'), table_name='visit_services')
    op.create_index('ix_visit_services_visit', 'visit_services', ['visit_id'], unique=False)
    op.create_index('ix_visit_services_code', 'visit_services', ['code'], unique=False)
    op.create_index('idx_visit_services_visit_id', 'visit_services', ['visit_id'], unique=False)
    op.alter_column('visit_services', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('visit_services', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'"),
               nullable=False)
    op.alter_column('visit_services', 'qty',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.drop_column('visit_services', 'currency')
    op.drop_column('visit_services', 'service_id')
    op.add_column('users', sa.Column('password_changed_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ux_users_username', 'users', ['username'], unique=1)
    op.create_index('ux_users_email', 'users', ['email'], unique=1)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               server_default=sa.text("'User'"),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index('idx_user_sessions_user_active', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expires', table_name='user_sessions')
    op.create_index('ux_user_sessions_token', 'user_sessions', ['refresh_token'], unique=1)
    op.create_index('ix_user_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.alter_column('user_sessions', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_sessions', 'refresh_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_constraint('uq_settings_category_key', 'settings', type_='unique')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.create_index('ux_settings_cat_key', 'settings', ['category', 'key'], unique=1)
    op.create_index('ix_settings_category', 'settings', ['category'], unique=False)
    op.alter_column('settings', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('settings', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('settings', 'value',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('settings', 'key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('settings', 'category',
               existing_type=sa.String(length=50),
               server_default=sa.text("'default'"),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'doctor_id')
    op.drop_column('services', 'duration_minutes')
    op.drop_column('services', 'category_id')
    op.add_column('service_catalog', sa.Column('department', sa.VARCHAR(length=64), nullable=True))
    op.add_column('service_catalog', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('service_catalog', sa.Column('unit', sa.VARCHAR(length=32), nullable=True))
    op.drop_index(op.f('ix_service_catalog_name'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_code'), table_name='service_catalog')
    op.create_index('ux_service_catalog_code', 'service_catalog', ['code'], unique=1)
    op.create_index('ix_service_catalog_dept', 'service_catalog', ['department'], unique=False)
    op.alter_column('service_catalog', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('service_catalog', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('service_catalog', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'"),
               nullable=False)
    op.alter_column('service_catalog', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('service_catalog', 'currency')
    op.drop_index(op.f('ix_schedule_templates_weekday'), table_name='schedule_templates')
    op.drop_index(op.f('ix_schedule_templates_id'), table_name='schedule_templates')
    op.drop_index(op.f('ix_schedule_templates_doctor_id'), table_name='schedule_templates')
    op.drop_index(op.f('ix_schedule_templates_department'), table_name='schedule_templates')
    op.create_index('ix_sched_wd', 'schedule_templates', ['weekday'], unique=False)
    op.create_index('ix_sched_doc', 'schedule_templates', ['doctor_id'], unique=False)
    op.create_index('ix_sched_dep', 'schedule_templates', ['department'], unique=False)
    op.alter_column('schedule_templates', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_index(op.f('ix_queue_tickets_ticket_number'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_status'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_id'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_department'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_date_str'), table_name='queue_tickets')
    op.create_index('uq_queue_dep_date_ticket__uniq_idx', 'queue_tickets', ['department', 'date_str', 'ticket_number'], unique=1)
    op.create_index('ix_queue_ticket', 'queue_tickets', ['ticket_number'], unique=False)
    op.create_index('ix_queue_status', 'queue_tickets', ['status'], unique=False)
    op.create_index('ix_queue_dep', 'queue_tickets', ['department'], unique=False)
    op.create_index('ix_queue_date', 'queue_tickets', ['date_str'], unique=False)
    op.alter_column('queue_tickets', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'waiting'"),
               existing_nullable=False)
    op.add_column('payments', sa.Column('cashier_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'payments', 'users', ['cashier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'payments', 'visits', ['visit_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_payments_visit_id'), table_name='payments')
    op.create_index('ux_payments_receipt', 'payments', ['receipt_no'], unique=1)
    op.create_index('ix_payments_visit', 'payments', ['visit_id'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_cashier', 'payments', ['cashier_id'], unique=False)
    op.create_index('idx_payments_visit_id', 'payments', ['visit_id'], unique=False)
    op.alter_column('payments', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('payments', 'note',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'paid'"),
               existing_nullable=False)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'cash'"),
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'UZS'"),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('payments', 'visit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_transactions', 'commission',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'payment_providers', type_='unique')
    op.alter_column('payment_providers', 'max_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment_providers', 'min_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment_providers', 'commission_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_patients_last_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_first_name'), table_name='patients')
    op.create_index('ix_patients_phone', 'patients', ['phone'], unique=False)
    op.create_index('ix_patients_doc', 'patients', ['doc_type', 'doc_number'], unique=False)
    op.alter_column('patients', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('patients', 'middle_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('patients', 'first_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('patients', 'last_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint('uq_online_day_dep_date', 'online_days', type_='unique')
    op.drop_index(op.f('ix_online_days_id'), table_name='online_days')
    op.drop_index(op.f('ix_online_days_department'), table_name='online_days')
    op.drop_index(op.f('ix_online_days_date_str'), table_name='online_days')
    op.create_index('uq_online_day_dep_date__uniq_idx', 'online_days', ['department', 'date_str'], unique=1)
    op.create_index('ix_online_days_dep', 'online_days', ['department'], unique=False)
    op.create_index('ix_online_days_date', 'online_days', ['date_str'], unique=False)
    op.add_column('notification_history', sa.Column('metadata', sqlite.JSON(), nullable=True))
    op.drop_column('notification_history', 'notification_metadata')
    op.drop_index(op.f('ix_lab_results_test_code'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_order_id'), table_name='lab_results')
    op.create_index('ix_lab_results_order', 'lab_results', ['order_id'], unique=False)
    op.create_index('ix_lab_results_code', 'lab_results', ['test_code'], unique=False)
    op.alter_column('lab_results', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('lab_results', 'abnormal',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_lab_orders_visit_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_patient_id'), table_name='lab_orders')
    op.create_index('ix_lab_orders_visit', 'lab_orders', ['visit_id'], unique=False)
    op.create_index('ix_lab_orders_status', 'lab_orders', ['status'], unique=False)
    op.create_index('ix_lab_orders_patient', 'lab_orders', ['patient_id'], unique=False)
    op.alter_column('lab_orders', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('lab_orders', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'ordered'"),
               existing_nullable=False)
    op.alter_column('emr', 'ai_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('emr', 'ai_suggestions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'social_history',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'family_history',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'allergies',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'medications',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'imaging_results',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'lab_results',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'vital_signs',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text("(datetime('now'))"),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('audit_logs', 'payload',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index('idx_activations_machine_hash', 'activations', ['machine_hash'], unique=False)
    op.create_index('idx_activations_key', 'activations', ['key'], unique=False)
    op.alter_column('activations', 'status',
               existing_type=sa.VARCHAR(length=7),
               server_default=sa.text("'issued'"),
               existing_nullable=False)
    op.create_table('telegram_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('template_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('template_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('language', sa.VARCHAR(length=5), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=True),
    sa.Column('message_text', sa.TEXT(), nullable=False),
    sa.Column('parse_mode', sa.VARCHAR(length=20), nullable=False),
    sa.Column('disable_web_page_preview', sa.BOOLEAN(), nullable=False),
    sa.Column('inline_buttons', sqlite.JSON(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telegram_templates_template_key', 'telegram_templates', ['template_key'], unique=False)
    op.create_index('ix_telegram_templates_id', 'telegram_templates', ['id'], unique=False)
    op.create_table('display_banners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('board_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('link_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('display_duration', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=5), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['display_boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_display_banners_id', 'display_banners', ['id'], unique=False)
    op.create_table('display_themes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('css_variables', sqlite.JSON(), nullable=False),
    sa.Column('font_family', sa.VARCHAR(length=100), nullable=False),
    sa.Column('font_sizes', sqlite.JSON(), nullable=True),
    sa.Column('background_config', sqlite.JSON(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_display_themes_id', 'display_themes', ['id'], unique=False)
    op.create_table('print_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('printer_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('template_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('template_content', sa.TEXT(), nullable=False),
    sa.Column('language', sa.VARCHAR(length=5), nullable=False),
    sa.Column('font_size', sa.INTEGER(), nullable=False),
    sa.Column('line_spacing', sa.INTEGER(), nullable=False),
    sa.Column('char_per_line', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_print_templates_id', 'print_templates', ['id'], unique=False)
    op.create_table('telegram_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=True),
    sa.Column('message_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('template_key', sa.VARCHAR(length=100), nullable=True),
    sa.Column('message_text', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('sent_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('related_entity_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('related_entity_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telegram_messages_id', 'telegram_messages', ['id'], unique=False)
    op.create_index('ix_telegram_messages_created_at', 'telegram_messages', ['created_at'], unique=False)
    op.create_index('ix_telegram_messages_chat_id', 'telegram_messages', ['chat_id'], unique=False)
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('provider_id', sa.INTEGER(), nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('specialty', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('request_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('cached_response', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_usage_logs_task_type', 'ai_usage_logs', ['task_type'], unique=False)
    op.create_index('ix_ai_usage_logs_request_hash', 'ai_usage_logs', ['request_hash'], unique=False)
    op.create_index('ix_ai_usage_logs_id', 'ai_usage_logs', ['id'], unique=False)
    op.create_index('ix_ai_usage_logs_created_at', 'ai_usage_logs', ['created_at'], unique=False)
    op.create_table('print_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('printer_id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('print_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer_configs.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['print_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_print_jobs_id', 'print_jobs', ['id'], unique=False)
    op.create_index('ix_print_jobs_created_at', 'print_jobs', ['created_at'], unique=False)
    op.create_table('telegram_configs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bot_token', sa.VARCHAR(length=200), nullable=True),
    sa.Column('webhook_url', sa.VARCHAR(length=300), nullable=True),
    sa.Column('webhook_secret', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bot_username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bot_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('admin_chat_ids', sqlite.JSON(), nullable=True),
    sa.Column('notifications_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('appointment_reminders', sa.BOOLEAN(), nullable=False),
    sa.Column('lab_results_notifications', sa.BOOLEAN(), nullable=False),
    sa.Column('payment_notifications', sa.BOOLEAN(), nullable=False),
    sa.Column('default_language', sa.VARCHAR(length=5), nullable=False),
    sa.Column('supported_languages', sqlite.JSON(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telegram_configs_id', 'telegram_configs', ['id'], unique=False)
    op.create_table('display_boards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('theme', sa.VARCHAR(length=50), nullable=False),
    sa.Column('show_patient_names', sa.VARCHAR(length=20), nullable=False),
    sa.Column('show_doctor_photos', sa.BOOLEAN(), nullable=False),
    sa.Column('queue_display_count', sa.INTEGER(), nullable=False),
    sa.Column('show_announcements', sa.BOOLEAN(), nullable=False),
    sa.Column('show_banners', sa.BOOLEAN(), nullable=False),
    sa.Column('show_videos', sa.BOOLEAN(), nullable=False),
    sa.Column('call_display_duration', sa.INTEGER(), nullable=False),
    sa.Column('sound_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('voice_announcements', sa.BOOLEAN(), nullable=False),
    sa.Column('voice_language', sa.VARCHAR(length=5), nullable=False),
    sa.Column('volume_level', sa.INTEGER(), nullable=False),
    sa.Column('colors', sqlite.JSON(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_display_boards_id', 'display_boards', ['id'], unique=False)
    op.create_table('ai_providers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=200), nullable=True),
    sa.Column('api_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=False),
    sa.Column('max_tokens', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('capabilities', sqlite.JSON(), nullable=True),
    sa.Column('limits', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_ai_providers_id', 'ai_providers', ['id'], unique=False)
    op.create_table('telegram_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('language_code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('notifications_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('appointment_reminders', sa.BOOLEAN(), nullable=False),
    sa.Column('lab_notifications', sa.BOOLEAN(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('blocked', sa.BOOLEAN(), nullable=False),
    sa.Column('last_activity', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telegram_users_id', 'telegram_users', ['id'], unique=False)
    op.create_index('ix_telegram_users_chat_id', 'telegram_users', ['chat_id'], unique=1)
    op.create_table('ai_prompt_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider_id', sa.INTEGER(), nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('specialty', sa.VARCHAR(length=50), nullable=True),
    sa.Column('language', sa.VARCHAR(length=5), nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('system_prompt', sa.TEXT(), nullable=False),
    sa.Column('context_template', sa.TEXT(), nullable=True),
    sa.Column('task_template', sa.TEXT(), nullable=False),
    sa.Column('examples', sqlite.JSON(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('max_tokens', sa.INTEGER(), nullable=True),
    sa.Column('response_schema', sqlite.JSON(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_prompt_templates_task_type', 'ai_prompt_templates', ['task_type'], unique=False)
    op.create_index('ix_ai_prompt_templates_specialty', 'ai_prompt_templates', ['specialty'], unique=False)
    op.create_index('ix_ai_prompt_templates_id', 'ai_prompt_templates', ['id'], unique=False)
    op.create_table('display_videos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('board_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('file_size_mb', sa.FLOAT(), nullable=True),
    sa.Column('video_format', sa.VARCHAR(length=20), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('loop_count', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['display_boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_display_videos_id', 'display_videos', ['id'], unique=False)
    op.create_table('audit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=64), nullable=False),
    sa.Column('entity', sa.VARCHAR(length=64), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('meta', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_user_id', 'audit', ['user_id'], unique=False)
    op.create_index('ix_audit_entity_id', 'audit', ['entity_id'], unique=False)
    op.create_index('ix_audit_entity', 'audit', ['entity'], unique=False)
    op.create_index('ix_audit_created_at', 'audit', ['created_at'], unique=False)
    op.create_index('ix_audit_action', 'audit', ['action'], unique=False)
    op.create_table('doctors_new',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('specialty', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cabinet', sa.VARCHAR(length=20), nullable=True),
    sa.Column('price_default', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('start_number_online', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_online_per_day', sa.INTEGER(), server_default=sa.text('(15)'), nullable=False),
    sa.Column('auto_close_time', sa.TIME(), server_default=sa.text("'09:00'"), nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('branch_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('display_announcements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('board_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('announcement_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('scroll_speed', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=5), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['display_boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_display_announcements_id', 'display_announcements', ['id'], unique=False)
    op.create_table('printer_configs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('printer_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('connection_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('port', sa.INTEGER(), nullable=True),
    sa.Column('device_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('paper_width', sa.INTEGER(), nullable=True),
    sa.Column('paper_height', sa.INTEGER(), nullable=True),
    sa.Column('margins', sqlite.JSON(), nullable=True),
    sa.Column('encoding', sa.VARCHAR(length=20), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_printer_configs_id', 'printer_configs', ['id'], unique=False)
    op.create_table('visit_billings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('visit_id', sa.INTEGER(), nullable=False),
    sa.Column('subtotal_services', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('discount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('total_due', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('paid_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=8), server_default=sa.text("'UZS'"), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'open'"), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_index('ux_visit_billings_visit', 'visit_billings', ['visit_id'], unique=1)
    op.create_index('ix_visit_billings_status', 'visit_billings', ['status'], unique=False)
    op.drop_index(op.f('ix_file_versions_id'), table_name='file_versions')
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index(op.f('ix_file_shares_shared_with_user_id'), table_name='file_shares')
    op.drop_index(op.f('ix_file_shares_shared_with_email'), table_name='file_shares')
    op.drop_index(op.f('ix_file_shares_id'), table_name='file_shares')
    op.drop_index(op.f('ix_file_shares_file_id'), table_name='file_shares')
    op.drop_index(op.f('ix_file_shares_access_token'), table_name='file_shares')
    op.drop_table('file_shares')
    op.drop_index(op.f('ix_file_access_logs_user_id'), table_name='file_access_logs')
    op.drop_index(op.f('ix_file_access_logs_id'), table_name='file_access_logs')
    op.drop_index(op.f('ix_file_access_logs_file_id'), table_name='file_access_logs')
    op.drop_table('file_access_logs')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_index(op.f('ix_files_patient_id'), table_name='files')
    op.drop_index(op.f('ix_files_owner_id'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_index(op.f('ix_files_file_type'), table_name='files')
    op.drop_index(op.f('ix_files_file_hash'), table_name='files')
    op.drop_index(op.f('ix_files_emr_id'), table_name='files')
    op.drop_index(op.f('ix_files_appointment_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_file_quotas_user_id'), table_name='file_quotas')
    op.drop_index(op.f('ix_file_quotas_id'), table_name='file_quotas')
    op.drop_table('file_quotas')
    op.drop_index(op.f('ix_file_folders_parent_id'), table_name='file_folders')
    op.drop_index(op.f('ix_file_folders_owner_id'), table_name='file_folders')
    op.drop_index(op.f('ix_file_folders_id'), table_name='file_folders')
    op.drop_table('file_folders')
    op.drop_index(op.f('ix_file_storage_id'), table_name='file_storage')
    op.drop_table('file_storage')
    # ### end Alembic commands ###
