"""add_queue_tag_to_daily_queues

Revision ID: b3a7a4f9c515
Revises: 38cc09372067
Create Date: 2025-09-25 08:10:05.200134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b3a7a4f9c515'
down_revision = '38cc09372067'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Безопасно удаляем индексы и таблицы только если они существуют
    
    # Проверяем и удаляем индексы medical_records
    try:
        op.drop_index('idx_medical_records_appointment_id', table_name='medical_records')
    except:
        pass
    try:
        op.drop_index('idx_medical_records_created_at', table_name='medical_records')
    except:
        pass
    try:
        op.drop_index('idx_medical_records_doctor_id', table_name='medical_records')
    except:
        pass
    try:
        op.drop_index('idx_medical_records_patient_id', table_name='medical_records')
    except:
        pass
    try:
        op.drop_index('idx_medical_records_status', table_name='medical_records')
    except:
        pass
    try:
        op.drop_table('medical_records')
    except:
        pass
    
    # Проверяем и удаляем индексы queue_tickets
    try:
        op.drop_index('ix_queue_date', table_name='queue_tickets')
    except:
        pass
    try:
        op.drop_index('ix_queue_dep', table_name='queue_tickets')
    except:
        pass
    try:
        op.drop_index('ix_queue_status', table_name='queue_tickets')
    except:
        pass
    try:
        op.drop_index('ix_queue_ticket', table_name='queue_tickets')
    except:
        pass
    try:
        op.drop_index('uq_queue_dep_date_ticket__uniq_idx', table_name='queue_tickets')
    except:
        pass
    try:
        op.drop_table('queue_tickets')
    except:
        pass
    op.alter_column('activations', 'status',
               existing_type=sa.VARCHAR(length=7),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_activations_key', table_name='activations')
    op.drop_index('idx_activations_machine_hash', table_name='activations')
    op.alter_column('appointments', 'visit_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=True)
    op.alter_column('appointments', 'payment_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('audit_logs', 'payload',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.drop_constraint(None, 'daily_queues', type_='foreignkey')
    op.create_foreign_key(None, 'daily_queues', 'users', ['specialist_id'], ['id'])
    op.alter_column('doctor_price_overrides', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('doctor_price_overrides', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('doctor_price_overrides', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'doctors', 'branches', ['branch_id'], ['id'])
    op.alter_column('emr', 'vital_signs',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'lab_results',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'imaging_results',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'medications',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'allergies',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'family_history',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'social_history',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'ai_suggestions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emr', 'ai_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_files_folder_id'), 'files', ['folder_id'], unique=False)
    op.alter_column('lab_orders', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lab_orders', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_lab_orders_patient', table_name='lab_orders')
    op.drop_index('ix_lab_orders_status', table_name='lab_orders')
    op.drop_index('ix_lab_orders_visit', table_name='lab_orders')
    op.create_index(op.f('ix_lab_orders_patient_id'), 'lab_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_visit_id'), 'lab_orders', ['visit_id'], unique=False)
    op.alter_column('lab_results', 'abnormal',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lab_results', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_lab_results_code', table_name='lab_results')
    op.drop_index('ix_lab_results_order', table_name='lab_results')
    op.create_index(op.f('ix_lab_results_order_id'), 'lab_results', ['order_id'], unique=False)
    op.create_index(op.f('ix_lab_results_test_code'), 'lab_results', ['test_code'], unique=False)
    op.drop_index('ix_online_days_date', table_name='online_days')
    op.drop_index('ix_online_days_dep', table_name='online_days')
    op.drop_index('uq_online_day_dep_date__uniq_idx', table_name='online_days')
    op.create_index(op.f('ix_online_days_date_str'), 'online_days', ['date_str'], unique=False)
    op.create_index(op.f('ix_online_days_department'), 'online_days', ['department'], unique=False)
    op.create_index(op.f('ix_online_days_id'), 'online_days', ['id'], unique=False)
    op.create_unique_constraint('uq_online_day_dep_date', 'online_days', ['department', 'date_str'])
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('patients', 'first_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('patients', 'middle_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('patients', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_patients_doc', table_name='patients')
    op.drop_index('ix_patients_phone', table_name='patients')
    op.create_index(op.f('ix_patients_first_name'), 'patients', ['first_name'], unique=False)
    op.create_index(op.f('ix_patients_last_name'), 'patients', ['last_name'], unique=False)
    op.create_unique_constraint(None, 'patients', ['user_id'])
    op.drop_index('uq_payment_invoice_visits_invoice_visit', table_name='payment_invoice_visits')
    op.alter_column('payment_invoices', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payment_invoices', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payment_invoices', 'payment_method',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payment_invoices', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.add_column('payment_providers', sa.Column('merchant_id', sa.String(length=100), nullable=True))
    op.add_column('payment_providers', sa.Column('service_id', sa.String(length=100), nullable=True))
    op.add_column('payment_providers', sa.Column('supported_currencies', sa.String(length=100), nullable=True))
    op.add_column('payment_providers', sa.Column('config', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'payment_providers', ['name'])
    op.add_column('payment_transactions', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.add_column('payment_transactions', sa.Column('provider_data', sa.JSON(), nullable=True))
    op.add_column('payment_transactions', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('payment_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_payment_transactions_payment_id'), 'payment_transactions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_visit_id'), 'payment_transactions', ['visit_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_webhook_id'), 'payment_transactions', ['webhook_id'], unique=False)
    op.create_foreign_key(None, 'payment_transactions', 'payment_webhooks', ['webhook_id'], ['id'])
    op.create_foreign_key(None, 'payment_transactions', 'payments', ['payment_id'], ['id'])
    op.add_column('payment_webhooks', sa.Column('payment_status', sa.String(length=32), nullable=True))
    op.add_column('payment_webhooks', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payment_webhooks_patient_id'), 'payment_webhooks', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payment_webhooks_payment_id'), 'payment_webhooks', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_webhooks_visit_id'), 'payment_webhooks', ['visit_id'], unique=False)
    op.create_foreign_key(None, 'payment_webhooks', 'payments', ['payment_id'], ['id'])
    op.alter_column('payments', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_payments_method', table_name='payments')
    op.drop_index('idx_payments_provider', table_name='payments')
    op.drop_index('idx_payments_provider_payment_id', table_name='payments')
    op.drop_index('idx_payments_provider_transaction_id', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_visit_id', table_name='payments')
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_transaction_id'), 'payments', ['provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_payments_visit_id'), 'payments', ['visit_id'], unique=False)
    op.drop_column('payments', 'cashier_id')
    op.alter_column('schedule_templates', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_sched_dep', table_name='schedule_templates')
    op.drop_index('ix_sched_doc', table_name='schedule_templates')
    op.drop_index('ix_sched_wd', table_name='schedule_templates')
    op.create_index(op.f('ix_schedule_templates_department'), 'schedule_templates', ['department'], unique=False)
    op.create_index(op.f('ix_schedule_templates_doctor_id'), 'schedule_templates', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_schedule_templates_id'), 'schedule_templates', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_templates_weekday'), 'schedule_templates', ['weekday'], unique=False)
    op.add_column('service_catalog', sa.Column('currency', sa.String(length=8), nullable=True))
    op.alter_column('service_catalog', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('service_catalog', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               nullable=True)
    op.alter_column('service_catalog', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('service_catalog', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_service_catalog_dept', table_name='service_catalog')
    op.drop_index('ux_service_catalog_code', table_name='service_catalog')
    op.create_index(op.f('ix_service_catalog_code'), 'service_catalog', ['code'], unique=False)
    op.create_index(op.f('ix_service_catalog_name'), 'service_catalog', ['name'], unique=False)
    op.drop_column('service_catalog', 'unit')
    op.drop_column('service_catalog', 'updated_at')
    op.drop_column('service_catalog', 'department')
    op.alter_column('services', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('services', 'requires_doctor',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('services', 'is_consultation',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('services', 'allow_doctor_price_override',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_services_category_code'), 'services', ['category_code'], unique=False)
    op.create_index(op.f('ix_services_service_code'), 'services', ['service_code'], unique=True)
    op.create_foreign_key(None, 'services', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'services', 'service_categories', ['category_id'], ['id'])
    op.alter_column('settings', 'category',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('settings', 'key',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('settings', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('settings', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('settings', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_settings_category', table_name='settings')
    op.drop_index('ux_settings_cat_key', table_name='settings')
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_unique_constraint('uq_settings_category_key', 'settings', ['category', 'key'])
    op.alter_column('telegram_configs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('telegram_configs', 'bot_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('telegram_configs', 'webhook_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('telegram_configs', 'webhook_secret',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('telegram_configs', 'bot_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('telegram_configs', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_configs', 'appointment_reminders',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_configs', 'lab_results_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_configs', 'payment_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_configs', 'default_language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               type_=sa.String(length=5),
               nullable=False)
    op.alter_column('telegram_configs', 'supported_languages',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('telegram_configs', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.drop_index('idx_telegram_configs_active', table_name='telegram_configs')
    op.create_index(op.f('ix_telegram_configs_id'), 'telegram_configs', ['id'], unique=False)
    op.add_column('telegram_messages', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.add_column('telegram_messages', sa.Column('message_id', sa.Integer(), nullable=True))
    op.add_column('telegram_messages', sa.Column('template_key', sa.String(length=100), nullable=True))
    op.add_column('telegram_messages', sa.Column('sent_by_user_id', sa.Integer(), nullable=True))
    op.add_column('telegram_messages', sa.Column('related_entity_type', sa.String(length=50), nullable=True))
    op.add_column('telegram_messages', sa.Column('related_entity_id', sa.Integer(), nullable=True))
    op.add_column('telegram_messages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('telegram_messages', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('telegram_messages', 'message_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('telegram_messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_messages', 'sent_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_telegram_messages_status', table_name='telegram_messages')
    op.drop_index('idx_telegram_messages_type', table_name='telegram_messages')
    op.drop_index('idx_telegram_messages_user_id', table_name='telegram_messages')
    op.create_index(op.f('ix_telegram_messages_chat_id'), 'telegram_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_telegram_messages_created_at'), 'telegram_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_telegram_messages_id'), 'telegram_messages', ['id'], unique=False)
    op.create_foreign_key(None, 'telegram_messages', 'users', ['sent_by_user_id'], ['id'])
    op.drop_column('telegram_messages', 'telegram_user_id')
    op.drop_column('telegram_messages', 'message_data')
    op.alter_column('telegram_templates', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('telegram_templates', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('telegram_templates', 'parse_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_templates', 'disable_web_page_preview',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_templates', 'inline_buttons',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('telegram_templates', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_telegram_templates_id'), 'telegram_templates', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_templates_template_key'), 'telegram_templates', ['template_key'], unique=False)
    op.alter_column('telegram_users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('telegram_users', 'chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('telegram_users', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               type_=sa.String(length=5),
               nullable=False)
    op.alter_column('telegram_users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_users', 'appointment_reminders',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_users', 'lab_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_users', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('telegram_users', 'blocked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.drop_index('idx_telegram_users_active', table_name='telegram_users')
    op.drop_index('idx_telegram_users_telegram_id', table_name='telegram_users')
    op.create_index(op.f('ix_telegram_users_chat_id'), 'telegram_users', ['chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_users_id'), 'telegram_users', ['id'], unique=False)
    op.drop_column('telegram_users', 'telegram_id')
    op.drop_column('telegram_users', 'is_bot')
    op.drop_column('telegram_users', 'updated_at')
    op.drop_column('telegram_users', 'is_active')
    op.alter_column('user_sessions', 'refresh_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('user_sessions', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_index('ix_user_sessions_user', table_name='user_sessions')
    op.drop_index('ux_user_sessions_token', table_name='user_sessions')
    op.create_index('idx_user_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_user_sessions_user_active', 'user_sessions', ['user_id', 'revoked'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
    op.drop_index('ux_users_email', table_name='users')
    op.drop_index('ux_users_username', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'password_changed_at')
    op.alter_column('visit_services', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visit_services', 'qty',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('visit_services', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               nullable=True)
    op.alter_column('visit_services', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_visit_services_visit_id', table_name='visit_services')
    op.drop_index('ix_visit_services_code', table_name='visit_services')
    op.drop_index('ix_visit_services_visit', table_name='visit_services')
    op.create_index(op.f('ix_visit_services_service_id'), 'visit_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_visit_services_visit_id'), 'visit_services', ['visit_id'], unique=False)
    op.alter_column('visits', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visits', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('visits', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('visits', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('visits', 'discount_mode',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('visits', 'approval_status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_visits_doctor_id', table_name='visits')
    op.drop_index('idx_visits_patient_id', table_name='visits')
    op.drop_index('ix_visits_doctor', table_name='visits')
    op.drop_index('ix_visits_patient', table_name='visits')
    op.drop_index('ix_visits_payment_provider', table_name='visits')
    op.drop_index('ix_visits_payment_status', table_name='visits')
    op.drop_index('ix_visits_payment_transaction', table_name='visits')
    op.drop_index('ix_visits_status', table_name='visits')
    op.create_index(op.f('ix_visits_doctor_id'), 'visits', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.create_foreign_key(None, 'visits', 'doctors', ['doctor_id'], ['id'])
    op.drop_column('visits', 'finished_at')
    op.drop_column('visits', 'payment_status')
    op.drop_column('visits', 'payment_processed_at')
    op.drop_column('visits', 'payment_webhook_id')
    op.drop_column('visits', 'payment_transaction_id')
    op.drop_column('visits', 'payment_amount')
    op.drop_column('visits', 'payment_currency')
    op.drop_column('visits', 'payment_provider')
    op.drop_column('visits', 'started_at')
    op.drop_column('visits', 'planned_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('planned_date', sa.DATE(), nullable=True))
    op.add_column('visits', sa.Column('started_at', sa.DATETIME(), nullable=True))
    op.add_column('visits', sa.Column('payment_provider', sa.VARCHAR(length=32), nullable=True))
    op.add_column('visits', sa.Column('payment_currency', sa.VARCHAR(length=3), server_default=sa.text("'UZS'"), nullable=True))
    op.add_column('visits', sa.Column('payment_amount', sa.NUMERIC(precision=12, scale=2), nullable=True))
    op.add_column('visits', sa.Column('payment_transaction_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('visits', sa.Column('payment_webhook_id', sa.INTEGER(), nullable=True))
    op.add_column('visits', sa.Column('payment_processed_at', sa.DATETIME(), nullable=True))
    op.add_column('visits', sa.Column('payment_status', sa.VARCHAR(length=32), server_default=sa.text("'unpaid'"), nullable=True))
    op.add_column('visits', sa.Column('finished_at', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.create_foreign_key(None, 'visits', 'users', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'visits', 'patients', ['patient_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_doctor_id'), table_name='visits')
    op.create_index('ix_visits_status', 'visits', ['status'], unique=False)
    op.create_index('ix_visits_payment_transaction', 'visits', ['payment_transaction_id'], unique=False)
    op.create_index('ix_visits_payment_status', 'visits', ['payment_status'], unique=False)
    op.create_index('ix_visits_payment_provider', 'visits', ['payment_provider'], unique=False)
    op.create_index('ix_visits_patient', 'visits', ['patient_id'], unique=False)
    op.create_index('ix_visits_doctor', 'visits', ['doctor_id'], unique=False)
    op.create_index('idx_visits_patient_id', 'visits', ['patient_id'], unique=False)
    op.create_index('idx_visits_doctor_id', 'visits', ['doctor_id'], unique=False)
    op.alter_column('visits', 'approval_status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'none'"),
               existing_nullable=False)
    op.alter_column('visits', 'discount_mode',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'none'"),
               existing_nullable=False)
    op.alter_column('visits', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('visits', 'notes',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('visits', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'open'"),
               existing_nullable=False)
    op.alter_column('visits', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_visit_services_visit_id'), table_name='visit_services')
    op.drop_index(op.f('ix_visit_services_service_id'), table_name='visit_services')
    op.create_index('ix_visit_services_visit', 'visit_services', ['visit_id'], unique=False)
    op.create_index('ix_visit_services_code', 'visit_services', ['code'], unique=False)
    op.create_index('idx_visit_services_visit_id', 'visit_services', ['visit_id'], unique=False)
    op.alter_column('visit_services', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('visit_services', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'"),
               nullable=False)
    op.alter_column('visit_services', 'qty',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('visit_services', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('password_changed_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ux_users_username', 'users', ['username'], unique=1)
    op.create_index('ux_users_email', 'users', ['email'], unique=1)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               server_default=sa.text("'User'"),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index('idx_user_sessions_user_active', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expires', table_name='user_sessions')
    op.create_index('ux_user_sessions_token', 'user_sessions', ['refresh_token'], unique=1)
    op.create_index('ix_user_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.alter_column('user_sessions', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_sessions', 'refresh_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.add_column('telegram_users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
    op.add_column('telegram_users', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('telegram_users', sa.Column('is_bot', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.add_column('telegram_users', sa.Column('telegram_id', sa.INTEGER(), nullable=False))
    op.drop_index(op.f('ix_telegram_users_id'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_chat_id'), table_name='telegram_users')
    op.create_index('idx_telegram_users_telegram_id', 'telegram_users', ['telegram_id'], unique=False)
    op.create_index('idx_telegram_users_active', 'telegram_users', ['is_active'], unique=False)
    op.alter_column('telegram_users', 'blocked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('telegram_users', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('telegram_users', 'lab_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('telegram_users', 'appointment_reminders',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('telegram_users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('telegram_users', 'language_code',
               existing_type=sa.String(length=5),
               server_default=sa.text("'ru'"),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('telegram_users', 'chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('telegram_users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_telegram_templates_template_key'), table_name='telegram_templates')
    op.drop_index(op.f('ix_telegram_templates_id'), table_name='telegram_templates')
    op.alter_column('telegram_templates', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('telegram_templates', 'inline_buttons',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('telegram_templates', 'disable_web_page_preview',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('telegram_templates', 'parse_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'HTML'"),
               nullable=True)
    op.alter_column('telegram_templates', 'language',
               existing_type=sa.String(length=5),
               server_default=sa.text("'ru'"),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('telegram_templates', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('telegram_messages', sa.Column('message_data', sqlite.JSON(), nullable=True))
    op.add_column('telegram_messages', sa.Column('telegram_user_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'telegram_messages', type_='foreignkey')
    op.drop_index(op.f('ix_telegram_messages_id'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_created_at'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_chat_id'), table_name='telegram_messages')
    op.create_index('idx_telegram_messages_user_id', 'telegram_messages', ['telegram_user_id'], unique=False)
    op.create_index('idx_telegram_messages_type', 'telegram_messages', ['message_type'], unique=False)
    op.create_index('idx_telegram_messages_status', 'telegram_messages', ['status'], unique=False)
    op.alter_column('telegram_messages', 'sent_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
    op.alter_column('telegram_messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'sent'"),
               nullable=True)
    op.alter_column('telegram_messages', 'message_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('telegram_messages', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('telegram_messages', 'created_at')
    op.drop_column('telegram_messages', 'related_entity_id')
    op.drop_column('telegram_messages', 'related_entity_type')
    op.drop_column('telegram_messages', 'sent_by_user_id')
    op.drop_column('telegram_messages', 'template_key')
    op.drop_column('telegram_messages', 'message_id')
    op.drop_column('telegram_messages', 'chat_id')
    op.drop_index(op.f('ix_telegram_configs_id'), table_name='telegram_configs')
    op.create_index('idx_telegram_configs_active', 'telegram_configs', ['active'], unique=False)
    op.alter_column('telegram_configs', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('telegram_configs', 'supported_languages',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('telegram_configs', 'default_language',
               existing_type=sa.String(length=5),
               server_default=sa.text("'ru'"),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('telegram_configs', 'payment_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('telegram_configs', 'lab_results_notifications',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('telegram_configs', 'appointment_reminders',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('telegram_configs', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('telegram_configs', 'bot_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('telegram_configs', 'webhook_secret',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('telegram_configs', 'webhook_url',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('telegram_configs', 'bot_token',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('telegram_configs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_settings_category_key', 'settings', type_='unique')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.create_index('ux_settings_cat_key', 'settings', ['category', 'key'], unique=1)
    op.create_index('ix_settings_category', 'settings', ['category'], unique=False)
    op.alter_column('settings', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('settings', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('settings', 'value',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('settings', 'key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('settings', 'category',
               existing_type=sa.String(length=50),
               server_default=sa.text("'default'"),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_index(op.f('ix_services_service_code'), table_name='services')
    op.drop_index(op.f('ix_services_category_code'), table_name='services')
    op.alter_column('services', 'allow_doctor_price_override',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('services', 'is_consultation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('services', 'requires_doctor',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('services', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('(30)'),
               existing_nullable=True)
    op.add_column('service_catalog', sa.Column('department', sa.VARCHAR(length=64), nullable=True))
    op.add_column('service_catalog', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('service_catalog', sa.Column('unit', sa.VARCHAR(length=32), nullable=True))
    op.drop_index(op.f('ix_service_catalog_name'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_code'), table_name='service_catalog')
    op.create_index('ux_service_catalog_code', 'service_catalog', ['code'], unique=1)
    op.create_index('ix_service_catalog_dept', 'service_catalog', ['department'], unique=False)
    op.alter_column('service_catalog', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('service_catalog', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('service_catalog', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'"),
               nullable=False)
    op.alter_column('service_catalog', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('service_catalog', 'currency')
    op.drop_index(op.f('ix_schedule_templates_weekday'), table_name='schedule_templates')
    op.drop_index(op.f('ix_schedule_templates_id'), table_name='schedule_templates')
    op.drop_index(op.f('ix_schedule_templates_doctor_id'), table_name='schedule_templates')
    op.drop_index(op.f('ix_schedule_templates_department'), table_name='schedule_templates')
    op.create_index('ix_sched_wd', 'schedule_templates', ['weekday'], unique=False)
    op.create_index('ix_sched_doc', 'schedule_templates', ['doctor_id'], unique=False)
    op.create_index('ix_sched_dep', 'schedule_templates', ['department'], unique=False)
    op.alter_column('schedule_templates', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.add_column('payments', sa.Column('cashier_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_payments_visit_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.create_index('idx_payments_visit_id', 'payments', ['visit_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_provider_transaction_id', 'payments', ['provider_transaction_id'], unique=False)
    op.create_index('idx_payments_provider_payment_id', 'payments', ['provider_payment_id'], unique=False)
    op.create_index('idx_payments_provider', 'payments', ['provider'], unique=False)
    op.create_index('idx_payments_method', 'payments', ['method'], unique=False)
    op.alter_column('payments', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'paid'"),
               existing_nullable=False)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'cash'"),
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'UZS'"),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'payment_webhooks', type_='foreignkey')
    op.drop_index(op.f('ix_payment_webhooks_visit_id'), table_name='payment_webhooks')
    op.drop_index(op.f('ix_payment_webhooks_payment_id'), table_name='payment_webhooks')
    op.drop_index(op.f('ix_payment_webhooks_patient_id'), table_name='payment_webhooks')
    op.drop_column('payment_webhooks', 'payment_id')
    op.drop_column('payment_webhooks', 'payment_status')
    op.drop_constraint(None, 'payment_transactions', type_='foreignkey')
    op.drop_constraint(None, 'payment_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_payment_transactions_webhook_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_visit_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_id'), table_name='payment_transactions')
    op.alter_column('payment_transactions', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('payment_transactions', 'error_message')
    op.drop_column('payment_transactions', 'provider_data')
    op.drop_column('payment_transactions', 'payment_id')
    op.drop_constraint(None, 'payment_providers', type_='unique')
    op.drop_column('payment_providers', 'config')
    op.drop_column('payment_providers', 'supported_currencies')
    op.drop_column('payment_providers', 'service_id')
    op.drop_column('payment_providers', 'merchant_id')
    op.alter_column('payment_invoices', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('payment_invoices', 'payment_method',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'cash'"),
               existing_nullable=False)
    op.alter_column('payment_invoices', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'pending'"),
               existing_nullable=False)
    op.alter_column('payment_invoices', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'UZS'"),
               existing_nullable=False)
    op.create_index('uq_payment_invoice_visits_invoice_visit', 'payment_invoice_visits', ['invoice_id', 'visit_id'], unique=1)
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_last_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_first_name'), table_name='patients')
    op.create_index('ix_patients_phone', 'patients', ['phone'], unique=False)
    op.create_index('ix_patients_doc', 'patients', ['doc_type', 'doc_number'], unique=False)
    op.alter_column('patients', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('patients', 'middle_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('patients', 'first_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('patients', 'last_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint('uq_online_day_dep_date', 'online_days', type_='unique')
    op.drop_index(op.f('ix_online_days_id'), table_name='online_days')
    op.drop_index(op.f('ix_online_days_department'), table_name='online_days')
    op.drop_index(op.f('ix_online_days_date_str'), table_name='online_days')
    op.create_index('uq_online_day_dep_date__uniq_idx', 'online_days', ['department', 'date_str'], unique=1)
    op.create_index('ix_online_days_dep', 'online_days', ['department'], unique=False)
    op.create_index('ix_online_days_date', 'online_days', ['date_str'], unique=False)
    op.drop_index(op.f('ix_lab_results_test_code'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_order_id'), table_name='lab_results')
    op.create_index('ix_lab_results_order', 'lab_results', ['order_id'], unique=False)
    op.create_index('ix_lab_results_code', 'lab_results', ['test_code'], unique=False)
    op.alter_column('lab_results', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('lab_results', 'abnormal',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_lab_orders_visit_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_patient_id'), table_name='lab_orders')
    op.create_index('ix_lab_orders_visit', 'lab_orders', ['visit_id'], unique=False)
    op.create_index('ix_lab_orders_status', 'lab_orders', ['status'], unique=False)
    op.create_index('ix_lab_orders_patient', 'lab_orders', ['patient_id'], unique=False)
    op.alter_column('lab_orders', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('lab_orders', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'ordered'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_files_folder_id'), table_name='files')
    op.alter_column('emr', 'ai_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('emr', 'ai_suggestions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'social_history',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'family_history',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'allergies',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'medications',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'imaging_results',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'lab_results',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emr', 'vital_signs',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.alter_column('doctor_price_overrides', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('doctor_price_overrides', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('doctor_price_overrides', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'pending'"),
               existing_nullable=False)
    op.drop_constraint(None, 'daily_queues', type_='foreignkey')
    op.create_foreign_key(None, 'daily_queues', 'doctors', ['specialist_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text("(datetime('now'))"),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('audit_logs', 'payload',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('appointments', 'payment_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'cash'"),
               existing_nullable=True)
    op.alter_column('appointments', 'visit_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'paid'"),
               existing_nullable=True)
    op.create_index('idx_activations_machine_hash', 'activations', ['machine_hash'], unique=False)
    op.create_index('idx_activations_key', 'activations', ['key'], unique=False)
    op.alter_column('activations', 'status',
               existing_type=sa.VARCHAR(length=7),
               server_default=sa.text("'issued'"),
               existing_nullable=False)
    op.create_table('queue_tickets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=64), nullable=False),
    sa.Column('date_str', sa.VARCHAR(length=16), nullable=False),
    sa.Column('ticket_number', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'waiting'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_queue_dep_date_ticket__uniq_idx', 'queue_tickets', ['department', 'date_str', 'ticket_number'], unique=1)
    op.create_index('ix_queue_ticket', 'queue_tickets', ['ticket_number'], unique=False)
    op.create_index('ix_queue_status', 'queue_tickets', ['status'], unique=False)
    op.create_index('ix_queue_dep', 'queue_tickets', ['department'], unique=False)
    op.create_index('ix_queue_date', 'queue_tickets', ['date_str'], unique=False)
    op.create_table('medical_records',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('record_type', sa.VARCHAR(length=50), server_default=sa.text("'general'"), nullable=False),
    sa.Column('chief_complaint', sa.TEXT(), nullable=True),
    sa.Column('history_of_present_illness', sa.TEXT(), nullable=True),
    sa.Column('past_medical_history', sa.TEXT(), nullable=True),
    sa.Column('medications', sa.TEXT(), nullable=True),
    sa.Column('allergies', sa.TEXT(), nullable=True),
    sa.Column('family_history', sa.TEXT(), nullable=True),
    sa.Column('social_history', sa.TEXT(), nullable=True),
    sa.Column('review_of_systems', sa.TEXT(), nullable=True),
    sa.Column('physical_examination', sa.TEXT(), nullable=True),
    sa.Column('vital_signs', sa.TEXT(), nullable=True),
    sa.Column('assessment', sa.TEXT(), nullable=True),
    sa.Column('plan', sa.TEXT(), nullable=True),
    sa.Column('diagnosis', sa.TEXT(), nullable=True),
    sa.Column('treatment_notes', sa.TEXT(), nullable=True),
    sa.Column('follow_up_instructions', sa.TEXT(), nullable=True),
    sa.Column('additional_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'"), nullable=True),
    sa.Column('is_confidential', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medical_records_status', 'medical_records', ['status'], unique=False)
    op.create_index('idx_medical_records_patient_id', 'medical_records', ['patient_id'], unique=False)
    op.create_index('idx_medical_records_doctor_id', 'medical_records', ['doctor_id'], unique=False)
    op.create_index('idx_medical_records_created_at', 'medical_records', ['created_at'], unique=False)
    op.create_index('idx_medical_records_appointment_id', 'medical_records', ['appointment_id'], unique=False)
    # ### end Alembic commands ###

