"""Add EMR and Prescription tables for appointment flow

Revision ID: add_emr_prescription
Revises: 20250829_0002
Create Date: 2025-01-01 12:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_emr_prescription"
down_revision = "20250829_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create EMR table
    op.create_table(
        "emr",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("complaints", sa.Text(), nullable=True),
        sa.Column("anamnesis", sa.Text(), nullable=True),
        sa.Column("examination", sa.Text(), nullable=True),
        sa.Column("diagnosis", sa.Text(), nullable=True),
        sa.Column("icd10", sa.String(length=16), nullable=True),
        sa.Column("recommendations", sa.Text(), nullable=True),
        sa.Column("procedures", sa.JSON(), nullable=True),
        sa.Column("attachments", sa.JSON(), nullable=True),
        sa.Column("is_draft", sa.Boolean(), nullable=False, default=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            default=sa.func.now(),
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emr_appointment_id"), "emr", ["appointment_id"], unique=False
    )

    # Create Prescriptions table
    op.create_table(
        "prescriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("emr_id", sa.Integer(), nullable=False),
        sa.Column("medications", sa.JSON(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("doctor_notes", sa.Text(), nullable=True),
        sa.Column("is_draft", sa.Boolean(), nullable=False, default=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            default=sa.func.now(),
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("printed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["emr_id"],
            ["emr.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prescriptions_appointment_id"),
        "prescriptions",
        ["appointment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prescriptions_emr_id"), "prescriptions", ["emr_id"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prescriptions_emr_id"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_appointment_id"), table_name="prescriptions")
    op.drop_table("prescriptions")
    op.drop_index(op.f("ix_emr_appointment_id"), table_name="emr")
    op.drop_table("emr")
    # ### end Alembic commands ###
