"""
Generated helper documentation endpoints.
"""

from collections import Counter, defaultdict
from typing import Any, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Request

from app.api.deps import get_current_user
from app.models.user import User

router = APIRouter()

_HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}


def _iter_operations(schema: dict[str, Any]):
    for path, path_item in schema.get("paths", {}).items():
        for method, operation in path_item.items():
            if method.lower() in _HTTP_METHODS:
                yield path, method.lower(), operation


def _slugify_tag(tag: str) -> str:
    return tag.strip().lower().replace(" ", "-").replace("_", "-")


def _operation_index(schema: dict[str, Any]) -> dict[str, dict[str, Any]]:
    buckets: dict[str, dict[str, Any]] = {}

    for path, method, operation in _iter_operations(schema):
        tags = operation.get("tags") or ["untagged"]
        for raw_tag in tags:
            slug = _slugify_tag(raw_tag)
            bucket = buckets.setdefault(
                slug,
                {
                    "tag": raw_tag,
                    "slug": slug,
                    "description": "Generated from the current OpenAPI schema.",
                    "operation_count": 0,
                    "methods": set(),
                    "sample_operations": [],
                },
            )
            bucket["operation_count"] += 1
            bucket["methods"].add(method.upper())
            if len(bucket["sample_operations"]) < 5:
                bucket["sample_operations"].append(
                    {
                        "method": method.upper(),
                        "path": path,
                        "summary": operation.get("summary"),
                    }
                )

    for bucket in buckets.values():
        bucket["methods"] = sorted(bucket["methods"])

    return dict(sorted(buckets.items(), key=lambda item: (-item[1]["operation_count"], item[0])))


def _example_catalog() -> dict[str, Any]:
    return {
        "authentication_examples": {
            "oauth_password_login": {
                "route": "/api/v1/auth/login",
                "content_type": "application/x-www-form-urlencoded",
                "curl": "curl -X POST '/api/v1/auth/login' -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=admin&password=admin123'",
            },
            "minimal_login_json": {
                "route": "/api/v1/auth/minimal-login",
                "content_type": "application/json",
                "json": {"username": "admin", "password": "admin123"},
            },
        },
        "patient_examples": {
            "create_patient": {
                "route": "/api/v1/patients/",
                "method": "POST",
                "json": {
                    "first_name": "Иван",
                    "last_name": "Иванов",
                    "phone": "+998901234567",
                    "birth_date": "1990-01-01",
                },
            }
        },
        "visit_examples": {
            "create_visit": {
                "route": "/api/v1/visits/visits",
                "method": "POST",
                "json": {
                    "patient_id": 1,
                    "doctor_id": 1,
                    "visit_date": "2026-03-14",
                    "visit_time": "10:00",
                    "status": "scheduled",
                },
            }
        },
        "queue_examples": {
            "join_flow": {
                "start_route": "/api/v1/queue/join/start",
                "complete_route": "/api/v1/queue/join/complete",
                "note": "The modern queue flow is session-based: start first, then complete with the returned session context.",
            }
        },
    }


def _response_code_guide(schema: dict[str, Any]) -> list[dict[str, Any]]:
    counts: Counter[str] = Counter()
    for _path, _method, operation in _iter_operations(schema):
        for code in operation.get("responses", {}):
            if isinstance(code, str) and code.isdigit():
                counts[code] += 1

    descriptions = {
        "200": "Standard success response with a body.",
        "201": "Resource created successfully.",
        "202": "Accepted for background or deferred processing.",
        "204": "Success with no response body.",
        "400": "Client-side request shape or domain precondition error.",
        "401": "Missing or invalid authentication.",
        "403": "Authenticated but rejected by role or access rules.",
        "404": "Resource or linked record not found.",
        "409": "State conflict on selected routes.",
        "422": "Validation error generated by FastAPI/Pydantic.",
        "500": "Internal server error fallback.",
    }

    preferred_order = ["200", "201", "202", "204", "400", "401", "403", "404", "409", "422", "500"]
    result: list[dict[str, Any]] = []
    for code in preferred_order:
        if counts.get(code):
            result.append(
                {
                    "code": code,
                    "operations": counts[code],
                    "description": descriptions.get(code, "Route-specific response code."),
                }
            )
    return result


def _auth_route_families(schema: dict[str, Any]) -> list[dict[str, Any]]:
    families: dict[str, list[str]] = defaultdict(list)
    for path in sorted(schema.get("paths", {})):
        if path.startswith("/api/v1/authentication"):
            families["authentication"].append(path)
        elif path.startswith("/api/v1/auth"):
            families["auth"].append(path)
        elif path.startswith("/api/v1/2fa"):
            families["two-factor"].append(path)
        elif path.startswith("/api/v1/phone-verification"):
            families["phone-verification"].append(path)
        elif path.startswith("/api/v1/password-reset"):
            families["password-reset"].append(path)

    return [
        {"family": family, "sample_paths": paths[:8], "path_count": len(paths)}
        for family, paths in sorted(families.items())
    ]


@router.get("/documentation/endpoints")
async def get_detailed_endpoints_documentation(
    request: Request,
    category: Optional[str] = Query(None, description="Tag/category slug from the generated schema"),
    current_user: User = Depends(get_current_user),
):
    """Return a generated endpoint index derived from the current OpenAPI schema."""
    schema = request.app.openapi()
    categories = _operation_index(schema)

    if category:
        slug = _slugify_tag(category)
        if slug not in categories:
            raise HTTPException(status_code=404, detail=f"Категория '{category}' не найдена")
        return {slug: categories[slug]}

    return {
        "kind": "generated-endpoint-index",
        "canonical_sources": {
            "swagger_ui": "/docs",
            "redoc": "/redoc",
            "openapi_json": "/openapi.json",
        },
        "category_count": len(categories),
        "categories": list(categories.values()),
        "reader_note": "This endpoint is a generated helper index. The canonical contract still lives in /docs and /openapi.json.",
    }


@router.get("/documentation/examples")
async def get_api_examples(
    endpoint: Optional[str] = Query(None, description="Example group key"),
    current_user: User = Depends(get_current_user),
):
    """Return curated live examples for selected route families."""
    examples = _example_catalog()

    if endpoint:
        if endpoint not in examples:
            raise HTTPException(
                status_code=404,
                detail=f"Примеры для эндпоинта '{endpoint}' не найдены",
            )
        return {endpoint: examples[endpoint]}

    return {
        "kind": "curated-live-examples",
        "canonical_sources": {
            "swagger_ui": "/docs",
            "openapi_json": "/openapi.json",
        },
        "examples": examples,
        "reader_note": "Examples are intentionally small and only cover selected live flows.",
    }


@router.get("/documentation/status-codes")
async def get_status_codes_documentation(request: Request):
    """Return common response patterns derived from the current OpenAPI schema."""
    schema = request.app.openapi()
    return {
        "kind": "generated-status-code-guide",
        "common_codes": _response_code_guide(schema),
        "notes": [
            "422 is typically the most common generated non-2xx code in the current schema.",
            "Not every runtime/stateful failure is fully represented in OpenAPI.",
            "Use /docs or /openapi.json for route-specific responses.",
        ],
    }


@router.get("/documentation/authentication")
async def get_authentication_documentation(request: Request):
    """Return a live authentication guide based on current OpenAPI metadata."""
    schema = request.app.openapi()
    security_schemes = schema.get("components", {}).get("securitySchemes", {})
    token_urls = []
    for scheme in security_schemes.values():
        flows = scheme.get("flows", {})
        password_flow = flows.get("password")
        if password_flow and password_flow.get("tokenUrl"):
            token_urls.append(password_flow["tokenUrl"])

    return {
        "kind": "generated-auth-guide",
        "overview": "The API uses Bearer-token authentication. Canonical auth details come from the generated OpenAPI security schemes.",
        "security_schemes": security_schemes,
        "token_urls": token_urls,
        "route_families": _auth_route_families(schema),
        "notes": [
            "The /api/v1/auth/* and /api/v1/authentication/* surfaces are both live and serve different purposes.",
            "Two-factor, phone verification, and password reset routes are adjacent auth-related families, not one single login flow.",
            "Use /docs or /openapi.json when a consumer needs exact request/response details.",
        ],
    }
