import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { expect, test } from '@playwright/test';

const rootDir = path.resolve(process.cwd(), '..');
const artifactsDir = path.join(rootDir, 'output', 'playwright', 'messaging-rollout-proof');
const attachmentPath = path.join(artifactsDir, 'messaging-rollout-proof.txt');
const voicePath = path.join(artifactsDir, 'messaging-rollout-proof.wav');

test.describe.configure({ mode: 'serial' });

test.use({
  baseURL: 'http://localhost:5173',
  viewport: { width: 1440, height: 1200 },
});

const LIVE_CREDENTIALS = {
  doctor: { username: 'doctor@example.com', route: /\/doctor-panel(\?.*)?$/ },
  admin: { username: 'admin', route: /\/admin(\?.*)?$/ },
};

function ensureArtifactsDir() {
  fs.mkdirSync(artifactsDir, { recursive: true });
  fs.writeFileSync(
    attachmentPath,
    'Messaging rollout proof attachment.\nGenerated by Playwright smoke.\n',
    'utf8',
  );
  const voiceScript = String.raw`
import os
import wave
import struct

path = ${JSON.stringify(voicePath)}
sample_rate = 16000
duration_seconds = 1
frames = b''.join(struct.pack('<h', 0) for _ in range(sample_rate * duration_seconds))

os.makedirs(os.path.dirname(path), exist_ok=True)
with wave.open(path, 'wb') as wav_file:
    wav_file.setnchannels(1)
    wav_file.setsampwidth(2)
    wav_file.setframerate(sample_rate)
    wav_file.writeframes(frames)
`;

  execFileSync('python', ['-c', voiceScript], {
    cwd: path.join(rootDir, 'backend'),
    encoding: 'utf8',
  });
}

function createBackendSession(username) {
  const script = String.raw`
import json
import sys
from datetime import timedelta

sys.path.insert(0, r"${path.join(rootDir, 'backend')}")

from sqlalchemy import or_

from app.api.deps import create_access_token
from app.db.session import SessionLocal
from app.models.user import User

target_username = ${JSON.stringify(username)}
db = SessionLocal()
try:
    user = (
        db.query(User)
        .filter(or_(User.username == target_username, User.email == target_username))
        .order_by(User.id.asc())
        .first()
    )
    if user is None:
        raise SystemExit(f"User not found: {target_username}")

    profile = {
        "id": user.id,
        "username": user.username,
        "email": user.email,
        "full_name": user.full_name,
        "role": user.role,
        "is_active": user.is_active,
        "is_superuser": user.is_superuser,
    }

    token = create_access_token(
        data={
            "sub": str(user.id),
            "username": user.username,
            "user_id": user.id,
        },
        expires_delta=timedelta(hours=8),
    )
    print(json.dumps({"access_token": token, "user": profile}, ensure_ascii=False))
finally:
    db.close()
`;

  const output = execFileSync('python', ['-c', script], {
    cwd: path.join(rootDir, 'backend'),
    encoding: 'utf8',
  }).trim();

  return JSON.parse(output);
}

async function seedAuthContext(context, credentials) {
  const session = createBackendSession(credentials.username);

  await context.addInitScript(({ token, profile }) => {
    sessionStorage.setItem('auth_token', token);
    sessionStorage.setItem('auth_profile', JSON.stringify(profile));
    sessionStorage.setItem('user', JSON.stringify(profile));
    sessionStorage.setItem('auth_token', token);
    sessionStorage.setItem('auth_profile', JSON.stringify(profile));
  }, {
    token: session.access_token,
    profile: session.user,
  });

  return session;
}

async function openChatWindow(page) {
  const chatButton = page.getByTitle(/Сообщения/).first();
  await expect(chatButton).toBeVisible({ timeout: 30000 });
  await chatButton.click();
  await expect(page.getByRole('button', { name: /Новый чат/ })).toBeVisible({ timeout: 15000 });
}

async function openConversation(page, target) {
  const query = typeof target === 'string' ? target : target.query;
  const userId = typeof target === 'object' ? target.userId : null;
  const exactPattern = new RegExp(`^\\s*${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*$`, 'i');
  const exactTarget = userId
    ? page.locator(`.conversations-list .conversation-item[data-user-id="${userId}"]`).first()
    : page.locator('.conversations-list .conversation-item').filter({ hasText: exactPattern }).first();
  try {
    await expect(exactTarget).toBeVisible({ timeout: 15000 });
    await exactTarget.click();
  } catch {
    await page.locator('button[title="Новый чат"]').click();
    const searchInput = page.locator('input[placeholder="Поиск..."]');
    await searchInput.fill(query);
    const exactSearchTarget = userId
      ? page.locator(`.user-search-results .conversation-item[data-user-id="${userId}"]`).first()
      : page.locator('.user-search-results .conversation-item').filter({ hasText: exactPattern }).first();
    try {
      await expect(exactSearchTarget).toBeVisible({ timeout: 15000 });
      await exactSearchTarget.click();
    } catch {
      const target = page.locator('.user-search-results .conversation-item').first();
      await expect(target).toBeVisible({ timeout: 15000 });
      await target.click();
    }
  }
  await expect(page.locator('textarea[aria-label="Введите сообщение"]')).toBeVisible({ timeout: 15000 });
}

async function sendTextMessage(page, text) {
  const composer = page.locator('textarea[aria-label="Введите сообщение"]');
  await composer.fill(text);
  await page.locator('button[title="Отправить"]').click();
  await expect(page.getByText(text)).toBeVisible({ timeout: 20000 });
}

async function attachFile(page) {
  await page.locator('button[title="Прикрепить файл"]').click();
  await page.locator('input[type="file"]').setInputFiles(attachmentPath);
  await expect(page.locator('.message-file .file-link').last()).toContainText('messaging-rollout-proof.txt', { timeout: 20000 });
}

async function sendVoiceMessage(page, recipientId) {
  const voiceBase64 = fs.readFileSync(voicePath).toString('base64');

  const response = await page.evaluate(async ({ voiceBase64Data, recipientIdValue }) => {
    const binary = Uint8Array.from(atob(voiceBase64Data), (char) => char.charCodeAt(0));
    const blob = new Blob([binary], { type: 'audio/wav' });
    const formData = new FormData();
    formData.append('audio_file', blob, 'voice.wav');
    formData.append('recipient_id', String(recipientIdValue));

    const token = sessionStorage.getItem('auth_token') || sessionStorage.getItem('auth_token');
    const uploadResponse = await fetch('/api/v1/messages/send-voice', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
      },
      body: formData,
    });

    const payload = await uploadResponse.text();
    if (!uploadResponse.ok) {
      throw new Error(payload || `Voice upload failed with ${uploadResponse.status}`);
    }

    return payload;
  }, {
    voiceBase64Data: voiceBase64,
    recipientIdValue: recipientId,
  });

  return response;
}

async function openAiWidget(page) {
  await page.locator('button[title="Открыть AI чат"]').click();
  await expect(page.locator('.chat-widget')).toBeVisible({ timeout: 15000 });
  await expect(page.locator('.chat-widget').getByTitle('Новый чат')).toBeVisible({ timeout: 10000 });
}

async function sendAiPrompt(page, prompt) {
  const widget = page.locator('.chat-widget');
  const sessionCreated = page.waitForResponse((response) =>
    response.url().includes('/api/v1/ai/chat/sessions') &&
    response.request().method() === 'POST' &&
    response.status() === 200,
  );
  const answerReceived = page.waitForResponse((response) =>
    response.url().includes('/api/v1/ai/chat/sessions/') &&
    response.url().includes('/messages') &&
    response.request().method() === 'POST' &&
    response.status() === 200,
  );

  await widget.locator('textarea').fill(prompt);
  await widget.locator('button[title="Отправить"]').click();

  await Promise.all([sessionCreated, answerReceived]);
  await expect(widget.locator('.chat-message.assistant').last()).toBeVisible({ timeout: 30000 });
}

test('messaging rollout proof: two-user chat, attachment, voice, reconnect', async ({ browser }, testInfo) => {
  testInfo.setTimeout(180000);
  ensureArtifactsDir();

  const networkEvents = [];
  const consoleEvents = [];

  const doctorContext = await browser.newContext({
    baseURL: 'http://localhost:5173',
    viewport: { width: 1440, height: 1200 },
  });
  const adminContext = await browser.newContext({
    baseURL: 'http://localhost:5173',
    viewport: { width: 1440, height: 1200 },
  });

  const doctorSession = await seedAuthContext(doctorContext, LIVE_CREDENTIALS.doctor);
  const adminSession = await seedAuthContext(adminContext, LIVE_CREDENTIALS.admin);

  await adminContext.addInitScript(() => {
    const originalMediaDevices = navigator.mediaDevices || {};
    const originalGetUserMedia = originalMediaDevices.getUserMedia?.bind(originalMediaDevices);

    Object.defineProperty(navigator, 'mediaDevices', {
      configurable: true,
      value: {
        ...originalMediaDevices,
        getUserMedia: async (constraints) => {
          try {
            const AudioContextCtor = window.AudioContext || window.webkitAudioContext;
            const audioContext = new AudioContextCtor();
            await audioContext.resume();

            const oscillator = audioContext.createOscillator();
            const gainNode = audioContext.createGain();
            const destination = audioContext.createMediaStreamDestination();

            gainNode.gain.value = 0.01;
            oscillator.frequency.value = 440;
            oscillator.connect(gainNode);
            gainNode.connect(destination);
            oscillator.start();

            const stream = destination.stream;
            const audioTrack = stream.getAudioTracks()[0];
            if (audioTrack) {
              const originalStop = audioTrack.stop.bind(audioTrack);
              audioTrack.stop = () => {
                try {
                  oscillator.stop();
                } catch {
                  // Ignore oscillator shutdown errors in test stubs.
                }
                originalStop();
                void audioContext.close();
              };
            }

            return stream;
          } catch (error) {
            if (originalGetUserMedia) {
              return originalGetUserMedia(constraints);
            }
            throw error;
          }
        },
      },
    });
  });

  const doctorPage = await doctorContext.newPage();
  const adminPage = await adminContext.newPage();

  for (const [role, page] of [['doctor', doctorPage], ['admin', adminPage]]) {
    page.on('request', (request) => {
      if (request.url().includes('/api/v1/')) {
        networkEvents.push(`[${role}] ${request.method()} ${request.url()}`);
      }
    });
    page.on('console', (message) => {
      consoleEvents.push(`[${role}] ${message.type()}: ${message.text()}`);
    });
  }

  await doctorPage.goto('/doctor-panel');
  await expect(doctorPage).toHaveURL(/\/doctor-panel(\?.*)?$/);
  await adminPage.goto('/admin');
  await expect(adminPage).toHaveURL(/\/admin(\?.*)?$/);

  await openChatWindow(adminPage);
  await openConversation(adminPage, { query: 'Doctor User', userId: doctorSession.user.id });

  const textMessage = `Regression smoke ${Date.now()}`;
  await sendTextMessage(adminPage, textMessage);

  await doctorPage.reload({ waitUntil: 'networkidle' });
  await openChatWindow(doctorPage);
  await openConversation(doctorPage, { query: 'admin', userId: adminSession.user.id });
  await expect(doctorPage.getByText(textMessage)).toBeVisible({ timeout: 30000 });

  await attachFile(adminPage);
  await doctorPage.reload({ waitUntil: 'networkidle' });
  await openChatWindow(doctorPage);
  await openConversation(doctorPage, { query: 'admin', userId: adminSession.user.id });
  await expect(doctorPage.locator('.message-file .file-link').last()).toContainText('messaging-rollout-proof.txt', { timeout: 30000 });

  await sendVoiceMessage(adminPage, doctorSession.user.id);
  await doctorPage.reload({ waitUntil: 'networkidle' });
  await openChatWindow(doctorPage);
  await openConversation(doctorPage, { query: 'admin', userId: adminSession.user.id });
  await expect(doctorPage.locator('button[title="Воспроизвести"]')).toBeVisible({ timeout: 30000 });

  await doctorPage.screenshot({
    path: path.join(artifactsDir, 'messaging-rollout-proof-chat.png'),
    fullPage: true,
  });

  fs.writeFileSync(
    path.join(artifactsDir, 'messaging-rollout-proof-network.json'),
    JSON.stringify(networkEvents, null, 2),
    'utf8',
  );
  fs.writeFileSync(
    path.join(artifactsDir, 'messaging-rollout-proof-console.log'),
    consoleEvents.join('\n'),
    'utf8',
  );

  await doctorContext.close();
  await adminContext.close();
});

test('messaging rollout proof: doctor AI widget round-trip', async ({ browser }, testInfo) => {
  testInfo.setTimeout(120000);
  ensureArtifactsDir();

  const networkEvents = [];
  const doctorContext = await browser.newContext({
    baseURL: 'http://localhost:5173',
    viewport: { width: 1440, height: 1200 },
  });
  await seedAuthContext(doctorContext, LIVE_CREDENTIALS.doctor);
  const doctorPage = await doctorContext.newPage();

  doctorPage.on('request', (request) => {
    if (request.url().includes('/api/v1/')) {
      networkEvents.push(`${request.method()} ${request.url()}`);
    }
  });

  await doctorPage.goto('/doctor-panel');
  await expect(doctorPage).toHaveURL(/\/doctor-panel(\?.*)?$/);
  await openAiWidget(doctorPage);

  const prompt = `AI rollout smoke ${Date.now()}`;
  await sendAiPrompt(doctorPage, prompt);

  await doctorPage.screenshot({
    path: path.join(artifactsDir, 'messaging-rollout-proof-ai.png'),
    fullPage: true,
  });

  fs.writeFileSync(
    path.join(artifactsDir, 'messaging-rollout-proof-ai-network.json'),
    JSON.stringify(networkEvents, null, 2),
    'utf8',
  );

  await doctorContext.close();
});
