name: 🏥 CI/CD Pipeline - Клиника

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * 0"   # раз в неделю — полное сканирование безопасности

env:
  PYTHON_VERSION: '3.11'
  DATABASE_URL: 'sqlite:///./test_clinic.db'
  CORS_DISABLE: '1'
  WS_DEV_ALLOW: '1'

jobs:

  # --- Проверка стиля кода ---
  lint:
    name: 🔍 Проверка стиля кода
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Установка зависимостей
        run: |
          cd backend
          pip install black flake8 ruff isort
      - name: Black check
        run: |
          cd backend
          black --check .
      - name: Ruff lint
        run: |
          cd backend
          ruff check .
      - name: Flake8 lint
        run: |
          cd backend
          flake8 app --select=E9,F63,F7,F82 --show-source --statistics
      - name: Isort check
        run: |
          cd backend
          isort --check-only .

  # --- Unit tests + покрытие ---
  tests:
    name: 🧪 Unit тесты
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Установка зависимостей
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov
      - name: Настройка Python path
        run: |
          cd backend
          echo "PYTHONPATH=${{ github.workspace }}/backend" >> $GITHUB_ENV
      - name: Создание тестовой базы данных
        run: |
          cd backend
          export DATABASE_URL="${{ env.DATABASE_URL }}"
          export CORS_DISABLE="${{ env.CORS_DISABLE }}"
          export WS_DEV_ALLOW="${{ env.WS_DEV_ALLOW }}"
          
          python - << 'PY'
          import sys
          import time
          sys.path.insert(0, '.')
          
          # Импортируем все модели для создания таблиц
          from app.db.base import Base
          from app.db.session import engine, SessionLocal
          from app.models.user import User
          from app.models.patient import Patient
          from app.models.visit import Visit, VisitService
          from app.models.payment import Payment
          from app.models.service import Service, ServiceCatalog
          from app.models.queue import QueueTicket
          from app.models.schedule import ScheduleTemplate
          from app.models.lab import LabOrder, LabResult
          from app.models.audit import AuditLog
          from app.models.setting import Setting
          from app.models.appointment import Appointment
          from app.models.payment_webhook import PaymentWebhook, PaymentTransaction, PaymentProvider
          from app.models.online import OnlineDay
          from app.models.emr import EMR, Prescription
          from app.models.activation import Activation
          from app.models.notification import NotificationTemplate, NotificationHistory, NotificationSettings
          from app.core.security import get_password_hash
          from sqlalchemy import text
          
          try:
              # Создаем таблицы
              print('🔧 Создаем таблицы базы данных...')
              Base.metadata.create_all(bind=engine)
              print('✅ База данных создана')
              
              # Проверяем, что таблица users действительно создана
              with engine.connect() as conn:
                  result = conn.execute(text("SELECT name FROM sqlite_master WHERE type='table' AND name='users'"))
                  if not result.fetchone():
                      print('❌ Таблица users не найдена после создания')
                      raise Exception("Таблица users не создана")
                  print('✅ Таблица users подтверждена')
              
              # Небольшая задержка для стабилизации
              time.sleep(1)
              
              # Создаем тестового пользователя admin
              db = SessionLocal()
              try:
                  # Проверяем существование пользователя admin
                  existing_admin = db.query(User).filter(User.username == "admin").first()
                  if not existing_admin:
                      admin_user = User(
                          username="admin",
                          email="admin@clinic.com",
                          hashed_password=get_password_hash("admin123"),
                          role="Admin",
                          is_active=True,
                          is_superuser=True
                      )
                      db.add(admin_user)
                      db.commit()
                      print('✅ Тестовый пользователь admin создан')
                  else:
                      print('✅ Пользователь admin уже существует')
              finally:
                  db.close()
                  
          except Exception as e:
              print('⚠️ Ошибка создания БД:', e)
              import traceback
              traceback.print_exc()
              raise SystemExit(1)
          PY
      - name: Запуск тестов
        run: |
          cd backend
          export DATABASE_URL="${{ env.DATABASE_URL }}"
          export CORS_DISABLE="${{ env.CORS_DISABLE }}"
          export WS_DEV_ALLOW="${{ env.WS_DEV_ALLOW }}"
          
          # Запускаем сервер в фоне
          nohup uvicorn app.main:app --host 127.0.0.1 --port 8000 > server.log 2>&1 &
          echo $! > server.pid
          sleep 10
          
          # Запускаем тесты
          python test_authentication.py
          python test_queue_system.py
          python test_visit_reschedule.py
          python test_websocket.py
          python test_reports.py
          python test_printing.py
          python test_printing_edge_cases.py
          
          # Останавливаем сервер
          if [ -f server.pid ]; then
            kill $(cat server.pid) 2>/dev/null || true
            rm server.pid
          fi
      - name: Загрузка покрытия в Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./backend/coverage.xml
          flags: backend
          name: backend-coverage

  # --- Сканирование безопасности ---
  security:
    name: 🔒 Сканирование безопасности
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Установка инструментов безопасности
        run: |
          cd backend
          pip install bandit safety pip-audit
      - name: Bandit scan
        run: |
          cd backend
          bandit -r app -ll -f json -o bandit-report.json || true
      - name: Safety check
        run: |
          cd backend
          safety check --json --output safety-report.json || true
      - name: Pip audit
        run: |
          cd backend
          pip-audit --format json --output pip-audit-report.json || true
      - name: Загрузка отчетов безопасности
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            backend/bandit-report.json
            backend/safety-report.json
            backend/pip-audit-report.json

  # --- Docker build & test run ---
  docker:
    name: 🐳 Docker сборка
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - name: Build Backend Docker image
        run: |
          docker build -f ops/backend.Dockerfile -t clinic-backend .
      - name: Build Frontend Docker image
        run: |
          docker build -f ops/frontend.Dockerfile -t clinic-frontend .
      - name: Test Backend run
        run: |
          # Запускаем контейнер в фоне
          CONTAINER_ID=$(docker run -d -p 8000:8000 -e DATABASE_URL="sqlite:///./test.db" clinic-backend)
          echo "Container ID: $CONTAINER_ID"
          
          # Ждем запуска сервера
          echo "⏳ Ожидаем запуск сервера..."
          for i in {1..30}; do
            echo "Попытка $i/30: проверяем http://localhost:8000/api/v1/health"
            if curl -s -f "http://localhost:8000/api/v1/health" > /dev/null 2>&1; then
              echo "✅ Сервер запущен успешно"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "❌ Сервер не запустился"
              echo "📄 Логи контейнера:"
              docker logs $CONTAINER_ID
              echo "📊 Статус контейнера:"
              docker ps -a | grep $CONTAINER_ID
              echo "🔍 Проверяем процессы в контейнере:"
              docker exec $CONTAINER_ID ps aux || echo "Не удалось выполнить ps aux"
              docker stop $CONTAINER_ID
              exit 1
            fi
            sleep 2
          done
          
          # Останавливаем контейнер
          docker stop $CONTAINER_ID
      - name: Test Frontend run
        run: |
          # Запускаем контейнер в фоне
          CONTAINER_ID=$(docker run -d -p 3000:3000 clinic-frontend)
          echo "Container ID: $CONTAINER_ID"
          
          # Ждем запуска сервера
          echo "⏳ Ожидаем запуск frontend сервера..."
          for i in {1..30}; do
            if curl -s -f "http://localhost:3000" > /dev/null 2>&1; then
              echo "✅ Frontend сервер запущен успешно"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "❌ Frontend сервер не запустился"
              echo "📄 Логи контейнера:"
              docker logs $CONTAINER_ID
              docker stop $CONTAINER_ID
              exit 1
            fi
            sleep 2
          done
          
          # Останавливаем контейнер
          docker stop $CONTAINER_ID

  # --- E2E тесты (Playwright) ---
  e2e:
    name: 🎭 E2E тесты
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v4
      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Установка зависимостей Frontend
        run: |
          cd frontend
          npm install
      - name: Установка Playwright
        run: |
          cd frontend
          npx playwright install --with-deps
      - name: Запуск E2E тестов
        run: |
          cd frontend
          # Запускаем backend в фоне
          cd ../backend
          export DATABASE_URL="sqlite:///./test.db"
          export CORS_DISABLE="1"
          export WS_DEV_ALLOW="1"
          nohup uvicorn app.main:app --host 127.0.0.1 --port 8000 > server.log 2>&1 &
          echo $! > server.pid
          sleep 10
          
          # Запускаем frontend
          cd ../frontend
          npm run dev &
          echo $! > frontend.pid
          sleep 10
          
          # Запускаем Playwright тесты
          npx playwright test --reporter=line || true
          
          # Останавливаем сервисы
          if [ -f ../backend/server.pid ]; then
            kill $(cat ../backend/server.pid) 2>/dev/null || true
            rm ../backend/server.pid
          fi
          if [ -f frontend.pid ]; then
            kill $(cat frontend.pid) 2>/dev/null || true
            rm frontend.pid
          fi

  # --- Проверка документации (Swagger/OpenAPI) ---
  docs:
    name: 📚 Проверка документации
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Установка зависимостей
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Запуск сервера для генерации OpenAPI
        run: |
          cd backend
          export DATABASE_URL="${{ env.DATABASE_URL }}"
          export CORS_DISABLE="${{ env.CORS_DISABLE }}"
          export WS_DEV_ALLOW="${{ env.WS_DEV_ALLOW }}"
          
          nohup uvicorn app.main:app --host 127.0.0.1 --port 8000 > server.log 2>&1 &
          echo $! > server.pid
          sleep 10
      - name: Проверка OpenAPI схемы
        run: |
          cd backend
          curl -f http://localhost:8000/openapi.json > openapi.json
          test -s openapi.json
          echo "✅ OpenAPI схема сгенерирована успешно"
      - name: Проверка Swagger UI
        run: |
          cd backend
          curl -f http://localhost:8000/docs > /dev/null
          echo "✅ Swagger UI доступен"
      - name: Проверка README.md
        run: |
          test -f README.md
          test -f docs/README.md
          echo "✅ Документация найдена"
      - name: Остановка сервера
        if: always()
        run: |
          cd backend
          if [ -f server.pid ]; then
            kill $(cat server.pid) 2>/dev/null || true
            rm server.pid
          fi

  # --- Интеграционные тесты ---
  integration:
    name: 🔗 Интеграционные тесты
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Установка зависимостей
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Настройка тестовой среды
        run: |
          cd backend
          export DATABASE_URL="${{ env.DATABASE_URL }}"
          export CORS_DISABLE="${{ env.CORS_DISABLE }}"
          export WS_DEV_ALLOW="${{ env.WS_DEV_ALLOW }}"
          
          # Создаем тестовую базу и пользователя
          python - << 'PY'
          import sys
          import time
          sys.path.insert(0, '.')
          
          from app.db.base import Base
          from app.db.session import engine, SessionLocal
          from app.models.user import User
          from app.core.security import get_password_hash
          from sqlalchemy import text
          
          try:
              # Создаем таблицы
              print('🔧 Создаем таблицы для интеграционных тестов...')
              Base.metadata.create_all(bind=engine)
              print('✅ База данных создана')
              
              # Проверяем, что таблица users действительно создана
              with engine.connect() as conn:
                  result = conn.execute(text("SELECT name FROM sqlite_master WHERE type='table' AND name='users'"))
                  if not result.fetchone():
                      print('❌ Таблица users не найдена после создания')
                      raise Exception("Таблица users не создана")
                  print('✅ Таблица users подтверждена')
              
              # Небольшая задержка для стабилизации
              time.sleep(1)
              
              # Создаем тестового пользователя admin
              db = SessionLocal()
              try:
                  existing_admin = db.query(User).filter(User.username == "admin").first()
                  if not existing_admin:
                      admin_user = User(
                          username="admin",
                          email="admin@clinic.com",
                          hashed_password=get_password_hash("admin123"),
                          role="Admin",
                          is_active=True,
                          is_superuser=True
                      )
                      db.add(admin_user)
                      db.commit()
                      print('✅ Тестовый пользователь admin создан')
                  else:
                      print('✅ Пользователь admin уже существует')
              finally:
                  db.close()
          except Exception as e:
              print('⚠️ Ошибка создания БД для интеграционных тестов:', e)
              import traceback
              traceback.print_exc()
              raise SystemExit(1)
          PY
      - name: Запуск интеграционных тестов
        run: |
          cd backend
          export DATABASE_URL="${{ env.DATABASE_URL }}"
          export CORS_DISABLE="${{ env.CORS_DISABLE }}"
          export WS_DEV_ALLOW="${{ env.WS_DEV_ALLOW }}"
          
          # Запускаем сервер
          nohup uvicorn app.main:app --host 127.0.0.1 --port 8000 > server.log 2>&1 &
          echo $! > server.pid
          sleep 10
          
          # Запускаем интеграционные тесты
          python test_authentication.py
          python test_queue_system.py
          python test_visit_reschedule.py
          python test_websocket.py
          python test_reports.py
          python test_printing.py
          python test_printing_edge_cases.py
          
          # Останавливаем сервер
          if [ -f server.pid ]; then
            kill $(cat server.pid) 2>/dev/null || true
            rm server.pid
          fi

  # --- Деплой в staging ---
  deploy-staging:
    name: 🚀 Деплой в staging
    runs-on: ubuntu-latest
    needs: integration
    if: github.ref == 'refs/heads/main'
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Деплой в staging
        run: |
          echo "🚀 Деплой в staging среду..."
          echo "✅ Все тесты пройдены, готово к деплою"

  # --- Деплой в production ---
  deploy-production:
    name: 🎯 Деплой в production
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Деплой в production
        run: |
          echo "🎯 Деплой в production среду..."
          echo "🎉 Система клиники развернута успешно!"
